--------------------------------------------------------
--  DDL for Table ENTERPRISE_STRUCTURE_MAPPING
--------------------------------------------------------

  CREATE TABLE "XXSUPCNV"."ENTERPRISE_STRUCTURE_MAPPING" 
   (	"LEGAL_ENTITY_NAME" VARCHAR2(64 BYTE) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'Legal Entity Name'), 
	"SUBSIDIARY_INTERNAL_ID" VARCHAR2(64 BYTE) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'Subsidiary Internal ID'), 
	"SUBSIDIARY" VARCHAR2(64 BYTE) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'Subsidiary'), 
	"COUNTRY_REGION" VARCHAR2(64 BYTE) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'Country Region'), 
	"COUNTRY" VARCHAR2(64 BYTE) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'Country'), 
	"LEGAL_ADDRESS" VARCHAR2(256 BYTE) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'Legal Address'), 
	"ORACLE_LEGAL_ENTITY_NAME" VARCHAR2(64 BYTE) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'Oracle Legal Entity Name'), 
	"PRIMARY_LEDGER" VARCHAR2(256 BYTE) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'Primary Ledger'), 
	"PRIMARY_LEDGER_CURRENCY" VARCHAR2(64 BYTE) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'Primary Ledger Currency'), 
	"BUSINESS_UNIT_NAME" VARCHAR2(64 BYTE) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'Business Unit Name'), 
	"FA_SUB_LEDGER" VARCHAR2(64 BYTE) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'FA Sub-Ledger')
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
  /