 /******************************************************************************************
	PURPOSE : GRANT Privileges script to XXMAP tables and packages.
    Change History																	    
    Developer        Date         Version     Comments and changes made				    
    -------------   ------       ----------  -------------------------------------------------------------
    Harish.V        25-06-2025      1.0         Initial Development
	Harish.V        26-07-2025      1.1         Added Delete,Update Grant to XXMAP_GL_E001_TEMP_COA_COMB_DATA
	Harish.V        08-12-2025      1.2         Added  Select,Insert,Delete Grants on XXMAP_GL_E001_EXCLUDE_ACCOUNTS
   *******************************************************************************************************/
GRANT UPDATE ON XXMAP.XXMAP_GL_E001_TEMP_COA_COMB_DATA to XXINT;   
GRANT DELETE ON XXMAP.XXMAP_GL_E001_TEMP_COA_COMB_DATA to XXINT;   
GRANT SELECT ON XXMAP.XXMAP_GL_E001_COA_NSERP_DATA to XXCNV;
GRANT SELECT ON XXMAP.XXMAP_GL_E001_KASEYA_NS_ACCOUNT to XXCNV;
GRANT SELECT ON XXMAP.XXMAP_GL_E001_KASEYA_NS_ACCTCC to XXCNV;
GRANT SELECT ON XXMAP.XXMAP_GL_E001_KASEYA_NS_COMPANY to XXCNV;
GRANT SELECT ON XXMAP.XXMAP_GL_E001_KASEYA_NS_COSTCENTER to XXCNV;
GRANT SELECT ON XXMAP.XXMAP_GL_E001_KASEYA_NS_DIVISON to XXCNV;
GRANT SELECT ON XXMAP.XXMAP_GL_E001_KASEYA_NS_FUTURE1 to XXCNV;
GRANT SELECT ON XXMAP.XXMAP_GL_E001_KASEYA_NS_FUTURE2 to XXCNV;
GRANT SELECT ON XXMAP.XXMAP_GL_E001_KASEYA_NS_FUTURE3 to XXCNV;
GRANT SELECT ON XXMAP.XXMAP_GL_E001_KASEYA_NS_INTERCOMPANY to XXCNV;
GRANT SELECT ON XXMAP.XXMAP_GL_E001_KASEYA_NS_LOCATION to XXCNV;
GRANT SELECT ON XXMAP.XXMAP_GL_E001_KASEYA_NS_PRODUCTLINE to XXCNV;
GRANT SELECT ON XXMAP.XXMAP_GL_E001_TEMP_COA_COMB_DATA to XXCNV;
GRANT DELETE ON XXMAP.XXMAP_GL_CONCUR_VENDOR_VALUES_REF to XXINT;
GRANT DELETE ON XXMAP.XXMAP_GL_JOB_PARAMETERS_REF to XXINT;
GRANT DELETE ON XXMAP.XXMAP_GL_SOURCES_REF to XXINT;
GRANT INSERT ON XXMAP.XXMAP_GL_CONCUR_VENDOR_VALUES_REF to XXINT;
GRANT INSERT ON XXMAP.XXMAP_GL_E001_COA_NSERP_DATA to XXINT;
GRANT INSERT ON XXMAP.XXMAP_GL_E001_KASEYA_NS_ACCOUNT to XXINT;
GRANT INSERT ON XXMAP.XXMAP_GL_E001_KASEYA_NS_ACCTCC to XXINT;
GRANT INSERT ON XXMAP.XXMAP_GL_E001_KASEYA_NS_COMPANY to XXINT;
GRANT INSERT ON XXMAP.XXMAP_GL_E001_KASEYA_NS_COSTCENTER to XXINT;
GRANT INSERT ON XXMAP.XXMAP_GL_E001_KASEYA_NS_DIVISON to XXINT;
GRANT INSERT ON XXMAP.XXMAP_GL_E001_KASEYA_NS_FUTURE1 to XXINT;
GRANT INSERT ON XXMAP.XXMAP_GL_E001_KASEYA_NS_FUTURE2 to XXINT;
GRANT INSERT ON XXMAP.XXMAP_GL_E001_KASEYA_NS_FUTURE3 to XXINT;
GRANT INSERT ON XXMAP.XXMAP_GL_E001_KASEYA_NS_INTERCOMPANY to XXINT;
GRANT INSERT ON XXMAP.XXMAP_GL_E001_KASEYA_NS_LOCATION to XXINT;
GRANT INSERT ON XXMAP.XXMAP_GL_E001_KASEYA_NS_PRODUCTLINE to XXINT;
GRANT INSERT ON XXMAP.XXMAP_GL_E001_TEMP_COA_COMB_DATA to XXINT;
GRANT INSERT ON XXMAP.XXMAP_GL_JOB_PARAMETERS_REF to XXINT;
GRANT INSERT ON XXMAP.XXMAP_GL_SOURCES_REF to XXINT;
GRANT INSERT ON XXMAP.XXMAP_NSOC_BU_MASTER_DATA to XXINT;
GRANT INSERT ON XXMAP.XXMAP_NSOC_COSTCENTER_MASTER_DATA to XXINT;
GRANT INSERT ON XXMAP.XXMAP_NSOC_CURRENCY_MASTER_DATA to XXINT;
GRANT INSERT ON XXMAP.XXMAP_NSOC_EMPLOYEE_MASTER_DATA to XXINT;
GRANT INSERT ON XXMAP.XXMAP_NSOC_ITEM_MASTER_DATA to XXINT;
GRANT INSERT ON XXMAP.XXMAP_NSOC_LEGAL_ENTITY_MASTER_DATA to XXINT;
GRANT INSERT ON XXMAP.XXMAP_NSOC_LOCATION_MASTER_DATA to XXINT;
GRANT INSERT ON XXMAP.XXMAP_NSOC_SUPPLIER_MASTER_DATA to XXINT;
GRANT SELECT ON XXMAP.XXMAP_GL_CONCUR_VENDOR_VALUES_REF to XXINT;
GRANT SELECT ON XXMAP.XXMAP_GL_E001_COA_NSERP_DATA to XXINT;
GRANT SELECT ON XXMAP.XXMAP_GL_E001_KASEYA_NS_ACCOUNT to XXINT;
GRANT SELECT ON XXMAP.XXMAP_GL_E001_KASEYA_NS_ACCTCC to XXINT;
GRANT SELECT ON XXMAP.XXMAP_GL_E001_KASEYA_NS_COMPANY to XXINT;
GRANT SELECT ON XXMAP.XXMAP_GL_E001_KASEYA_NS_COSTCENTER to XXINT;
GRANT SELECT ON XXMAP.XXMAP_GL_E001_KASEYA_NS_DIVISON to XXINT;
GRANT SELECT ON XXMAP.XXMAP_GL_E001_KASEYA_NS_FUTURE1 to XXINT;
GRANT SELECT ON XXMAP.XXMAP_GL_E001_KASEYA_NS_FUTURE2 to XXINT;
GRANT SELECT ON XXMAP.XXMAP_GL_E001_KASEYA_NS_FUTURE3 to XXINT;
GRANT SELECT ON XXMAP.XXMAP_GL_E001_KASEYA_NS_INTERCOMPANY to XXINT;
GRANT SELECT ON XXMAP.XXMAP_GL_E001_KASEYA_NS_LOCATION to XXINT;
GRANT SELECT ON XXMAP.XXMAP_GL_E001_KASEYA_NS_PRODUCTLINE to XXINT;
GRANT SELECT ON XXMAP.XXMAP_GL_E001_TEMP_COA_COMB_DATA to XXINT;
GRANT SELECT ON XXMAP.XXMAP_GL_JOB_PARAMETERS_REF to XXINT;
GRANT SELECT ON XXMAP.XXMAP_GL_SOURCES_REF to XXINT;
GRANT SELECT ON XXMAP.XXMAP_NSOC_BU_MASTER_DATA to XXINT;
GRANT SELECT ON XXMAP.XXMAP_NSOC_COSTCENTER_MASTER_DATA to XXINT;
GRANT SELECT ON XXMAP.XXMAP_NSOC_CURRENCY_MASTER_DATA to XXINT;
GRANT SELECT ON XXMAP.XXMAP_NSOC_EMPLOYEE_MASTER_DATA to XXINT;
GRANT SELECT ON XXMAP.XXMAP_NSOC_ITEM_MASTER_DATA to XXINT;
GRANT SELECT ON XXMAP.XXMAP_NSOC_LEGAL_ENTITY_MASTER_DATA to XXINT;
GRANT SELECT ON XXMAP.XXMAP_NSOC_LOCATION_MASTER_DATA to XXINT;
GRANT SELECT ON XXMAP.XXMAP_NSOC_SUPPLIER_MASTER_DATA to XXINT;
GRANT UPDATE ON XXMAP.XXMAP_GL_CONCUR_VENDOR_VALUES_REF to XXINT;
GRANT UPDATE ON XXMAP.XXMAP_GL_JOB_PARAMETERS_REF to XXINT;
GRANT UPDATE ON XXMAP.XXMAP_GL_SOURCES_REF to XXINT;
GRANT EXECUTE ON XXMAP.XXMAP_GL_E001_FIN_COASEGMENTS_PKG to XXINT;
GRANT SELECT ON XXMAP.XXMAP_GL_E001_EXCLUDE_ACCOUNTS to XXINT;
GRANT INSERT ON XXMAP.XXMAP_GL_E001_EXCLUDE_ACCOUNTS to XXINT;
GRANT DELETE ON XXMAP.XXMAP_GL_E001_EXCLUDE_ACCOUNTS to XXINT;
GRANT SELECT ON XXMAP.XXMAP_GL_E001_EXCLUDE_ACCOUNTS TO XXCNV;
GRANT SELECT ON XXMAP.XXMAP_GL_E001_EXCLUDE_ACCOUNTS TO XXCNV_RUN;
