--------------------------------------------------------
--  DDL for Table HZ_GEOGRAPHIES
--------------------------------------------------------

  CREATE TABLE "XXSUPCNV"."HZ_GEOGRAPHIES" 
   (	"ELEMENT1_NAME" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'ELEMENT1_NAME'), 
	"GEOGRAPHY_ELEMENT1" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'GEOGRAPHY_ELEMENT1'), 
	"GEOGRAPHY_ELEMENT1_CODE" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'GEOGRAPHY_ELEMENT1_CODE'), 
	"ELEMENT2_NAME" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'ELEMENT2_NAME'), 
	"GEOGRAPHY_ELEMENT2" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'GEOGRAPHY_ELEMENT2'), 
	"ELEMENT3_NAME" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'ELEMENT3_NAME'), 
	"GEOGRAPHY_ELEMENT3" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'GEOGRAPHY_ELEMENT3'), 
	"ELEMENT4_NAME" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'ELEMENT4_NAME'), 
	"GEOGRAPHY_ELEMENT4" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'GEOGRAPHY_ELEMENT4'), 
	"ELEMENT5_NAME" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'ELEMENT5_NAME'), 
	"GEOGRAPHY_ELEMENT5" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'GEOGRAPHY_ELEMENT5')
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
  /