--------------------------------------------------------
--  DDL for Table IBYTEMPEXTPAYEES_CLEANED
--------------------------------------------------------

  CREATE TABLE "XXSUPCNV"."IBYTEMPEXTPAYEES_CLEANED" 
   (	"IMPORT_BATCH_IDENTIFIER" VARCHAR2(80 BYTE) COLLATE "USING_NLS_COMP", 
	"PAYEE_IDENTIFIER" NUMBER(38,0), 
	"BUSINESS_UNIT_NAME" VARCHAR2(26 BYTE) COLLATE "USING_NLS_COMP", 
	"SUPPLIER_NUMBER" VARCHAR2(26 BYTE) COLLATE "USING_NLS_COMP", 
	"SUPPLIER_SITE" VARCHAR2(26 BYTE) COLLATE "USING_NLS_COMP", 
	"PAY_EACH_DOCUMENT_ALONE" VARCHAR2(26 BYTE) COLLATE "USING_NLS_COMP", 
	"PAYMENT_METHOD_CODE" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"DELIVERY_CHANNEL_CODE" VARCHAR2(26 BYTE) COLLATE "USING_NLS_COMP", 
	"SETTLEMENT_PRIORITY" VARCHAR2(26 BYTE) COLLATE "USING_NLS_COMP", 
	"REMIT_DELIVERY_METHOD" VARCHAR2(26 BYTE) COLLATE "USING_NLS_COMP", 
	"REMIT_ADVICE_EMAIL" VARCHAR2(400 BYTE) COLLATE "USING_NLS_COMP", 
	"REMIT_ADVICE_FAX" VARCHAR2(26 BYTE) COLLATE "USING_NLS_COMP", 
	"BANK_INSTRUCTIONS_1" VARCHAR2(26 BYTE) COLLATE "USING_NLS_COMP", 
	"BANK_INSTRUCTIONS_2" VARCHAR2(26 BYTE) COLLATE "USING_NLS_COMP", 
	"BANK_INSTRUCTION_DETAILS" VARCHAR2(26 BYTE) COLLATE "USING_NLS_COMP", 
	"PAYMENT_REASON_CODE" VARCHAR2(26 BYTE) COLLATE "USING_NLS_COMP", 
	"PAYMENT_REASON_COMMENTS" VARCHAR2(2600 BYTE) COLLATE "USING_NLS_COMP", 
	"PAYMENT_MESSAGE1" VARCHAR2(26 BYTE) COLLATE "USING_NLS_COMP", 
	"PAYMENT_MESSAGE2" VARCHAR2(26 BYTE) COLLATE "USING_NLS_COMP", 
	"PAYMENT_MESSAGE3" VARCHAR2(26 BYTE) COLLATE "USING_NLS_COMP", 
	"BANK_CHARGE_BEARER_CODE" VARCHAR2(26 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
  
  /