--------------------------------------------------------
--  DDL for Table IBYTEMPEXTBANTACCTS_CLEANED
--------------------------------------------------------

  CREATE TABLE "XXSUPCNV"."IBYTEMPEXTBANTACCTS_CLEANED" 
   (	"IMPORT_BATCH_IDENTIFIER" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"PAYEE_IDENTIFIER" NUMBER(38,0), 
	"PAYEE_BANK_ACCOUNT_IDENTIFIER" VARCHAR2(26 BYTE) COLLATE "USING_NLS_COMP", 
	"BANK_NAME" VARCHAR2(800 BYTE) COLLATE "USING_NLS_COMP", 
	"BRANCH_NAME" VARCHAR2(260 BYTE) COLLATE "USING_NLS_COMP", 
	"ACCOUNT_COUNTRY_CODE" VARCHAR2(26 BYTE) COLLATE "USING_NLS_COMP", 
	"ACCOUNT_NAME" VARCHAR2(1280 BYTE) COLLATE "USING_NLS_COMP", 
	"ACCOUNT_NUMBER" VARCHAR2(260 BYTE) COLLATE "USING_NLS_COMP", 
	"ACCOUNT_CURRENCY_CODE" VARCHAR2(26 BYTE) COLLATE "USING_NLS_COMP", 
	"ALLOW_INTERNATIONAL_PAYMENTS" VARCHAR2(26 BYTE) COLLATE "USING_NLS_COMP", 
	"ACCOUNT_START_DATE" VARCHAR2(26 BYTE) COLLATE "USING_NLS_COMP", 
	"ACCOUNT_END_DATE" VARCHAR2(26 BYTE) COLLATE "USING_NLS_COMP", 
	"IBAN" VARCHAR2(1280 BYTE) COLLATE "USING_NLS_COMP", 
	"CHECK_DIGITS" VARCHAR2(26 BYTE) COLLATE "USING_NLS_COMP", 
	"ACCOUNT_ALTERNATE_NAME" VARCHAR2(26 BYTE) COLLATE "USING_NLS_COMP", 
	"ACCOUNT_TYPE_CODE" VARCHAR2(26 BYTE) COLLATE "USING_NLS_COMP", 
	"ACCOUNT_SUFFIX" VARCHAR2(26 BYTE) COLLATE "USING_NLS_COMP", 
	"ACCOUNT_DESCRIPTION" VARCHAR2(26 BYTE) COLLATE "USING_NLS_COMP", 
	"AGENCY_LOCATION_CODE" VARCHAR2(26 BYTE) COLLATE "USING_NLS_COMP", 
	"EXCHANGE_RATE_AGREEMENT_NUMBER" VARCHAR2(26 BYTE) COLLATE "USING_NLS_COMP", 
	"EXCHANGE_RATE_AGREEMENT_TYPE" VARCHAR2(26 BYTE) COLLATE "USING_NLS_COMP", 
	"EXCHANGE_RATE" VARCHAR2(26 BYTE) COLLATE "USING_NLS_COMP", 
	"SECONDARY_ACCOUNT_REFERENCE" VARCHAR2(26 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE_CATEGORY" VARCHAR2(26 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE_1" VARCHAR2(26 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE_2" VARCHAR2(26 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE_3" VARCHAR2(26 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE_4" VARCHAR2(26 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE_5" VARCHAR2(26 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE_6" VARCHAR2(26 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE_7" VARCHAR2(26 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE_8" VARCHAR2(26 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE_9" VARCHAR2(26 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE_10" VARCHAR2(26 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE_11" VARCHAR2(26 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE_12" VARCHAR2(26 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE_13" VARCHAR2(26 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE_14" VARCHAR2(26 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE_15" VARCHAR2(26 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
  /