--------------------------------------------------------
--  DDL for Index XXINT_GL_I008_CONCUR_ACC_JOURNALS_STG_N3
--------------------------------------------------------

  CREATE INDEX "XXINT"."XXINT_GL_I008_CONCUR_ACC_JOURNALS_STG_N3" ON "XXINT"."XXINT_GL_I008_CONCUR_ACC_JOURNALS_STG" ("CURRENT_INSTANCE_ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

--------------------------------------------------------
--  DDL for Index XXINT_GL_I008_CONCUR_ACC_JOURNALS_STG_N4
--------------------------------------------------------

  CREATE INDEX "XXINT"."XXINT_GL_I008_CONCUR_ACC_JOURNALS_STG_N4" ON "XXINT"."XXINT_GL_I008_CONCUR_ACC_JOURNALS_STG" ("LOAD_REQUEST_ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;


--------------------------------------------------------
--  DDL for Index XXINT_GL_I018_CONCUR_JOURNALS_STG_N3
--------------------------------------------------------

  CREATE INDEX "XXINT"."XXINT_GL_I018_CONCUR_JOURNALS_STG_N3" ON "XXINT"."XXINT_GL_I018_CONCUR_JOURNALS_STG" ("CURRENT_INSTANCE_ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

--------------------------------------------------------
--  DDL for Index XXINT_GL_I018_CONCUR_JOURNALS_STG_N4
--------------------------------------------------------

  CREATE INDEX "XXINT"."XXINT_GL_I018_CONCUR_JOURNALS_STG_N4" ON "XXINT"."XXINT_GL_I018_CONCUR_JOURNALS_STG" ("LOAD_REQUEST_ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
