--------------------------------------------------------
--  DDL for Table LEXIS_NEXIS_DATA
--------------------------------------------------------

  CREATE TABLE "XXSUPCNV"."LEXIS_NEXIS_DATA" 
   (	"COUNTRY" VARCHAR2(26 BYTE) COLLATE "USING_NLS_COMP", 
	"KEYVALUE" VARCHAR2(38 BYTE) COLLATE "USING_NLS_COMP", 
	"NAME" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"COUNTRYCSP" VARCHAR2(26 BYTE) COLLATE "USING_NLS_COMP", 
	"CITY" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"BIC" VARCHAR2(26 BYTE) COLLATE "USING_NLS_COMP", 
	"NATID" VARCHAR2(26 BYTE) COLLATE "USING_NLS_COMP", 
	"NATIDTYPE" VARCHAR2(26 BYTE) COLLATE "USING_NLS_COMP", 
	"BRANCH" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"ADDRESS" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"POSTCODE" VARCHAR2(26 BYTE) COLLATE "USING_NLS_COMP", 
	"PHONE" VARCHAR2(26 BYTE) COLLATE "USING_NLS_COMP", 
	"FAX" VARCHAR2(26 BYTE) COLLATE "USING_NLS_COMP", 
	"EMAIL" VARCHAR2(26 BYTE) COLLATE "USING_NLS_COMP", 
	"LOC_ID" NUMBER(38,0), 
	"HO_LOC_ID" NUMBER(38,0), 
	"SANCTIONS_EU" VARCHAR2(26 BYTE) COLLATE "USING_NLS_COMP", 
	"SANCTIONS_HMT" VARCHAR2(26 BYTE) COLLATE "USING_NLS_COMP", 
	"SANCTIONS_OFAC" VARCHAR2(26 BYTE) COLLATE "USING_NLS_COMP", 
	"SANCTIONS_UN" VARCHAR2(26 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
  /