--------------------------------------------------------
--  DDL for Table MV_HZ_GEOGRAPHIES_MAPPED
--------------------------------------------------------

  CREATE TABLE "XXSUPCNV"."MV_HZ_GEOGRAPHIES_MAPPED" 
   (	"COUNTRY_CODE" CHAR(2 BYTE) COLLATE "USING_NLS_COMP", 
	"STATE" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"PROVINCE" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"COUNTY" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"CITY" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"POSTAL_CODE" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
  /