--------------------------------------------------------
--  DDL for Table POZ_SITE_ASSIGNMENTS_NS
--------------------------------------------------------

  CREATE TABLE "XXSUPCNV"."POZ_SITE_ASSIGNMENTS_NS" 
   (	"ID" VARCHAR2(64 BYTE) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'ID'), 
	"BATCH_ID" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'Batch ID'), 
	"IMPORT_ACTION" VARCHAR2(64 BYTE) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'Import Action'), 
	"SUPPLIER_NAME" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'Supplier Name'), 
	"SUPPLIER_SITE" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'Supplier Site'), 
	"PROCUREMENT_BU" VARCHAR2(64 BYTE) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'Procurement BU'), 
	"CLIENT_BU" VARCHAR2(64 BYTE) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'Client BU'), 
	"BILL_TO_BU" VARCHAR2(64 BYTE) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'Bill-to BU'), 
	"SHIP_TO_LOCATION" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'Ship-to Location'), 
	"BILL_TO_LOCATION" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'Bill-to Location'), 
	"USE_WITHHOLDING_TAX" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'Use Withholding Tax'), 
	"WITHHOLDING_TAX_GROUP" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'Withholding Tax Group'), 
	"LIABILITY_DISTRIBUTION" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'Liability Distribution'), 
	"PREPAYMENT_DISTRIBUTION" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'Prepayment Distribution'), 
	"BILLS_PAYABLE_DISTRIBUTION" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'Bills Payable Distribution'), 
	"DISTRIBUTION_SET" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'Distribution Set'), 
	"ERROR_FLAG" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"ERROR_MESSAGE" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
  /