--------------------------------------------------------
--  DDL for Table POZ_SUPPLIER_ADDRESSES_NS
--------------------------------------------------------

  CREATE TABLE "XXSUPCNV"."POZ_SUPPLIER_ADDRESSES_NS" 
   (	"ID" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'ID'), 
	"BATCH_ID" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'Batch ID'), 
	"IMPORT_ACTION" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'Import Action'), 
	"SUPPLIER_NAME" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'Supplier Name'), 
	"ADDRESS_NAME" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'Address Name'), 
	"ADDRESS_NAME_NEW" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'Address Name New'), 
	"COUNTRY_CODE" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'Country Code'), 
	"ADDRESS_1" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'Address 1'), 
	"ADDRESS_2" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'Address 2'), 
	"ADDRESS_3" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'Address 3'), 
	"CITY" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'City'), 
	"STATE" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'State'), 
	"PROVINCE" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'Province'), 
	"COUNTY" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'County'), 
	"POSTAL_CODE" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'Postal code'), 
	"POSTAL_PLUS_4_CODE" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'Postal Plus 4 code'), 
	"ADDRESSEE" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'Addressee'), 
	"GLOBAL_LOCATION_NUMBER" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'Global Location Number'), 
	"LANGUAGE" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'Language'), 
	"INACTIVE_DATE" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'Inactive Date'), 
	"PHONE_COUNTRY_CODE" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'Phone Country Code'), 
	"PHONE_AREA_CODE" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'Phone Area Code'), 
	"PHONE" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'Phone'), 
	"PHONE_EXTENSION" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'Phone Extension'), 
	"FAX_COUNTRY_CODE" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'Fax Country Code'), 
	"FAX_AREA_CODE" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'Fax Area Code'), 
	"FAX" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'Fax'), 
	"RFQ_OR_BIDDING" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'RFQ or Bidding'), 
	"ORDERING" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'Ordering'), 
	"PAY" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'Pay'), 
	"EMAIL" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'Email'), 
	"DELIVERY_CHANNEL" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'Delivery Channel'), 
	"REMITTANCE_EMAIL" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'Remittance Email'), 
	"ERROR_FLAG" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"ERROR_MESSAGE" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
  /