--------------------------------------------------------
--  DDL for Table POZ_SUPPLIER_SITES_NS
--------------------------------------------------------

  CREATE TABLE "XXSUPCNV"."POZ_SUPPLIER_SITES_NS" 
   (	"ID" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'ID'), 
	"BATCH_ID" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'BATCH ID'), 
	"IMPORT_ACTION" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'Import Action'), 
	"SUPPLIER_NAME" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'Supplier Name'), 
	"PROCUREMENT_BU" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'Procurement BU'), 
	"ADDRESS_NAME" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'Address Name'), 
	"SUPPLIER_SITE" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'Supplier Site'), 
	"SUPPLIER_SITE_NEW" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'Supplier Site New'), 
	"INACTIVE_DATE" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'Inactive Date'), 
	"SOURCING_ONLY" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'Sourcing only'), 
	"PURCHASING" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'Purchasing'), 
	"PROCUREMENT_CARD" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'Procurement card'), 
	"PAY" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'Pay'), 
	"PRIMARY_PAY" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'Primary Pay'), 
	"INCOME_TAX_REPORTING_SITE" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'Income tax reporting site'), 
	"ALTERNATE_SITE_NAME" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'Alternate Site Name'), 
	"CUSTOMER_NUMBER" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'Customer Number'), 
	"B2B_COMMUNICATION_METHOD" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'B2B Communication Method'), 
	"COMMUNICATION_METHOD" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'Communication Method'), 
	"EMAIL" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'Email'), 
	"FAX_COUNTRY_CODE" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'Fax Country Code'), 
	"FAX_AREA_CODE" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'Fax Area Code'), 
	"FAX" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'Fax'), 
	"HOLD_ALL_NEW_PURCHASING_DOCUMENTS" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'Hold all new purchasing documents'), 
	"PURCHASING_HOLD_REASON" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'Purchasing Hold Reason'), 
	"CARRIER" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'Carrier'), 
	"MODE_OF_TRANSPORT" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'Mode of Transport'), 
	"SERVICE_LEVEL" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'Service Level'), 
	"FREIGHT_TERMS" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'Freight Terms'), 
	"PAY_ON_RECEIPT" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'Pay on receipt'), 
	"FOB" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'FOB'), 
	"COUNTRY_OF_ORIGIN" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'Country of Origin'), 
	"BUYER_MANAGED_TRANSPORTATION" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'Buyer Managed Transportation'), 
	"PAY_ON_USE" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'Pay on use'), 
	"AGING_ONSET_POINT" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'Aging Onset Point'), 
	"AGING_PERIOD_DAYS" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'Aging Period Days'), 
	"CONSUMPTION_ADVICE_FREQUENCY" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'Consumption Advice Frequency'), 
	"CONSUMPTION_ADVICE_SUMMARY" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'Consumption Advice Summary'), 
	"ALTERNATE_PAY_SITE" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'Alternate Pay Site'), 
	"INVOICE_SUMMARY_LEVEL" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'Invoice Summary Level'), 
	"GAPLESS_INVOICE_NUMBERING" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'Gapless invoice numbering'), 
	"SELLING_COMPANY_IDENTIFIER" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'Selling Company Identifier'), 
	"CREATE_DEBIT_MEMO_FROM_RETURN" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'Create debit memo from return'), 
	"SHIP_TO_EXCEPTION_ACTION" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'Ship-to Exception Action'), 
	"RECEIPT_ROUTING" NUMBER ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'Receipt Routing'), 
	"OVER_RECEIPT_TOLERANCE" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'Over-receipt Tolerance'), 
	"OVER_RECEIPT_ACTION" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'Over-receipt Action'), 
	"PAYMENT_CURRENCY" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'Payment Currency'), 
	"PAYMENT_PRIORITY" NUMBER ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'Payment Priority'), 
	"PAYMENT_TERMS" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'Payment Terms'), 
	"PAYMENT_METHOD" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'Payment Method'), 
	"REMITTANCE_EMAIL" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'Remittance Email'), 
	"ERROR_FLAG" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"ERROR_MESSAGE" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE1" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
  /