--------------------------------------------------------
--  DDL for Table STG_POZ_SITE_ASSIGNMENTS
--------------------------------------------------------

  CREATE TABLE "XXSUPCNV"."STG_POZ_SITE_ASSIGNMENTS" 
   (	"ID" VARCHAR2(64 BYTE) COLLATE "USING_NLS_COMP", 
	"BATCH_ID" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP", 
	"IMPORT_ACTION" VARCHAR2(64 BYTE) COLLATE "USING_NLS_COMP", 
	"SUPPLIER_NAME" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"SUPPLIER_SITE" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"PROCUREMENT_BU" VARCHAR2(64 BYTE) COLLATE "USING_NLS_COMP", 
	"CLIENT_BU" VARCHAR2(64 BYTE) COLLATE "USING_NLS_COMP", 
	"BILL_TO_BU" VARCHAR2(64 BYTE) COLLATE "USING_NLS_COMP", 
	"SHIP_TO_LOCATION" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP", 
	"BILL_TO_LOCATION" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP", 
	"USE_WITHHOLDING_TAX" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP", 
	"WITHHOLDING_TAX_GROUP" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP", 
	"LIABILITY_DISTRIBUTION" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP", 
	"PREPAYMENT_DISTRIBUTION" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP", 
	"BILLS_PAYABLE_DISTRIBUTION" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP", 
	"DISTRIBUTION_SET" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP", 
	"ERROR_FLAG" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"ERROR_MESSAGE" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
  /