--------------------------------------------------------
--  DDL for Table STG_POZ_SUP_BUS_CLASS
--------------------------------------------------------

  CREATE TABLE "XXSUPCNV"."STG_POZ_SUP_BUS_CLASS" 
   (	"ID" VARCHAR2(64 BYTE) COLLATE "USING_NLS_COMP", 
	"BATCH_ID" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP", 
	"IMPORT_ACTION" VARCHAR2(64 BYTE) COLLATE "USING_NLS_COMP", 
	"SUPPLIER_NAME" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"CLASSIFICATION" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP", 
	"CLASSIFICATION_NEW" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP", 
	"SUBCLASSIFICATION" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP", 
	"CERTIFYING_AGENCY" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP", 
	"CERTIFYING_AGENCY_NEW" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP", 
	"CREATE_CERTIFYING_AGENCY" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP", 
	"CERTIFICATE_NUMBER" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP", 
	"CERTIFICATE_NUMBER_NEW" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP", 
	"START_DATE" DATE, 
	"EXPIRATION_DATE" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP", 
	"NOTES" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"PROVIDED_BY_FIRST_NAME" VARCHAR2(64 BYTE) COLLATE "USING_NLS_COMP", 
	"PROVIDED_BY_LAST_NAME" VARCHAR2(64 BYTE) COLLATE "USING_NLS_COMP", 
	"PROVIDED_BY_E_MAIL" VARCHAR2(64 BYTE) COLLATE "USING_NLS_COMP", 
	"ERROR_FLAG" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"ERROR_MESSAGE" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
  /