--------------------------------------------------------
--  DDL for Table STG_POZ_SUPPLIERS
--------------------------------------------------------

  CREATE TABLE "XXSUPCNV"."STG_POZ_SUPPLIERS" 
   (	"BATCH_ID" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP", 
	"IMPORT_ACTION" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"SUPPLIER_NAME" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"SUPPLIER_NAME_NEW" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP", 
	"SUPPLIER_NUMBER" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"ALTERNATE_NAME" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"TAX_ORGANIZATION_TYPE" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"SUPPLIER_TYPE" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"INACTIVE_DATE" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP", 
	"BUSINESS_RELATIONSHIP" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP", 
	"PARENT_SUPPLIER" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP", 
	"ALIAS" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"DUNS_NUMBER" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP", 
	"CORPORATE_WEB_SITE" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"TAXPAYER_COUNTRY" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"TAXPAYER_ID" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"FEDERAL_REPORTABLE" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"FEDERAL_INCOME_TAX_TYPE" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP", 
	"STATE_REPORTABLE" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP", 
	"TAX_REPORTING_NAME" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP", 
	"NAME_CONTROL" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP", 
	"TAX_VERIFICATION_DATE" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP", 
	"USE_WITHHOLDING_TAX" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP", 
	"TAX_REGISTRATION_NUMBER" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"PAYMENT_METHOD" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"REMITTANCE_E_MAIL" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"CRITICAL_PAY" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"ERROR_FLAG" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"ERROR_MESSAGE" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
  /