--------------------------------------------------------
--  DDL for Table STG_POZ_SUP_CONTACTS
--------------------------------------------------------

  CREATE TABLE "XXSUPCNV"."STG_POZ_SUP_CONTACTS" 
   (	"ID" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"BATCH_ID" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP", 
	"IMPORT_ACTION" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"SUPPLIER_NAME" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"PREFIX" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP", 
	"FIRST_NAME" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"FIRST_NAME_NEW" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP", 
	"MIDDLE_NAME" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP", 
	"LAST_NAME" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"LAST_NAME_NEW" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP", 
	"JOB_TITLE" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP", 
	"ADMINISTRATIVE_CONTACT" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"EMAIL" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"E_MAIL_NEW" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP", 
	"PHONE_COUNTRY_CODE" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP", 
	"PHONE_AREA_CODE" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP", 
	"PHONE" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"PHONE_EXTENSION" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP", 
	"FAX_COUNTRY_CODE" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP", 
	"FAX_AREA_CODE" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP", 
	"FAX" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP", 
	"MOBILE_COUNTRY_CODE" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP", 
	"MOBILE_AREA_CODE" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP", 
	"MOBILE" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP", 
	"INACTIVE_DATE" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP", 
	"USER_ACCOUNT_ACTION" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"ERROR_FLAG" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"ERROR_MESSAGE" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
  /