--------------------------------------------------------
--  DDL for Table STG_POZ_SUPPLIER_ADDRESSES
--------------------------------------------------------

  CREATE TABLE "XXSUPCNV"."STG_POZ_SUPPLIER_ADDRESSES" 
   (	"ID" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"BATCH_ID" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP", 
	"IMPORT_ACTION" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"SUPPLIER_NAME" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"ADDRESS_NAME" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"ADDRESS_NAME_NEW" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP", 
	"COUNTRY_CODE" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"ADDRESS_1" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"ADDRESS_2" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"ADDRESS_3" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP", 
	"CITY" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"STATE" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"PROVINCE" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP", 
	"COUNTY" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP", 
	"POSTAL_CODE" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"POSTAL_PLUS_4_CODE" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP", 
	"ADDRESSEE" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP", 
	"GLOBAL_LOCATION_NUMBER" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP", 
	"LANGUAGE" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP", 
	"INACTIVE_DATE" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP", 
	"PHONE_COUNTRY_CODE" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP", 
	"PHONE_AREA_CODE" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP", 
	"PHONE" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"PHONE_EXTENSION" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP", 
	"FAX_COUNTRY_CODE" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP", 
	"FAX_AREA_CODE" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP", 
	"FAX" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"RFQ_OR_BIDDING" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP", 
	"ORDERING" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP", 
	"PAY" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP", 
	"EMAIL" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"DELIVERY_CHANNEL" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"REMITTANCE_EMAIL" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"ERROR_FLAG" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"ERROR_MESSAGE" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
  /