--------------------------------------------------------
--  DDL for Table STG_POZ_SUPP_CONTACT_ADDRESSES
--------------------------------------------------------

  CREATE TABLE "XXSUPCNV"."STG_POZ_SUPP_CONTACT_ADDRESSES" 
   (	"ID" VARCHAR2(64 BYTE) COLLATE "USING_NLS_COMP", 
	"BATCH_ID" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP", 
	"IMPORT_ACTION" VARCHAR2(64 BYTE) COLLATE "USING_NLS_COMP", 
	"SUPPLIER_NAME" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"ADDRESS_NAME" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"FIRST_NAME" VARCHAR2(64 BYTE) COLLATE "USING_NLS_COMP", 
	"LAST_NAME" VARCHAR2(64 BYTE) COLLATE "USING_NLS_COMP", 
	"EMAIL" VARCHAR2(64 BYTE) COLLATE "USING_NLS_COMP", 
	"ERROR_FLAG" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"ERROR_MESSAGE" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
  /