--------------------------------------------------------
--  DDL for Table STG_POZ_SUPPLIER_SITES
--------------------------------------------------------

  CREATE TABLE "XXSUPCNV"."STG_POZ_SUPPLIER_SITES" 
   (	"ID" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"BATCH_ID" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP", 
	"IMPORT_ACTION" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"SUPPLIER_NAME" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"PROCUREMENT_BU" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"ADDRESS_NAME" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"SUPPLIER_SITE" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"SUPPLIER_SITE_NEW" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP", 
	"INACTIVE_DATE" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP", 
	"SOURCING_ONLY" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP", 
	"PURCHASING" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP", 
	"PROCUREMENT_CARD" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP", 
	"PAY" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP", 
	"PRIMARY_PAY" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP", 
	"INCOME_TAX_REPORTING_SITE" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP", 
	"ALTERNATE_SITE_NAME" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP", 
	"CUSTOMER_NUMBER" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP", 
	"B2B_COMMUNICATION_METHOD" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP", 
	"COMMUNICATION_METHOD" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP", 
	"EMAIL" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"FAX_COUNTRY_CODE" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP", 
	"FAX_AREA_CODE" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP", 
	"FAX" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"HOLD_ALL_NEW_PURCHASING_DOCUMENTS" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP", 
	"PURCHASING_HOLD_REASON" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP", 
	"CARRIER" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP", 
	"MODE_OF_TRANSPORT" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP", 
	"SERVICE_LEVEL" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP", 
	"FREIGHT_TERMS" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP", 
	"PAY_ON_RECEIPT" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP", 
	"FOB" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP", 
	"COUNTRY_OF_ORIGIN" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP", 
	"BUYER_MANAGED_TRANSPORTATION" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP", 
	"PAY_ON_USE" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP", 
	"AGING_ONSET_POINT" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP", 
	"AGING_PERIOD_DAYS" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP", 
	"CONSUMPTION_ADVICE_FREQUENCY" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP", 
	"CONSUMPTION_ADVICE_SUMMARY" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP", 
	"ALTERNATE_PAY_SITE" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP", 
	"INVOICE_SUMMARY_LEVEL" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP", 
	"GAPLESS_INVOICE_NUMBERING" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP", 
	"SELLING_COMPANY_IDENTIFIER" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP", 
	"CREATE_DEBIT_MEMO_FROM_RETURN" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP", 
	"SHIP_TO_EXCEPTION_ACTION" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"RECEIPT_ROUTING" NUMBER, 
	"OVER_RECEIPT_TOLERANCE" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP", 
	"OVER_RECEIPT_ACTION" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"PAYMENT_CURRENCY" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"PAYMENT_PRIORITY" NUMBER, 
	"PAYMENT_TERMS" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"PAYMENT_METHOD" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"REMITTANCE_EMAIL" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"ERROR_FLAG" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"ERROR_MESSAGE" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE1" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
  /