--------------------------------------------------------
--  DDL for Table SUPPLIER_CONVERSION_CLEANED_DATA
--------------------------------------------------------

  CREATE TABLE "XXSUPCNV"."SUPPLIER_CONVERSION_CLEANED_DATA" 
   (	"MAPPING_BUCKETS" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'Mapping Buckets'), 
	"MERGE_VENDOR" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'Merge Vendor'), 
	"INTERNAL_ID" NUMBER ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'Internal ID'), 
	"ID" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'ID'), 
	"NAME" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'Name'), 
	"TAX_ID_AND_NUMBER_VALIDATOR" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'Tax ID and Number Validator'), 
	"TAX_ID" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'Tax ID'), 
	"TAX_NUMBER" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'Tax Number'), 
	"TYPE_OF__ENTITY_FROM_W9" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'Type of  Entity from W9'), 
	"C1099_MISC_CATEGORY" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" '1099 MISC Category'), 
	"C1099_ELIGIBLE" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" '1099 Eligible'), 
	"PHONE" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'Phone'), 
	"PHONE_CHECK" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'Phone Check'), 
	"PHONE_COUNTRY_CODE" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'Phone Country Code'), 
	"PHONE_AREA_CODE" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'Phone Area Code'), 
	"PHONE1" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'Phone'), 
	"PHONE_EXTENSION" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'Phone Extension'), 
	"EMAIL" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'Email'), 
	"REMITTANCE_EMAIL" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'Remittance Email'), 
	"COUNTRY_CODE" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'Country Code'), 
	"BANK_COUNTRY_CODE" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'Bank Country Code'), 
	"COUNTRY" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'Country'), 
	"ADDRESS" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'Address'), 
	"BANK_NAME" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'Bank Name'), 
	"ACCOUNT_NUMBER" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'Account Number'), 
	"ACCOUNT_NAME" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'Account Name'), 
	"BIC" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'BIC'), 
	"IBAN" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'IBAN'), 
	"BANK_NUMBER" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'Bank Number'), 
	"BANK_CITY" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'Bank City'), 
	"ADDRESS1" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"ADDRESS2" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"ADDRESS3" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"CITY" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"STATE_PROVINCE" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"ZIP_CODE" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"NSEP_PAYMENT_METHOD" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"NSEP_PAYMENT_TYPE" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"CURRENCY" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"BANK_PAYMENT_DEFINITION" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"ACH_LOCAL_INSTRUMENT" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"PURPOSE_CODES" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"COUNTY" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"ZIP_PLUS_4" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
  /