
  CREATE TABLE "XXAUD"."XXAUD_XX_I024_OCI_EVENT_AUDIT_LOGS_ARC" 
   (	"ID" NUMBER, 
	"EVENT_TYPE" VARCHAR2(1000 BYTE) COLLATE "USING_NLS_COMP", 
	"CLOUD_EVENTS_VERSION" VARCHAR2(1000 BYTE) COLLATE "USING_NLS_COMP", 
	"EVENT_TYPE_VERSION" VARCHAR2(1000 BYTE) COLLATE "USING_NLS_COMP", 
	"SOURCE" VARCHAR2(1000 BYTE) COLLATE "USING_NLS_COMP", 
	"EVENT_ID" VARCHAR2(1000 BYTE) COLLATE "USING_NLS_COMP", 
	"EVENT_TIME" DATE, 
	"COMPARTMENT_NAME" VARCHAR2(1000 BYTE) COLLATE "USING_NLS_COMP", 
	"RESOURCE_NAME" VARCHAR2(1000 BYTE) COLLATE "USING_NLS_COMP", 
	"RESOURCE_ID" VARCHAR2(1000 BYTE) COLLATE "USING_NLS_COMP", 
	"IDENTITY_AUDIT" JSON(ARRAY), 
	"REQUEST" JSON(ARRAY), 
	"RESPONSE" JSON(ARRAY), 
	"STATE_CHANGE" JSON(ARRAY), 
	"ADDITIONAL_DETAILS" JSON(ARRAY), 
	"CREATION_DATE" DATE DEFAULT SYSDATE, 
	"LAST_UPDATE_DATE" DATE DEFAULT SYSDATE, 
	"CREATED_BY" VARCHAR2(1000 BYTE) COLLATE "USING_NLS_COMP", 
	"LAST_UPDATED_BY" VARCHAR2(1000 BYTE) COLLATE "USING_NLS_COMP", 
	 CONSTRAINT "XXAUD_XX_I024_OCI_EVENT_AUDIT_LOGS_ARC_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 
  TABLESPACE "DATA"  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "DATA" 
 JSON ("IDENTITY_AUDIT") STORE AS (
  TABLESPACE "DATA"  CHUNK 8192 RETENTION MIN 1800) 
 JSON ("REQUEST") STORE AS (
  TABLESPACE "DATA"  CHUNK 8192 RETENTION MIN 1800) 
 JSON ("RESPONSE") STORE AS (
  TABLESPACE "DATA"  CHUNK 8192 RETENTION MIN 1800) 
 JSON ("STATE_CHANGE") STORE AS (
  TABLESPACE "DATA"  CHUNK 8192 RETENTION MIN 1800) 
 JSON ("ADDITIONAL_DETAILS") STORE AS (
  TABLESPACE "DATA"  CHUNK 8192 RETENTION MIN 1800) ;


  GRANT DELETE ON "XXAUD"."XXAUD_XX_I024_OCI_EVENT_AUDIT_LOGS_ARC" TO "XXINT";
  GRANT INSERT ON "XXAUD"."XXAUD_XX_I024_OCI_EVENT_AUDIT_LOGS_ARC" TO "XXINT";
  GRANT SELECT ON "XXAUD"."XXAUD_XX_I024_OCI_EVENT_AUDIT_LOGS_ARC" TO "XXINT";
  GRANT UPDATE ON "XXAUD"."XXAUD_XX_I024_OCI_EVENT_AUDIT_LOGS_ARC" TO "XXINT";
