CREATE TABLE xxcnv.xxcnv_gl_le_bu_mapping
(
NS_LEGAL_ENTITY_ID              NUMBER        
,NS_LEGAL_ENTITY_NAME            VARCHAR2(100) 
,OC_LEGAL_ENTITY_NAME            VARCHAR2(100) 
,OC_BUSINESS_UNIT_NAME           VARCHAR2(100) 
,OC_PRIMARY_LEDGER               VARCHAR2(100) 
,FA_SUB_LEDGER                   VARCHAR2(100) 
,OC_PRIMARY_LEDGER_CURRENY       VARCHAR2(100) 
,OC_LEGAL_ENTITY_ID              NUMBER        
,OC_BILL_TO_LOCATION             VARCHAR2(200) 
,OC_BILL_TO_ORG_CODE             VARCHAR2(200) 
,OC_BILL_TO_LOCATION_CODE        VARCHAR2(200) 
,OC_SHIP_TO_ORG_CODE             VARCHAR2(200) 
,PROCUREMENT_APPLICABLE          VARCHAR2(200) 
);