create table XXCNV.XXCNV_GL_LEDGER_MAPPING(
SUBSIDIARY_INTERNAL_ID           VARCHAR2(100) ,
CONSOLIDATED_EXCHANGE_RATE       VARCHAR2(100) ,
PRIMARY_LEDGER_NAME              VARCHAR2(100) ,
MID_PARENT_LEDGER_NAME           VARCHAR2(100) ,
REPORTING_LEDGER_NAME            VARCHAR2(100) ,
SUBSIDIARY_NAME                  VARCHAR2(50)  ,
LEDGER_TYPE                      VARCHAR2(50)
)