
  CREATE TABLE xxcnv.xxcnv_ap_c003_poz_sup_bus_class_stg 
   (	BATCH_ID VARCHAR2(200)  
	,IMPORT_ACTION VARCHAR2(10)  
	,VENDOR_NAME VARCHAR2(360)  
	,CLASSIFICATION_LOOKUP_CODE VARCHAR2(30)  
	,CLASSIFICATION_LOOKUP_CODE_NEW VARCHAR2(30)  
	,SUB_CLASSIFICATION VARCHAR2(240)  
	,CERTIFYING_AGENCY_NAME VARCHAR2(255)  
	,CERTIFYING_AGENCY_NAME_NEW VARCHAR2(255)  
	,CREATE_CERTIFYING_AGENCY_FLAG VARCHAR2(1)  
	,CERTIFICATE_NUMBER VARCHAR2(80)  
	,CERTIFICATE_NUMBER_NAME VARCHAR2(80)  
	,START_DATE DATE 
	,EXPIRATION_DATE DATE 
	,NOTES VARCHAR2(1000)  
	,PROVIDED_BY_CONTACT_FIRST_NAME VARCHAR2(150)  
	,PROVIDED_BY_CONTACT_LAST_NAME VARCHAR2(150)  
	,PROVIDED_BY_CONTACT_EMAIL VARCHAR2(320)  
	,CONFIRMED_ON DATE 
	,FILE_NAME VARCHAR2(4000)  
	,ERROR_MESSAGE VARCHAR2(4000)  
	,IMPORT_STATUS VARCHAR2(4000)  
	,FILE_REFERENCE_IDENTIFIER VARCHAR2(4000)  
	,EXECUTION_ID VARCHAR2(4000)  
	,SOURCE_SYSTEM VARCHAR2(4000) 
   );