CREATE TABLE XXCNV.XXCNV_AP_C039_INVOICEATTACHMENTS_MAPPING (
RECORD_ID                 VARCHAR2(20)   ,
INVOICEID                 NUMBER(30)     ,
INVOICENUMBER             VARCHAR2(50)   ,
ATTACHMENT_FILEPATH       VARCHAR2(500)  ,
ATTACHMENT_FILENAME       VARCHAR2(100)  ,
ATTACHMENTFLAG            VARCHAR2(10)   ,
ERRORMESSAGE              VARCHAR2(1000) ,
IMPORT_STATUS             VARCHAR2(30))