DROP TABLE xxcnv.xxcnv_gl_c002_gl_reconciled_interface_stg;
CREATE TABLE xxcnv.xxcnv_gl_c002_gl_reconciled_interface_stg
(
LEDGER                         VARCHAR2(500) 
,USER_JE_SOURCE_NAME            VARCHAR2(500) 
,USER_JE_CATEGORY_NAME          VARCHAR2(500) 
,ACTUAL_FLAG                    VARCHAR2(500) 
,CREATION_DATE                  VARCHAR2(500) 
,EFFECTIVE_DATE                 VARCHAR2(500) 
,BATCH_NAME                     VARCHAR2(500) 
,BATCH_DESCRIPTION              VARCHAR2(500) 
,JOURNAL_NAME                   VARCHAR2(500) 
,HEADER_DESCRIPTION             VARCHAR2(500) 
,SEGMENT1                       VARCHAR2(500) 
,SEGMENT2                       VARCHAR2(500) 
,SEGMENT3                       VARCHAR2(500) 
,SEGMENT4                       VARCHAR2(500) 
,SEGMENT5                       VARCHAR2(500) 
,SEGMENT6                       VARCHAR2(500) 
,SEGMENT7                       VARCHAR2(500) 
,SEGMENT8                       VARCHAR2(500) 
,SEGMENT9                       VARCHAR2(500) 
,SEGMENT10                      VARCHAR2(500) 
,CURRENCY_CODE                  VARCHAR2(500) 
,ENTERED_DR                     VARCHAR2(500) 
,ENTERED_CR                     VARCHAR2(500) 
,ACCOUNTED_DR                   VARCHAR2(500) 
,ACCOUNTED_CR                   VARCHAR2(500) 
,STATUS                         VARCHAR2(500) 
,GROUP_ID                       VARCHAR2(500) 
,ATTRIBUTE1                     VARCHAR2(500) 
,ATTRIBUTE2                     VARCHAR2(500) 
,ATTRIBUTE3                     VARCHAR2(500) 
,ATTRIBUTE4                     VARCHAR2(500) 
,ATTRIBUTE5                     VARCHAR2(500) 
,ATTRIBUTE6                     VARCHAR2(500) 
,ATTRIBUTE7                     VARCHAR2(500) 
,ATTRIBUTE8                     VARCHAR2(500) 
,ATTRIBUTE9                     VARCHAR2(500) 
,ATTRIBUTE10                    VARCHAR2(500) 
,CURRENCY_CONVERSION_RATE       VARCHAR2(500) 
,DESCRIPTION                    VARCHAR2(500) 
,PERIOD_NAME                    VARCHAR2(500) 
,KEY                            VARCHAR2(500) 
);


  GRANT SELECT ON "XXCNV"."xxcnv_gl_c002_gl_reconciled_interface_stg" TO "XXCNV_RUN";
  GRANT SELECT ON "XXCNV"."xxcnv_gl_c002_gl_reconciled_interface_stg" TO "XXRO";