CREATE TABLE xxcnv.xxcnv_ap_c006_poz_sup_site_assign_stg
(
BATCH_ID                              VARCHAR2(200)  
,IMPORT_ACTION                         VARCHAR2(10)   
,VENDOR_NAME                           VARCHAR2(360)  
,VENDOR_SITE_CODE                      VARCHAR2(240)  
,PROCUREMENT_BUSINESS_UNIT_NAME        VARCHAR2(240)  
,BUSINESS_UNIT_NAME                    VARCHAR2(240)  
,BILL_TO_BU_NAME                       VARCHAR2(240)  
,SHIP_TO_LOCATION_CODE                 VARCHAR2(60)   
,BILL_TO_LOCATION_CODE                 VARCHAR2(60)   
,ALLOW_AWT_LAG                         VARCHAR2(1)    
,AWT_GROUP_NAME                        VARCHAR2(30)   
,ACCTS_PAY_CONCATENATED_SEGMENTS       VARCHAR2(800)  
,PREPAY_CONCAT_SEGMENTS                VARCHAR2(800)  
,FUTURE_DATED_CONCAT_SEGMENTS          VARCHAR2(800)  
,DISTRIBUTION_SET_NAME                 VARCHAR2(50)   
,INACTIVE_DATE                         DATE           
,FILE_NAME                             VARCHAR2(4000) 
,ERROR_MESSAGE                         VARCHAR2(4000) 
,IMPORT_STATUS                         VARCHAR2(4000) 
,FILE_REFERENCE_IDENTIFIER             VARCHAR2(4000) 
,EXECUTION_ID                          VARCHAR2(4000) 
,SOURCE_SYSTEM                         VARCHAR2(4000) 
);
