CREATE TABLE xxcnv.xxcnv_pdh_c027_egp_system_items_stg
(
 TRANSACTION_TYPE                       VARCHAR2(100)  
,BATCH_ID                               NUMBER(18)     
,BATCH_NUMBER                           VARCHAR2(40)   
,ITEM_NUMBER                            VARCHAR2(300)  
,OUTSIDE_PROCESS_SERVICE_FLAG           VARCHAR2(10)   
,ORGANIZATION_CODE                      VARCHAR2(50)   
,DESCRIPTION                            VARCHAR2(240)  
,TEMPLATE_NAME                          VARCHAR2(960)  
,SOURCE_SYSTEM_CODE                     VARCHAR2(30)   
,SOURCE_SYSTEM_REFERENCE                VARCHAR2(255)  
,SOURCE_SYSTEM_REFERENCE_DESC           VARCHAR2(500)  
,ITEM_CATALOG_GROUP_NAME                VARCHAR2(820)  
,PRIMARY_UOM_NAME                       VARCHAR2(25)   
,CURRENT_PHASE_CODE                     VARCHAR2(120)  
,INVENTORY_ITEM_STATUS_CODE             VARCHAR2(10)   
,ASSET_TRACKED_FLAG                     VARCHAR2(5)    
,ALLOW_MAIN_PRCTENANCE_ASSET_FLAG       VARCHAR2(10)   
,ENABLE_GENEALOGY_TRACKING_FLAG         VARCHAR2(10)   
,ASSET_CLASS                            VARCHAR2(30)   
,EAM_ITEM_TYPE                          NUMBER         
,EAM_ACTIVITY_TYPE_CODE                 VARCHAR2(30)   
,EAM_ACTIVITY_CAUSE_CODE                VARCHAR2(30)   
,EAM_ACT_NOTIFICATION_FLAG              VARCHAR2(10)   
,EAM_ACT_SHUTDOWN_STATUS                VARCHAR2(30)   
,EAM_ACTIVITY_SOURCE_CODE               VARCHAR2(30)   
,COSTING_ENABLED_FLAG                   VARCHAR2(10)   
,STD_LOT_SIZE                           NUMBER         
,INVENTORY_ASSET_FLAG                   VARCHAR2(10)   
,DEFAULT_INCLUDE_IN_ROLLUP_FLAG         VARCHAR2(10)   
,ORDER_COST                             NUMBER         
,VMI_MINIMUM_DAYS                       NUMBER         
,VMI_FIXED_ORDER_QUANTITY               NUMBER         
,VMI_MINIMUM_UNITS                      NUMBER         
,ASN_AUTOEXPIRE_FLAG                    NUMBER         
,CARRYING_COST                          NUMBER         
,CONSIGNED_FLAG                         NUMBER         
,FIXED_DAYS_SUPPLY                      NUMBER         
,FIXED_LOT_MULTIPLIER                   NUMBER         
,FIXED_ORDER_QUANTITY                   NUMBER         
,FORECAST_HORIZON                       NUMBER         
,INVENTORY_PLANNING_CODE                NUMBER         
,SAFETY_STOCK_PLANNING_METHOD           NUMBER         
,DEMAND_PERIOD                          NUMBER         
,DAYS_OF_COVER                          NUMBER         
,MIN_MINMAX_QUANTITY                    NUMBER         
,MAX_MINMAX_QUANTITY                    NUMBER         
,MINIMUM_ORDER_QUANTITY                 NUMBER         
,MAXIMUM_ORDER_QUANTITY                 NUMBER         
,PLANNER_CODE                           VARCHAR2(10)   
,PLANNING_MAKE_BUY_CODE                 VARCHAR2(10)   
,SOURCE_SUBINVENTORY                    VARCHAR2(10)   
,SOURCE_TYPE                            NUMBER         
,SO_AUTHORIZATION_FLAG                  NUMBER         
,SUBCONTRACTING_COMPONENT               NUMBER         
,VMI_FORECAST_TYPE                      NUMBER         
,VMI_MAXIMUM_UNITS                      NUMBER         
,VMI_MAXIMUM_DAYS                       NUMBER         
,SOURCE_ORGANIZATION_CODE               VARCHAR2(50)   
,RESTRICT_SUBINVENTORIES_CODE           NUMBER         
,RESTRICT_LOCATORS_CODE                 NUMBER         
,CHILD_LOT_FLAG                         VARCHAR2(10)   
,CHILD_LOT_PREFIX                       VARCHAR2(30)   
,CHILD_LOT_STARTING_NUMBER              NUMBER         
,CHILD_LOT_VALIDATION_FLAG              VARCHAR2(10)   
,COPY_LOT_ATTRIBUTE_FLAG                VARCHAR2(10)   
,EXPIRATION_ACTION_CODE                 VARCHAR2(32)   
,EXPIRATION_ACTION_INTERVAL             NUMBER         
,STOCK_ENABLED_FLAG                     VARCHAR2(10)   
,START_AUTO_LOT_NUMBER                  VARCHAR2(80)   
,SHELF_LIFE_CODE                        NUMBER         
,SHELF_LIFE_DAYS                        NUMBER         
,SERIAL_NUMBER_CONTROL_CODE             NUMBER         
,SERIAL_STATUS_ENABLED                  VARCHAR2(10)   
,REVISION_QTY_CONTROL_CODE              NUMBER         
,RETEST_INTERVAL                        NUMBER         
,AUTO_LOT_ALPHA_PREFIX                  VARCHAR2(80)   
,AUTO_SERIAL_ALPHA_PREFIX               VARCHAR2(80)   
,BULK_PICKED_FLAG                       VARCHAR2(10)   
,CHECK_SHORTAGES_FLAG                   VARCHAR2(10)   
,CYCLE_COUNT_ENABLED_FLAG               VARCHAR2(10)   
,DEFAULT_GRADE                          VARCHAR2(150)  
,GRADE_CONTROL_FLAG                     VARCHAR2(10)   
,HOLD_DAYS                              NUMBER         
,LOT_DIVISIBLE_FLAG                     VARCHAR2(10)   
,MATURITY_DAYS                          NUMBER         
,DEFAULT_LOT_STATUS_ID                  NUMBER(18)     
,DEFAULT_SERIAL_STATUS_ID               NUMBER(18)     
,LOT_SPLIT_ENABLED                      VARCHAR2(10)   
,LOT_MERGE_ENABLED                      VARCHAR2(10)   
,INVENTORY_ITEM_FLAG                    VARCHAR2(10)   
,LOCATION_CONTROL_CODE                  NUMBER         
,LOT_CONTROL_CODE                       NUMBER         
,LOT_STATUS_ENABLED                     VARCHAR2(10)   
,LOT_SUBSTITUTION_ENABLED               VARCHAR2(10)   
,LOT_TRANSLATE_ENABLED                  VARCHAR2(10)   
,MTL_TRANSACTIONS_ENABLED_FLAG          VARCHAR2(10)   
,POSITIVE_MEASUREMENT_ERROR             NUMBER         
,NEGATIVE_MEASUREMENT_ERROR             NUMBER         
,PARENT_CHILD_GENERATION_FLAG           VARCHAR2(10)   
,RESERVABLE_TYPE                        NUMBER         
,START_AUTO_SERIAL_NUMBER               VARCHAR2(80)   
,INVOICING_RULE_NAME                    NUMBER(18)     
,TAX_CODE                               VARCHAR2(50)   
,SALES_ACCOUNT                          NUMBER(18)     
,PAYMENT_TERMS_NAME                     VARCHAR2(15)   
,INVOICE_ENABLED_FLAG                   VARCHAR2(10)   
,INVOICEABLE_ITEM_FLAG                  VARCHAR2(10)   
,ACCOUNTING_RULE_NAME                   NUMBER(18)     
,AUTO_CREATED_CONFIG_FLAG               VARCHAR2(10)   
,REPLENISH_TO_ORDER_FLAG                VARCHAR2(10)   
,PICK_COMPONENTS_FLAG                   VARCHAR2(10)   
,BASE_ITEM_NUMBER                       VARCHAR2(300)  
,EFFECTIVITY_CONTROL                    NUMBER         
,CONFIG_ORGS                            VARCHAR2(30)   
,CONFIG_MATCH                           VARCHAR2(30)   
,CONFIG_MODEL_TYPE                      VARCHAR2(30)   
,BOM_ITEM_TYPE                          NUMBER         
,CUM_MANUFACTURING_LEAD_TIME            NUMBER         
,PREPROCESSING_LEAD_TIME                NUMBER         
,CUMULATIVE_TOTAL_LEAD_TIME             NUMBER         
,FIXED_LEAD_TIME                        NUMBER         
,VARIABLE_LEAD_TIME                     NUMBER         
,FULL_LEAD_TIME                         NUMBER         
,LEAD_TIME_LOT_SIZE                     NUMBER         
,POSTPROCESSING_LEAD_TIME               NUMBER         
,ATO_FORECAST_CONTROL                   NUMBER         
,CRITICAL_COMPONENT_FLAG                NUMBER         
,ACCEPTABLE_EARLY_DAYS                  NUMBER         
,CREATE_SUPPLY_FLAG                     VARCHAR2(10)   
,DAYS_TGT_INV_SUPPLY                    NUMBER         
,DAYS_TGT_INV_WINDOW                    NUMBER         
,DAYS_MAX_INV_SUPPLY                    NUMBER         
,DAYS_MAX_INV_WINDOW                    NUMBER         
,DEMAND_TIME_FENCE_CODE                 NUMBER         
,DEMAND_TIME_FENCE_DAYS                 NUMBER         
,DRP_PLANNED_FLAG                       NUMBER         
,END_ASSEMBLY_PEGGING_FLAG              VARCHAR2(10)   
,EXCLUDE_FROM_BUDGET_FLAG               NUMBER         
,MRP_CALCULATE_ATP_FLAG                 VARCHAR2(10)   
,MRP_PLANNING_CODE                      NUMBER         
,PLANNED_INV_POINT_FLAG                 VARCHAR2(10)   
,PLANNING_TIME_FENCE_CODE               NUMBER         
,PLANNING_TIME_FENCE_DAYS               NUMBER         
,PREPOSITION_POINT                      VARCHAR2(10)   
,RELEASE_TIME_FENCE_CODE                NUMBER         
,RELEASE_TIME_FENCE_DAYS                NUMBER         
,REPAIR_LEADTIME                        NUMBER         
,REPAIR_YIELD                           NUMBER         
,REPAIR_PROGRAM                         NUMBER         
,ROUNDING_CONTROL_TYPE                  NUMBER         
,SHRINKAGE_RATE                         NUMBER         
,SUBSTITUTION_WINDOW_CODE               NUMBER         
,SUBSTITUTION_WINDOW_DAYS               NUMBER         
,TRADE_ITEM_DESCRIPTOR                  VARCHAR2(35)   
,ALLOWED_UNITS_LOOKUP_CODE              NUMBER         
,DUAL_UOM_DEVIATION_HIGH                NUMBER         
,DUAL_UOM_DEVIATION_LOW                 NUMBER         
,ITEM_TYPE                              VARCHAR2(30)   
,LONG_DESCRIPTION                       VARCHAR2(4000) 
,HTML_LONG_DESCRIPTION                  CLOB           
,ONT_PRICING_QTY_SOURCE                 VARCHAR2(30)   
,SECONDARY_DEFAULT_IND                  VARCHAR2(30)   
,SECONDARY_UOM_NAME                     VARCHAR2(25)   
,TRACKING_QUANTITY_IND                  VARCHAR2(30)   
,ENGINEERED_ITEM_FLAG                   VARCHAR2(10)   
,ATP_COMPONENTS_FLAG                    VARCHAR2(10)   
,ATP_FLAG                               VARCHAR2(10)   
,OVER_SHIPMENT_TOLERANCE                NUMBER         
,UNDER_SHIPMENT_TOLERANCE               NUMBER         
,OVER_RETURN_TOLERANCE                  NUMBER         
,UNDER_RETURN_TOLERANCE                 NUMBER         
,DOWNLOADABLE_FLAG                      VARCHAR2(10)   
,ELECTRONIC_FLAG                        VARCHAR2(10)   
,INDIVISIBLE_FLAG                       VARCHAR2(10)   
,INTERNAL_ORDER_ENABLED_FLAG            VARCHAR2(10)   
,ATP_RULE_ID                            NUMBER(18)     
,CHARGE_PERIODICITY_NAME                VARCHAR2(25)   
,CUSTOMER_ORDER_ENABLED_FLAG            VARCHAR2(10)   
,DEFAULT_SHIPPING_ORG_CODE              VARCHAR2(50)   
,DEFAULT_SO_SOURCE_TYPE                 VARCHAR2(30)   
,ELIGIBILITY_COMPATIBILITY_RULE         VARCHAR2(10)   
,FINANCING_ALLOWED_FLAG                 VARCHAR2(10)   
,INTERNAL_ORDER_FLAG                    VARCHAR2(10)   
,PICKING_RULE_ID                        NUMBER         
,RETURNABLE_FLAG                        VARCHAR2(10)   
,RETURN_INSPECTION_REQUIREMENT          NUMBER         
,SALES_PRODUCT_TYPE                     VARCHAR2(30)   
,BACK_TO_BACK_ENABLED                   VARCHAR2(5)    
,SHIPPABLE_ITEM_FLAG                    VARCHAR2(10)   
,SHIP_MODEL_COMPLETE_FLAG               VARCHAR2(10)   
,SO_TRANSACTIONS_FLAG                   VARCHAR2(10)   
,CUSTOMER_ORDER_FLAG                    VARCHAR2(10)   
,UNIT_WEIGHT                            NUMBER         
,WEIGHT_UOM_NAME                        VARCHAR2(25)   
,UNIT_VOLUME                            NUMBER         
,VOLUME_UOM_NAME                        VARCHAR2(25)   
,DIMENSION_UOM_NAME                     VARCHAR2(25)   
,UNIT_LENGTH                            NUMBER         
,UNIT_WIDTH                             NUMBER         
,UNIT_HEIGHT                            NUMBER         
,COLLATERAL_FLAG                        VARCHAR2(10)   
,CONTAINER_ITEM_FLAG                    VARCHAR2(10)   
,CONTAINER_TYPE_CODE                    VARCHAR2(30)   
,EQUIPMENT_TYPE                         NUMBER         
,EVENT_FLAG                             VARCHAR2(10)   
,INTERNAL_VOLUME                        NUMBER         
,MAXIMUM_LOAD_WEIGHT                    NUMBER         
,MINIMUM_FILL_PERCENT                   NUMBER         
,VEHICLE_ITEM_FLAG                      VARCHAR2(10)   
,CAS_NUMBER                             VARCHAR2(30)   
,HAZARDOUS_MATERIAL_FLAG                VARCHAR2(10)   
,PROCESS_COSTING_ENABLED_FLAG           VARCHAR2(10)   
,PROCESS_EXECUTION_ENABLED_FLAG         VARCHAR2(10)   
,PROCESS_QUALITY_ENABLED_FLAG           VARCHAR2(10)   
,PROCESS_SUPPLY_LOCATOR_ID              NUMBER(18)     
,PROCESS_SUPPLY_SUBINVENTORY            VARCHAR2(10)   
,PROCESS_YIELD_LOCATOR_ID               NUMBER(18)     
,PROCESS_YIELD_SUBINVENTORY             VARCHAR2(10)   
,RECIPE_ENABLED_FLAG                    VARCHAR2(10)   
,EXPENSE_ACCOUNT                        NUMBER(18)     
,UN_NUMBER_CODE                         VARCHAR2(30)   
,UNIT_OF_ISSUE                          VARCHAR2(25)   
,ROUNDING_FACTOR                        NUMBER         
,RECEIVE_CLOSE_TOLERANCE                NUMBER         
,PURCHASING_TAX_CODE                    VARCHAR2(50)   
,PURCHASING_ITEM_FLAG                   VARCHAR2(10)   
,PRICE_TOLERANCE_PERCENT                NUMBER         
,OUTSOURCED_ASSEMBLY                    NUMBER         
,OUTSIDE_OPERATION_UOM_TYPE             VARCHAR2(25)   
,NEGOTIATION_REQUIRED_FLAG              VARCHAR2(10)   
,MUST_USE_APPROVED_VENDOR_FLAG          VARCHAR2(10)   
,MATCH_APPROVAL_LEVEL                   NUMBER(1)      
,INVOICE_MATCH_OPTION                   NUMBER(1)      
,LIST_PRICE_PER_UNIT                    NUMBER         
,INVOICE_CLOSE_TOLERANCE                NUMBER         
,HAZARD_CLASS_CODE                      VARCHAR2(30)   
,BUYER_NAME                             VARCHAR2(960)  
,TAXABLE_FLAG                           VARCHAR2(10)   
,PURCHASING_ENABLED_FLAG                VARCHAR2(10)   
,OUTSIDE_OPERATION_FLAG                 VARCHAR2(10)   
,MARKET_PRICE                           NUMBER         
,ASSET_CATEGORY_ID                      NUMBER(18)     
,ALLOW_ITEM_DESC_UPDATE_FLAG            VARCHAR2(10)   
,ALLOW_EXPRESS_DELIVERY_FLAG            VARCHAR2(10)   
,ALLOW_SUBSTITUTE_RECEIPTS_FLAG         VARCHAR2(10)   
,ALLOW_UNORDERED_RECEIPTS_FLAG          VARCHAR2(10)   
,DAYS_EARLY_RECEIPT_ALLOWED             NUMBER         
,DAYS_LATE_RECEIPT_ALLOWED              NUMBER         
,RECEIVING_ROUTING_ID                   NUMBER(18)     
,ENFORCE_SHIP_TO_LOCATION_CODE          VARCHAR2(25)   
,QTY_RCV_EXCEPTION_CODE                 VARCHAR2(25)   
,QTY_RCV_TOLERANCE                      NUMBER         
,RECEIPT_DAYS_EXCEPTION_CODE            VARCHAR2(25)   
,ASSET_CREATION_CODE                    VARCHAR2(30)   
,SERVICE_START_TYPE_CODE                VARCHAR2(30)   
,COMMS_NL_TRACKABLE_FLAG                VARCHAR2(10)   
,CSS_ENABLED_FLAG                       VARCHAR2(10)   
,CONTRACT_ITEM_TYPE_CODE                VARCHAR2(30)   
,STANDARD_COVERAGE                      VARCHAR2(150)  
,DEFECT_TRACKING_ON_FLAG                VARCHAR2(10)   
,IB_ITEM_INSTANCE_CLASS                 VARCHAR2(30)   
,MATERIAL_BILLABLE_FLAG                 VARCHAR2(30)   
,RECOVERED_PART_DISP_CODE               VARCHAR2(30)   
,SERVICEABLE_PRODUCT_FLAG               VARCHAR2(10)   
,SERVICE_STARTING_DELAY                 NUMBER         
,SERVICE_DURATION                       NUMBER         
,SERVICE_DURATION_PERIOD_NAME           VARCHAR2(25)   
,SERV_REQ_ENABLED_CODE                  VARCHAR2(30)   
,ALLOW_SUSPEND_FLAG                     VARCHAR2(10)   
,ALLOW_TERMINATE_FLAG                   VARCHAR2(10)   
,REQUIRES_FULFILLMENT_LOC_FLAG          VARCHAR2(10)   
,REQUIRES_ITM_ASSOCIATION_FLAG          VARCHAR2(10)   
,SERVICE_START_DELAY                    NUMBER         
,SERVICE_DURATION_TYPE_CODE             VARCHAR2(30)   
,COMMS_ACTIVATION_REQD_FLAG             VARCHAR2(10)   
,SERV_BILLING_ENABLED_FLAG              VARCHAR2(10)   
,ORDERABLE_ON_WEB_FLAG                  VARCHAR2(10)   
,BACK_ORDERABLE_FLAG                    VARCHAR2(10)   
,WEB_STATUS                             VARCHAR2(30)   
,MINIMUM_LICENSE_QUANTITY               NUMBER         
,BUILD_IN_WIP_FLAG                      VARCHAR2(10)   
,CONTRACT_MANUFACTURING                 VARCHAR2(10)   
,WIP_SUPPLY_LOCATOR_ID                  NUMBER(18)     
,WIP_SUPPLY_TYPE                        NUMBER(18)     
,WIP_SUPPLY_SUBINVENTORY                VARCHAR2(10)   
,OVERCOMPLETION_TOLERANCE_TYPE          NUMBER         
,OVERCOMPLETION_TOLERANCE_VALUE         NUMBER         
,INVENTORY_CARRY_PENALTY                NUMBER         
,OPERATION_SLACK_PENALTY                NUMBER         
,REVISION                               VARCHAR2(50)   
,STYLE_ITEM_FLAG                        VARCHAR2(10)   
,STYLE_ITEM_NUMBER                      VARCHAR2(700)  
,VERSION_START_DATE                     DATE           
,VERSION_REVISION_CODE                  VARCHAR2(50)   
,VERSION_LABEL                          VARCHAR2(80)   
,START_UPON_MILESTONE_CODE              VARCHAR2(30)   
,SALES_PRODUCT_SUB_TYPE                 VARCHAR2(30)   
,GLOBAL_ATTRIBUTE_CATEGORY              VARCHAR2(150)  
,GLOBAL_ATTRIBUTE1                      VARCHAR2(150)  
,GLOBAL_ATTRIBUTE2                      VARCHAR2(150)  
,GLOBAL_ATTRIBUTE3                      VARCHAR2(150)  
,GLOBAL_ATTRIBUTE4                      VARCHAR2(150)  
,GLOBAL_ATTRIBUTE5                      VARCHAR2(150)  
,GLOBAL_ATTRIBUTE6                      VARCHAR2(150)  
,GLOBAL_ATTRIBUTE7                      VARCHAR2(150)  
,GLOBAL_ATTRIBUTE8                      VARCHAR2(150)  
,GLOBAL_ATTRIBUTE9                      VARCHAR2(150)  
,GLOBAL_ATTRIBUTE10                     VARCHAR2(150)  
,ATTRIBUTE_CATEGORY                     VARCHAR2(30)   
,ATTRIBUTE1                             VARCHAR2(500)  
,ATTRIBUTE2                             VARCHAR2(500)  
,ATTRIBUTE3                             VARCHAR2(500)  
,ATTRIBUTE4                             VARCHAR2(500)  
,ATTRIBUTE5                             VARCHAR2(500)  
,ATTRIBUTE6                             VARCHAR2(500)  
,ATTRIBUTE7                             VARCHAR2(500)  
,ATTRIBUTE8                             VARCHAR2(500)  
,ATTRIBUTE9                             VARCHAR2(500)  
,ATTRIBUTE10                            VARCHAR2(500)  
,ATTRIBUTE11                            VARCHAR2(500)  
,ATTRIBUTE12                            VARCHAR2(500)  
,ATTRIBUTE13                            VARCHAR2(500)  
,ATTRIBUTE14                            VARCHAR2(500)  
,ATTRIBUTE15                            VARCHAR2(500)  
,ATTRIBUTE16                            VARCHAR2(500)  
,ATTRIBUTE17                            VARCHAR2(500)  
,ATTRIBUTE18                            VARCHAR2(500)  
,ATTRIBUTE19                            VARCHAR2(500)  
,ATTRIBUTE20                            VARCHAR2(500)  
,ATTRIBUTE21                            VARCHAR2(500)  
,ATTRIBUTE22                            VARCHAR2(500)  
,ATTRIBUTE23                            VARCHAR2(500)  
,ATTRIBUTE24                            VARCHAR2(500)  
,ATTRIBUTE25                            VARCHAR2(500)  
,ATTRIBUTE26                            VARCHAR2(500)  
,ATTRIBUTE27                            VARCHAR2(500)  
,ATTRIBUTE28                            VARCHAR2(500)  
,ATTRIBUTE29                            VARCHAR2(500)  
,ATTRIBUTE30                            VARCHAR2(500)  
,ATTRIBUTE_NUMBER1                      NUMBER         
,ATTRIBUTE_NUMBER2                      NUMBER         
,ATTRIBUTE_NUMBER3                      NUMBER         
,ATTRIBUTE_NUMBER4                      NUMBER         
,ATTRIBUTE_NUMBER5                      NUMBER         
,ATTRIBUTE_NUMBER6                      NUMBER         
,ATTRIBUTE_NUMBER7                      NUMBER         
,ATTRIBUTE_NUMBER8                      NUMBER         
,ATTRIBUTE_NUMBER9                      NUMBER         
,ATTRIBUTE_NUMBER10                     NUMBER         
,ATTRIBUTE_DATE1                        DATE           
,ATTRIBUTE_DATE2                        DATE           
,ATTRIBUTE_DATE3                        DATE           
,ATTRIBUTE_DATE4                        DATE           
,ATTRIBUTE_DATE5                        DATE           
,ATTRIBUTE_TIMESTAMP1                   TIMESTAMP(6)   
,ATTRIBUTE_TIMESTAMP2                   TIMESTAMP(6)   
,ATTRIBUTE_TIMESTAMP3                   TIMESTAMP(6)   
,ATTRIBUTE_TIMESTAMP4                   TIMESTAMP(6)   
,ATTRIBUTE_TIMESTAMP5                   TIMESTAMP(6)   
,GLOBAL_ATTRIBUTE11                     VARCHAR2(150)  
,GLOBAL_ATTRIBUTE12                     VARCHAR2(150)  
,GLOBAL_ATTRIBUTE13                     VARCHAR2(150)  
,GLOBAL_ATTRIBUTE14                     VARCHAR2(150)  
,GLOBAL_ATTRIBUTE15                     VARCHAR2(150)  
,GLOBAL_ATTRIBUTE16                     VARCHAR2(150)  
,GLOBAL_ATTRIBUTE17                     VARCHAR2(150)  
,GLOBAL_ATTRIBUTE18                     VARCHAR2(150)  
,GLOBAL_ATTRIBUTE19                     VARCHAR2(150)  
,GLOBAL_ATTRIBUTE20                     VARCHAR2(150)  
,GLOBAL_ATTRIBUTE_NUMBER1               NUMBER         
,GLOBAL_ATTRIBUTE_NUMBER2               NUMBER         
,GLOBAL_ATTRIBUTE_NUMBER3               NUMBER         
,GLOBAL_ATTRIBUTE_NUMBER4               NUMBER         
,GLOBAL_ATTRIBUTE_NUMBER5               NUMBER         
,GLOBAL_ATTRIBUTE_DATE1                 DATE           
,GLOBAL_ATTRIBUTE_DATE2                 DATE           
,GLOBAL_ATTRIBUTE_DATE3                 DATE           
,GLOBAL_ATTRIBUTE_DATE4                 DATE           
,GLOBAL_ATTRIBUTE_DATE5                 DATE           
,PRC_BU_NAME                            VARCHAR2(500)  
,FORCE_PURCHASE_LEAD_TIME_FLAG          VARCHAR2(10)   
,REPLACEMENT_TYPE                       VARCHAR2(30)   
,BUYER_EMAIL_ADDRESS                    VARCHAR2(500)  
,DEFAULT_EXPENDITURE_TYPE               VARCHAR2(500)  
,HARD_PEGGING_LEVEL                     VARCHAR2(25)   
,COMN_SUPPLY_PRJ_DEMAND_FLAG            VARCHAR2(10)   
,ENABLE_IOT_FLAG                        VARCHAR2(10)   
,PACKAGING_STRING                       VARCHAR2(100)  
,CREATE_SUPPLY_AFTER_DATE               DATE           
,CREATE_FIXED_ASSET                     VARCHAR2(30)   
,UNDER_COMPL_TOLERANCE_TYPE             VARCHAR2(30)   
,UNDER_COMPL_TOLERANCE_VALUE            NUMBER         
,REPAIR_TRANSACTION_NAME                VARCHAR2(250)  
,NEW_PRIMARY_UOM_NAME                   VARCHAR2(25)   
,NEW_SECONDARY_UOM_NAME                 VARCHAR2(25)   
,ITEM_CLASS_NAME                        VARCHAR2(820)  
,NEW_ITEM_CLASS_NAME                    VARCHAR2(820)  
,FILE_NAME                              VARCHAR2(4000) 
,IMPORT_STATUS                          VARCHAR2(4000) 
,ERROR_MESSAGE                          VARCHAR2(4000) 
,FILE_REFERENCE_IDENTIFIER              VARCHAR2(4000) 
,SOURCE_SYSTEM                          VARCHAR2(4000) 
,EXECUTION_ID                           VARCHAR2(4000) 
,OC_ITEM_TYPE                           VARCHAR2(30)   
);