CREATE TABLE xxcnv.xxcnv_ap_c006_poz_supplier_sites_stg
(
BATCH_ID                                VARCHAR2(200)  
,IMPORT_ACTION                           VARCHAR2(10)   
,VENDOR_NAME                             VARCHAR2(360)  
,PROCUREMENT_BUSINESS_UNIT_NAME          VARCHAR2(240)  
,PARTY_SITE_NAME                         VARCHAR2(240)  
,VENDOR_SITE_CODE                        VARCHAR2(240)  
,VENDOR_SITE_CODE_NEW                    VARCHAR2(240)  
,INACTIVE_DATE                           DATE           
,RFQ_ONLY_SITE_FLAG                      VARCHAR2(1)    
,PURCHASING_SITE_FLAG                    VARCHAR2(1)    
,PCARD_SITE_FLAG                         VARCHAR2(1)    
,PAY_SITE_FLAG                           VARCHAR2(1)    
,PRIMARY_PAY_SITE_FLAG                   VARCHAR2(1)    
,TAX_REPORTING_SITE_FLAG                 VARCHAR2(1)    
,VENDOR_SITE_CODE_ALT                    VARCHAR2(320)  
,CUSTOMER_NUM                            VARCHAR2(25)   
,B2B_COMMUNICATION_METHOD                VARCHAR2(30)   
,B2B_SITE_CODE                           VARCHAR2(256)  
,SUPPLIER_NOTIF_METHOD                   VARCHAR2(25)   
,EMAIL_ADDRESS                           VARCHAR2(2000) 
,FAX_COUNTRY_CODE                        VARCHAR2(10)   
,FAX_AREA_CODE                           VARCHAR2(10)   
,FAX                                     VARCHAR2(15)   
,HOLD_FLAG                               VARCHAR2(1)    
,PURCHASING_HOLD_REASON                  VARCHAR2(240)  
,CARRIER                                 VARCHAR2(360)  
,MODE_OF_TRANSPORT_CODE                  VARCHAR2(30)   
,SERVICE_LEVEL_CODE                      VARCHAR2(30)   
,FREIGHT_TERMS_LOOKUP_CODE               VARCHAR2(30)   
,PAY_ON_CODE                             VARCHAR2(25)   
,FOB_LOOKUP_CODE                         VARCHAR2(25)   
,COUNTRY_OF_ORIGIN_CODE                  VARCHAR2(2)    
,BUYER_MANAGED_TRANSPORT_FLAG            VARCHAR2(1)    
,PAY_ON_USE_FLAG                         VARCHAR2(1)    
,AGING_ONSET_POINT                       VARCHAR2(30)   
,AGING_PERIOD_DAYS                       NUMBER(5)      
,CONSUMPTION_ADVICE_FREQUENCY            VARCHAR2(30)   
,CONSUMPTION_ADVICE_SUMMARY              VARCHAR2(30)   
,DEFAULT_PAY_SITE_CODE                   VARCHAR2(15)   
,PAY_ON_RECEIPT_SUMMARY_CODE             VARCHAR2(25)   
,GAPLESS_INV_NUM_FLAG                    VARCHAR2(1)    
,SELLING_COMPANY_IDENTIFIER              VARCHAR2(10)   
,CREATE_DEBIT_MEMO_FLAG                  VARCHAR2(25)   
,ENFORCE_SHIP_TO_LOCATION_CODE           VARCHAR2(25)   
,RECEIVING_ROUTING_ID                    VARCHAR2(18)   
,QTY_RCV_TOLERANCE                       NUMBER         
,QTY_RCV_EXCEPTION_CODE                  VARCHAR2(25)   
,DAYS_EARLY_RECEIPT_ALLOWED              NUMBER         
,DAYS_LATE_RECEIPT_ALLOWED               NUMBER         
,ALLOW_SUBSTITUTE_RECEIPTS_FLAG          VARCHAR2(1)    
,ALLOW_UNORDERED_RECEIPTS_FLAG           VARCHAR2(1)    
,RECEIPT_DAYS_EXCEPTION_CODE             VARCHAR2(25)   
,INVOICE_CURRENCY_CODE                   VARCHAR2(15)   
,INVOICE_AMOUNT_LIMIT                    NUMBER         
,MATCH_OPTION                            VARCHAR2(25)   
,MATCH_APPROVAL_LEVEL                    VARCHAR2(1)    
,PAYMENT_CURRENCY_CODE                   VARCHAR2(15)   
,PAYMENT_PRIORITY                        NUMBER         
,PAY_GROUP_LOOKUP_CODE                   VARCHAR2(25)   
,TOLERANCE_NAME                          VARCHAR2(255)  
,SERVICES_TOLERANCE                      VARCHAR2(255)  
,HOLD_ALL_PAYMENTS_FLAG                  VARCHAR2(1)    
,HOLD_UNMATCHED_INVOICES_FLAG            VARCHAR2(1)    
,HOLD_FUTURE_PAYMENTS_FLAG               VARCHAR2(1)    
,HOLD_BY                                 NUMBER         
,PAYMENT_HOLD_DATE                       DATE           
,HOLD_REASON                             VARCHAR2(240)  
,TERMS_NAME                              VARCHAR2(50)   
,TERMS_DATE_BASICS                       VARCHAR2(25)   
,PAY_DATE_BASIS_LOOKUP_CODE              VARCHAR2(25)   
,BANK_CHARGE_DEDUCTION_TYPE              VARCHAR2(1)    
,ALWAYS_TAKE_DISC_FLAG                   VARCHAR2(1)    
,EXCLUDE_FREIGHT_FROM_DISCOUNT           VARCHAR2(1)    
,EXCLUDE_TAX_FROM_DISCOUNT               VARCHAR2(1)    
,AUTO_CALCULATE_INTEREST_FLAG            VARCHAR2(1)    
,VAT_CODE_OBSOLETED                      VARCHAR2(30)   
,TAX_REGISTRATION_NUMBER_OBSOLETED       VARCHAR2(20)   
,PAYMENT_METHOD_LOOKUP_CODE              VARCHAR2(30)   
,DELIVERY_CHANNEL_CODE                   VARCHAR2(30)   
,BANK_INSTRUCTION1_CODE                  VARCHAR2(30)   
,BANK_INSTRUCTION2_CODE                  VARCHAR2(30)   
,BANK_INSTRUCTION_DETAILS                VARCHAR2(255)  
,SETTLEMENT_PRIORITY                     VARCHAR2(30)   
,PAYMENT_TEXT_MESSAGE1                   VARCHAR2(256)  
,PAYMENT_TEXT_MESSAGE2                   VARCHAR2(256)  
,PAYMENT_TEXT_MESSAGE3                   VARCHAR2(256)  
,IBY_BANK_VARCHAR2GE_BEARER              VARCHAR2(30)   
,PAYMENT_REASON_CODE                     VARCHAR2(30)   
,PAYMENT_REASON_COMMENTS                 VARCHAR2(240)  
,REMIT_ADVICE_DELIVERY_METHOD            VARCHAR2(30)   
,REMITTANCE_EMAIL                        VARCHAR2(255)  
,REMIT_ADVICE_FAX                        VARCHAR2(100)  
,ATTRIBUTE_CATEGORY                      VARCHAR2(30)   
,ATTRIBUTE1                              VARCHAR2(150)  
,ATTRIBUTE2                              VARCHAR2(150)  
,ATTRIBUTE3                              VARCHAR2(150)  
,ATTRIBUTE4                              VARCHAR2(150)  
,ATTRIBUTE5                              VARCHAR2(150)  
,ATTRIBUTE6                              VARCHAR2(150)  
,ATTRIBUTE7                              VARCHAR2(150)  
,ATTRIBUTE8                              VARCHAR2(150)  
,ATTRIBUTE9                              VARCHAR2(150)  
,ATTRIBUTE10                             VARCHAR2(150)  
,ATTRIBUTE11                             VARCHAR2(150)  
,ATTRIBUTE12                             VARCHAR2(150)  
,ATTRIBUTE13                             VARCHAR2(150)  
,ATTRIBUTE14                             VARCHAR2(150)  
,ATTRIBUTE15                             VARCHAR2(150)  
,ATTRIBUTE16                             VARCHAR2(150)  
,ATTRIBUTE17                             VARCHAR2(150)  
,ATTRIBUTE18                             VARCHAR2(150)  
,ATTRIBUTE19                             VARCHAR2(150)  
,ATTRIBUTE20                             VARCHAR2(150)  
,ATTRIBUTE_DATE1                         DATE           
,ATTRIBUTE_DATE2                         DATE           
,ATTRIBUTE_DATE3                         DATE           
,ATTRIBUTE_DATE4                         DATE           
,ATTRIBUTE_DATE5                         DATE           
,ATTRIBUTE_DATE6                         DATE           
,ATTRIBUTE_DATE7                         DATE           
,ATTRIBUTE_DATE8                         DATE           
,ATTRIBUTE_DATE9                         DATE           
,ATTRIBUTE_DATE10                        DATE           
,ATTRIBUTE_TIMESTAMP1                    TIMESTAMP(6)   
,ATTRIBUTE_TIMESTAMP2                    TIMESTAMP(6)   
,ATTRIBUTE_TIMESTAMP3                    TIMESTAMP(6)   
,ATTRIBUTE_TIMESTAMP4                    TIMESTAMP(6)   
,ATTRIBUTE_TIMESTAMP5                    TIMESTAMP(6)   
,ATTRIBUTE_TIMESTAMP6                    TIMESTAMP(6)   
,ATTRIBUTE_TIMESTAMP7                    TIMESTAMP(6)   
,ATTRIBUTE_TIMESTAMP8                    TIMESTAMP(6)   
,ATTRIBUTE_TIMESTAMP9                    TIMESTAMP(6)   
,ATTRIBUTE_TIMESTAMP10                   TIMESTAMP(6)   
,ATTRIBUTE_NUMBER1                       NUMBER         
,ATTRIBUTE_NUMBER2                       NUMBER         
,ATTRIBUTE_NUMBER3                       NUMBER         
,ATTRIBUTE_NUMBER4                       NUMBER         
,ATTRIBUTE_NUMBER5                       NUMBER         
,ATTRIBUTE_NUMBER6                       NUMBER         
,ATTRIBUTE_NUMBER7                       NUMBER         
,ATTRIBUTE_NUMBER8                       NUMBER         
,ATTRIBUTE_NUMBER9                       NUMBER         
,ATTRIBUTE_NUMBER10                      NUMBER         
,GLOBAL_ATTRIBUTE_CATEGORY               VARCHAR2(30)   
,GLOBAL_ATTRIBUTE1                       VARCHAR2(150)  
,GLOBAL_ATTRIBUTE2                       VARCHAR2(150)  
,GLOBAL_ATTRIBUTE3                       VARCHAR2(150)  
,GLOBAL_ATTRIBUTE4                       VARCHAR2(150)  
,GLOBAL_ATTRIBUTE5                       VARCHAR2(150)  
,GLOBAL_ATTRIBUTE6                       VARCHAR2(150)  
,GLOBAL_ATTRIBUTE7                       VARCHAR2(150)  
,GLOBAL_ATTRIBUTE8                       VARCHAR2(150)  
,GLOBAL_ATTRIBUTE9                       VARCHAR2(150)  
,GLOBAL_ATTRIBUTE10                      VARCHAR2(150)  
,GLOBAL_ATTRIBUTE11                      VARCHAR2(150)  
,GLOBAL_ATTRIBUTE12                      VARCHAR2(150)  
,GLOBAL_ATTRIBUTE13                      VARCHAR2(150)  
,GLOBAL_ATTRIBUTE14                      VARCHAR2(150)  
,GLOBAL_ATTRIBUTE15                      VARCHAR2(150)  
,GLOBAL_ATTRIBUTE16                      VARCHAR2(150)  
,GLOBAL_ATTRIBUTE17                      VARCHAR2(150)  
,GLOBAL_ATTRIBUTE18                      VARCHAR2(150)  
,GLOBAL_ATTRIBUTE19                      VARCHAR2(150)  
,GLOBAL_ATTRIBUTE20                      VARCHAR2(150)  
,GLOBAL_ATTRIBUTE_DATE1                  DATE           
,GLOBAL_ATTRIBUTE_DATE2                  DATE           
,GLOBAL_ATTRIBUTE_DATE3                  DATE           
,GLOBAL_ATTRIBUTE_DATE4                  DATE           
,GLOBAL_ATTRIBUTE_DATE5                  DATE           
,GLOBAL_ATTRIBUTE_DATE6                  DATE           
,GLOBAL_ATTRIBUTE_DATE7                  DATE           
,GLOBAL_ATTRIBUTE_DATE8                  DATE           
,GLOBAL_ATTRIBUTE_DATE9                  DATE           
,GLOBAL_ATTRIBUTE_DATE10                 DATE           
,GLOBAL_ATTRIBUTE_TIMESTAMP1             TIMESTAMP(6)   
,GLOBAL_ATTRIBUTE_TIMESTAMP2             TIMESTAMP(6)   
,GLOBAL_ATTRIBUTE_TIMESTAMP3             TIMESTAMP(6)   
,GLOBAL_ATTRIBUTE_TIMESTAMP4             TIMESTAMP(6)   
,GLOBAL_ATTRIBUTE_TIMESTAMP5             TIMESTAMP(6)   
,GLOBAL_ATTRIBUTE_TIMESTAMP6             TIMESTAMP(6)   
,GLOBAL_ATTRIBUTE_TIMESTAMP7             TIMESTAMP(6)   
,GLOBAL_ATTRIBUTE_TIMESTAMP8             TIMESTAMP(6)   
,GLOBAL_ATTRIBUTE_TIMESTAMP9             TIMESTAMP(6)   
,GLOBAL_ATTRIBUTE_TIMESTAMP10            TIMESTAMP(6)   
,GLOBAL_ATTRIBUTE_NUMBER1                NUMBER         
,GLOBAL_ATTRIBUTE_NUMBER2                NUMBER         
,GLOBAL_ATTRIBUTE_NUMBER3                NUMBER         
,GLOBAL_ATTRIBUTE_NUMBER4                NUMBER         
,GLOBAL_ATTRIBUTE_NUMBER5                NUMBER         
,GLOBAL_ATTRIBUTE_NUMBER6                NUMBER         
,GLOBAL_ATTRIBUTE_NUMBER7                NUMBER         
,GLOBAL_ATTRIBUTE_NUMBER8                NUMBER         
,GLOBAL_ATTRIBUTE_NUMBER9                NUMBER         
,GLOBAL_ATTRIBUTE_NUMBER10               NUMBER         
,PO_ACK_REQD_CODE                        VARCHAR2(30)   
,PO_ACK_REQD_DAYS                        NUMBER         
,INVOICE_CHANNEL                         VARCHAR2(30)   
,PAYEE_SERVICE_LEVEL_CODE                VARCHAR2(30)   
,EXCLUSIVE_PARENT_FLAG                   VARCHAR2(1)    
,FILE_NAME                               VARCHAR2(4000) 
,ERROR_MESSAGE                           VARCHAR2(4000) 
,IMPORT_STATUS                           VARCHAR2(4000) 
,FILE_REFERENCE_IDENTIFIER               VARCHAR2(4000) 
,EXECUTION_ID                            VARCHAR2(4000) 
,SOURCE_SYSTEM                           VARCHAR2(4000) 
);
