/*******************************************************************************************
NAME              :     xxcnv_ap_c012_supplier_bus_class_attachments_stg TABLE
 -- Modification History
	-- Developer         Date         Version     Comments and changes made
	-- -------------   ------         ----------  -----------------------------------------
	    Phanindra      28-Aug-2024        1.1       Made Changes as per the Jira LTCI-8094
*********************************************************************************************/
DROP TABLE xxcnv.xxcnv_ap_c012_supplier_bus_class_attachments_stg;

CREATE TABLE xxcnv.xxcnv_ap_c012_supplier_bus_class_attachments_stg
(RECORD_ID                      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY ( START WITH 1 MAXVALUE 999999999 MINVALUE 1 NOCYCLE NOCACHE NOORDER NOKEEP NOSCALE) NOT NULL,
BATCH_ID                        VARCHAR2(200) ,
IMPORT_ACTION                   VARCHAR2(10)   ,
VENDOR_NAME                     VARCHAR2(360)  ,
CLASSIFICATION                  VARCHAR2(240)  ,
SUBCLASSIFICATION               VARCHAR2(15)   ,
CERTIFYING_AGENCY               VARCHAR2(200)  ,
CERTIFICATE_NUMBER              VARCHAR2(200)  ,
ATTACHMENT_CATEGORY             VARCHAR2(200)  ,
ATTACHMENT_TYPE                 VARCHAR2(200)  ,
FILE_TEXT_URL                   CLOB                ,
FILE_ATTACHMENTS_ZIP            VARCHAR2(2000) ,
ATTACHMENT_TITLE                VARCHAR2(80)       ,
ATTACHMENT_DESCRIPTION          VARCHAR2(225)  ,
FILE_NAME                       VARCHAR2(200)  ,
IMPORT_STATUS                   VARCHAR2(200)  ,
ERROR_MESSAGE                   VARCHAR2(4000) ,
FILE_REFERENCE_IDENTIFIER       VARCHAR2(200)  ,
SOURCE_SYSTEM                   VARCHAR2(200)  ,
EXECUTION_ID                    VARCHAR2(200)  ,
ATTACHMENT_FLAG                 VARCHAR2(5)    DEFAULT 'N',
ATTACHMENT_ERROR                VARCHAR2(4000) ,
NS_VENDOR_NUM                    VARCHAR2(30)  --Added column for the change jira LTCI-8094
);