CREATE TABLE xxcnv.XXCNV_FA_LOCATION_SEGMENT_MAPPING
(
NETSUITE_ID       VARCHAR2(20) ,
EE_SITE           VARCHAR2(255) ,
COUNTRY           VARCHAR2(255) ,
STATE             VARCHAR2(255) ,
COUNTY            VARCHAR2(255) ,
CITY              VARCHAR2(255) ,
ZIP               VARCHAR2(255) ,
DEPRN_SEG1        VARCHAR2(20) 
);