  CREATE TABLE "XXCNV"."XXCNV_GL_C002_FBDI_JOURNAL_FILES_METADATA" 
   ("INTERFACE_RICE_ID" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"INTERFACE_RICE_NAME" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"PARENT_INSTANCE_ID" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"CURRENT_INSTANCE_ID" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"CYCLE" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"CONVERSION_ID" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"ITERATION_NUMBER" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"FBDI_FILE_NAME" VARCHAR2(2000 BYTE) COLLATE "USING_NLS_COMP", 
	"OBJECT_STORAGE_FILE_PATH" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP", 
	"LEDGER_NAME" VARCHAR2(250 BYTE) COLLATE "USING_NLS_COMP", 
	"GROUP_ID" VARCHAR2(250 BYTE) COLLATE "USING_NLS_COMP", 
	"PERIOD_NAME" VARCHAR2(250 BYTE) COLLATE "USING_NLS_COMP", 
	"SUBSIDIARY_NAME" VARCHAR2(250 BYTE) COLLATE "USING_NLS_COMP", 
	"FILE_TYPE" VARCHAR2(250 BYTE) COLLATE "USING_NLS_COMP", 
	"LOAD_REQUEST_ID" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"LOAD_REQUEST_STATUS" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"IMPORT_REQUEST_ID" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"IMPORT_REQUEST_STATUS" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"RECON_JOB_REPORT_ID" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"RECON_JOB_REPORT_NAME" VARCHAR2(2000 BYTE) COLLATE "USING_NLS_COMP", 
	"STATUS" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"MESSAGE" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"CREATED_BY" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"CREATED_DATE" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"LAST_UPDATED_BY" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"LAST_UPDATED_DATE" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

  CREATE INDEX "XXCNV"."XXCNV_GL_C002_FBDI_JOURNAL_FILES_METADATA_N1" ON "XXCNV"."XXCNV_GL_C002_FBDI_JOURNAL_FILES_METADATA" ("CURRENT_INSTANCE_ID", "FBDI_FILE_NAME", "GROUP_ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

  CREATE INDEX "XXCNV"."XXCNV_GL_C002_FBDI_JOURNAL_FILES_METADATA_N3" ON "XXCNV"."XXCNV_GL_C002_FBDI_JOURNAL_FILES_METADATA" ("CURRENT_INSTANCE_ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

  CREATE INDEX "XXCNV"."XXCNV_GL_C002_FBDI_JOURNAL_FILES_METADATA_N2" ON "XXCNV"."XXCNV_GL_C002_FBDI_JOURNAL_FILES_METADATA" ("LOAD_REQUEST_ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;


  GRANT INSERT ON "XXCNV"."XXCNV_GL_C002_FBDI_JOURNAL_FILES_METADATA" TO "XXINT";
  GRANT SELECT ON "XXCNV"."XXCNV_GL_C002_FBDI_JOURNAL_FILES_METADATA" TO "XXINT";
  GRANT UPDATE ON "XXCNV"."XXCNV_GL_C002_FBDI_JOURNAL_FILES_METADATA" TO "XXINT";
  GRANT SELECT ON "XXCNV"."XXCNV_GL_C002_FBDI_JOURNAL_FILES_METADATA" TO "XXCNV_RUN";
  GRANT SELECT ON "XXCNV"."XXCNV_GL_C002_FBDI_JOURNAL_FILES_METADATA" TO "XXRO";
  GRANT SELECT ON "XXMAP"."XXMAP_GL_SOURCES_REF" TO "XXCNV";
  GRANT UPDATE ON "XXMAP"."XXMAP_GL_SOURCES_REF" TO "XXCNV";
  GRANT INSERT ON "XXMAP"."XXMAP_GL_SOURCES_REF" TO "XXCNV";
  GRANT SELECT ON "XXMAP"."XXMAP_GL_JOB_PARAMETERS_REF" TO "XXCNV";
  GRANT INSERT ON "XXMAP"."XXMAP_GL_JOB_PARAMETERS_REF" TO "XXCNV";
  GRANT UPDATE ON "XXMAP"."XXMAP_GL_JOB_PARAMETERS_REF" TO "XXCNV";