CREATE TABLE  XXCNV.xxcnv_po_ship_to_location_mapping (
OS_LOCATION_CODE       VARCHAR2(200) ,
OS_LOCATION_NAME       VARCHAR2(200) ,
OS_SUB_INVENTORY       VARCHAR2(200) ,
OS_ORG_CODE            VARCHAR2(200) ,
OS_ORG_NAME            VARCHAR2(200) ,
NS_LOCATION_NAME       VARCHAR2(200)
)