CREATE TABLE xxcnv.XXCNV_FA_ASSET_CATEGORY_MAPPING
(NS_ASSET_CATEGORY                VARCHAR2(100) ,
ASSET_CATEGORY_ID_SEGMENT1       VARCHAR2(50)  ,
ASSET_CATEGORY_ID_SEGMENT2       VARCHAR2(50)  
);