CREATE TABLE XXCNV.XXCNV_PO_RECEIPTS_QUANTITY_MAPPING
(
PO_DOC                 VARCHAR2(30) ,
PO_DOC_LINE            NUMBER       ,
RECEIPT_NUMBER         VARCHAR2(30) ,
RECEIPT_QUANTITY       NUMBER       ,
BILLED_QUANTITY        NUMBER       ,
RECEIPT_ID             VARCHAR2(30) ,
PO_QUANTITY            NUMBER    
);