CREATE TABLE xxint.xxint_po_i030_po_lines_tbl (
    "XXINT_POLINE_SEQ_ID"    NUMBER
        GENERATED BY DEFAULT ON NULL AS IDENTITY,
    "OIC_BATCH_ID"           VARCHAR2(250 BYTE),
    "PO_LINE_NUM"            NUMBER,
    "PO_LINE_ID"             NUMBER NOT NULL PRIMARY KEY,
    "ITEM_DESCRIPTION"       VARCHAR2(250 BYTE),
    "ITEM_NUM"               VARCHAR2(100 BYTE),
    "ITEM_STATUS"            VARCHAR2(20 BYTE),
    "VENDOR_NAME"            VARCHAR2(100 BYTE),
    "DESCRIPTION"            VARCHAR2(250 BYTE),
    "QUANTITY"               NUMBER,
    "RATE"                   NUMBER,
    "AMOUNT"                 NUMBER,
    "COST_CENTER_DEPARTMENT" VARCHAR2(250 BYTE),
    "PAYMENT_SCHEDULE"       VARCHAR2(250 BYTE),
    "ERP_PO_NUM"             VARCHAR2(50 BYTE),
    "ERP_PO_ID"              NUMBER,
    "ACTION_TYPE"            VARCHAR2(20 BYTE),
    "STATUS"                 VARCHAR2(50 BYTE),
    "MESSAGE"                VARCHAR2(5000 BYTE),
    "CREATION_DATE"          DATE,
    "CREATED_BY"             VARCHAR2(250 BYTE),
    "LAST_UPDATE_DATE"       DATE,
    "LAST_UPDATED_BY"        VARCHAR2(50 BYTE),
    "ITEM_NETSUITE_ID"       VARCHAR2(100 BYTE),
    "ORGANIZATION_ID"        VARCHAR2(250 BYTE),
    "ORGANIZATION_CODE"      VARCHAR2(250 BYTE),
    "NS_PO_LINE_NUM"         NUMBER,
	"NS_PO_ID"				 VARCHAR2(250 BYTE)
);

CREATE INDEX xxint_po_i030_po_lines_tbl_n2 ON
    xxint.xxint_po_i030_po_lines_tbl (
        erp_po_num
    );