DROP TABLE IF EXISTS "XXINT"."XXINT_I130_EMPLOYEE_DEFAULT_EXPENSE_ACCOUNT_STG";
CREATE TABLE "XXINT"."XXINT_I130_EMPLOYEE_DEFAULT_EXPENSE_ACCOUNT_STG" (
    "ASSIGNMENT_ID"                NUMBER,
    "PERSON_ID"                    NUMBER,
    "PERSON_NUMBER"                VARCHAR2(30 BYTE),
    "LAST_NAME"                    VARCHAR2(200 BYTE),
    "FIRST_NAME"                   VARCHAR2(200 BYTE),
    "ASSIGNMENT_NUMBER"            VARCHAR2(50 BYTE),
    "ASSIGNMENT_NAME"              VARCHAR2(80 BYTE),
    "ASSIGNEMENT_STATUS_TYPE"      VARCHAR2(30 BYTE),
    "WORK_TERMS_ASSIGNMENT_ID"     NUMBER,
    "PERIOD_OF_SERVICE_ID"         NUMBER,
    "ACTION_CODE"                  VARCHAR2(240 BYTE),
    "LEGAL_EMPLOYER_NAME"          VARCHAR2(240 BYTE),
    "EFFECTIVE_START_DATE"         DATE,
    "PRIMARY_FLAG"                 VARCHAR2(10 BYTE),
    "PRIMARY_ASSIGNMENT_FLAG"      VARCHAR2(10 BYTE),
    "WORKER_TYPE"                  VARCHAR2(240 BYTE),
    "WORKER_NUMBER"                VARCHAR2(240 BYTE),
    "MANAGER_NAME"                 VARCHAR2(240 BYTE),
    "BUSINESS_UNIT_NAME"           VARCHAR2(240 BYTE),
    "DEPARTMENT_NAME"              VARCHAR2(240 BYTE),
    "JOB_CODE"                     VARCHAR2(240 BYTE),
    "JOB_NAME"                     VARCHAR2(240 BYTE),
    "LOCATION_CODE"                VARCHAR2(240 BYTE),
    "LOCATION_NAME"                VARCHAR2(240 BYTE),
    "GRADE_CODE"                   VARCHAR2(240 BYTE),
    "GRADE_NAME"                   VARCHAR2(240 BYTE),
    "Location_Address_Line1"       VARCHAR2(240 BYTE),
    "Location_Address_Line2"       VARCHAR2(240 BYTE),
    "Location_Address_Line3"       VARCHAR2(240 BYTE),
    "Location_Address_Line4"       VARCHAR2(240 BYTE),
    "Location_REGION1"             VARCHAR2(240 BYTE),
    "Location_REGION2"             VARCHAR2(240 BYTE),
    "Location_REGION3"             VARCHAR2(240 BYTE),
    "Location_REGION4"             VARCHAR2(240 BYTE),
    "Location_Town_Or_City"        VARCHAR2(240 BYTE),
    "Location_Postal_Code"         VARCHAR2(240 BYTE),
    "Location_Country"             VARCHAR2(240 BYTE),
    "Location_Long_Postal_Code"    VARCHAR2(240 BYTE),
    "Length_Of_Service_Years"      NUMBER,
    "Length_Of_Service_Months"     NUMBER,
    "Length_Of_Service_Days"       NUMBER,
    "DIVISION"                     VARCHAR2(240 BYTE),
    "EFFECTIVE_SEQUENCE"           VARCHAR2(20 BYTE),
    "DEFAULT_EXPENSE_ACCOUNT"      VARCHAR2(250 BYTE),
    "NEW_DEAFAULT_EXPENSE_ACCOUNT" VARCHAR2(250 BYTE),
    "COMPANY"                      VARCHAR2(250 BYTE),
    "LOCATION_SEGMENT"             VARCHAR2(250 BYTE),
    "DIVISION_SEGMENT"             VARCHAR2(250 BYTE),
    "COST_CENTER"                  VARCHAR2(250 BYTE),
    "CREATED_BY"                   VARCHAR2(240 BYTE),
    "LAST_UPDATED_BY"              VARCHAR2(240 BYTE),
    "CREATED_DATE"                 DATE,
    "LAST_UPDATE_DATE"             DATE,
    PRIMARY KEY ( "ASSIGNMENT_ID" )
);

CREATE INDEX "XXINT"."XXINT_I130_EMPLOYEE_DEFAULT_EXPENSE_ACCOUNT_STG_N1" ON
    "XXINT"."XXINT_I130_EMPLOYEE_DEFAULT_EXPENSE_ACCOUNT_STG" (
        "ASSIGNMENT_ID",
        "LOCATION_CODE",
        "DEPARTMENT_NAME",
        "LEGAL_EMPLOYER_NAME"
    );