--------------------------------------------------------
--  DDL for Table XXINT_GL_I001_JOURNALS_STG
--------------------------------------------------------

  CREATE TABLE "XXINT"."XXINT_GL_I001_JOURNALS_STG" 
   (	"CURRENT_INSTANCE_ID" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"PARENT_INSTANCE_ID" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"INTERFACE_RICE_ID" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"INTERFACE_RICE_NAME" VARCHAR2(1000 BYTE) COLLATE "USING_NLS_COMP", 
	"SOURCE_FILE_NAME" VARCHAR2(400 BYTE) COLLATE "USING_NLS_COMP", 
	"SOURCE" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"STATUS_CODE" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"LEDGER_ID" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"TRANSACTION_DATE" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"JOURNAL_SOURCE" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"JOURNAL_CATEGORY" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"CURRENCY_CODE" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"JE_CREATION_DATE" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"ACTUAL_FLAG" VARCHAR2(10 BYTE) COLLATE "USING_NLS_COMP", 
	"ERP_SEGMENT1" VARCHAR2(25 BYTE) COLLATE "USING_NLS_COMP", 
	"ERP_SEGMENT2" VARCHAR2(25 BYTE) COLLATE "USING_NLS_COMP", 
	"ERP_SEGMENT3" VARCHAR2(25 BYTE) COLLATE "USING_NLS_COMP", 
	"ERP_SEGMENT4" VARCHAR2(25 BYTE) COLLATE "USING_NLS_COMP", 
	"ERP_SEGMENT5" VARCHAR2(25 BYTE) COLLATE "USING_NLS_COMP", 
	"ERP_SEGMENT6" VARCHAR2(25 BYTE) COLLATE "USING_NLS_COMP", 
	"ERP_SEGMENT7" VARCHAR2(25 BYTE) COLLATE "USING_NLS_COMP", 
	"ERP_SEGMENT8" VARCHAR2(25 BYTE) COLLATE "USING_NLS_COMP", 
	"ERP_SEGMENT9" VARCHAR2(25 BYTE) COLLATE "USING_NLS_COMP", 
	"ERP_SEGMENT10" VARCHAR2(25 BYTE) COLLATE "USING_NLS_COMP", 
	"NS_SEGMENT1" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"NS_SEGMENT2" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"NS_SEGMENT3" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"NS_SEGMENT4" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"NS_SEGMENT5" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"NS_SEGMENT6" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"NS_SEGMENT7" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"NS_SEGMENT8" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"NS_SEGMENT9" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"NS_SEGMENT10" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"ENTERED_DEBIT_AMOUNT" VARCHAR2(250 BYTE) COLLATE "USING_NLS_COMP", 
	"ENTERED_CREDIT_AMOUNT" VARCHAR2(250 BYTE) COLLATE "USING_NLS_COMP", 
	"CONVERTED_DEBIT_AMOUNT" VARCHAR2(250 BYTE) COLLATE "USING_NLS_COMP", 
	"CONVERTED_CREDIT_AMOUNT" VARCHAR2(250 BYTE) COLLATE "USING_NLS_COMP", 
	"REFERENCE1" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"REFERENCE2" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"REFERENCE4" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"REFERENCE5" VARCHAR2(240 BYTE) COLLATE "USING_NLS_COMP", 
	"REFERENCE6" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"REFERENCE7" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"REFERENCE8" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"REFERENCE9" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"REFERENCE10" VARCHAR2(300 BYTE) COLLATE "USING_NLS_COMP", 
	"STATISTICAL_AMOUNT" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"CURRENCY_CONVERSION_TYPE" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"CURRENCY_CONVERSION_DATE" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"CURRENCY_CONVERSION_RATE" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"INTERFACE_GROUP_IDENTIFIER" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"CONTEXT_FIELD" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE1" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE2" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE3" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE4" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE5" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE6" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE7" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE8" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE9" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE10" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"CLEARING_COMPANY" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"LEDGER_NAME" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"ENCUMBRANCE_TYPE_ID" NUMBER, 
	"RECONCILIATION_REFERENCE" VARCHAR2(250 BYTE) COLLATE "USING_NLS_COMP", 
	"PERIOD_NAME" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE_DATE_1" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE_DATE_2" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE_DATE_3" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE_DATE_4" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE_DATE_5" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE_NUMBER_1" NUMBER, 
	"ATTRIBUTE_NUMBER_2" NUMBER, 
	"ATTRIBUTE_NUMBER_3" NUMBER, 
	"ATTRIBUTE_NUMBER_4" NUMBER, 
	"ATTRIBUTE_NUMBER_5" NUMBER, 
	"GLOBAL_ATTRIBUTE_CATEGORY" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"GLOBAL_ATTRIBUTE1" VARCHAR2(150 BYTE) COLLATE "USING_NLS_COMP", 
	"GLOBAL_ATTRIBUTE2" VARCHAR2(150 BYTE) COLLATE "USING_NLS_COMP", 
	"GLOBAL_ATTRIBUTE3" VARCHAR2(150 BYTE) COLLATE "USING_NLS_COMP", 
	"GLOBAL_ATTRIBUTE_DATE1" VARCHAR2(10 BYTE) COLLATE "USING_NLS_COMP", 
	"GLOBAL_ATTRIBUTE_DATE2" VARCHAR2(10 BYTE) COLLATE "USING_NLS_COMP", 
	"GLOBAL_ATTRIBUTE_DATE3" VARCHAR2(10 BYTE) COLLATE "USING_NLS_COMP", 
	"GLOBAL_ATTRIBUTE_NUMBER1" NUMBER, 
	"GLOBAL_ATTRIBUTE_NUMBER2" NUMBER, 
	"GLOBAL_ATTRIBUTE_NUMBER3" NUMBER, 
	"STATUS" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"MESSAGE" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"LOAD_REQUEST_ID" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"LOAD_REQUEST_STATUS" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"FBDI_FILE_NAME" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"IMPORT_REQUEST_ID" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"IMPORT_REQUEST_STATUS" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"CREATED_DATE_TIME" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP", 
	"CREATED_BY" VARCHAR2(40 BYTE) COLLATE "USING_NLS_COMP", 
	"CREATION_DATE" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP", 
	"LAST_UPDATED_BY" VARCHAR2(40 BYTE) COLLATE "USING_NLS_COMP", 
	"LAST_UPDATED_DATE" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP", 
	"ADD_ATTRIBUTE1" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"ADD_ATTRIBUTE2" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"ADD_ATTRIBUTE3" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"PROCESS_BATCH_ID" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"COA_BATCH_ID" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"REPROCESSING_FLAG" VARCHAR2(10 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
 
--------------------------------------------------------
--  DDL for Index XXINT_GL_I001_JOURNALS_STG_N7
--------------------------------------------------------

  CREATE INDEX "XXINT"."XXINT_GL_I001_JOURNALS_STG_N7" ON "XXINT"."XXINT_GL_I001_JOURNALS_STG" ("PARENT_INSTANCE_ID", "SOURCE_FILE_NAME") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index XXINT_GL_I001_JOURNALS_STG_N1
--------------------------------------------------------

  CREATE INDEX "XXINT"."XXINT_GL_I001_JOURNALS_STG_N1" ON "XXINT"."XXINT_GL_I001_JOURNALS_STG" ("CURRENT_INSTANCE_ID", "PARENT_INSTANCE_ID", "INTERFACE_RICE_ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index XXINT_GL_I001_JOURNALS_STG_N2
--------------------------------------------------------

  CREATE INDEX "XXINT"."XXINT_GL_I001_JOURNALS_STG_N2" ON "XXINT"."XXINT_GL_I001_JOURNALS_STG" ("CURRENT_INSTANCE_ID", "LEDGER_NAME", "PERIOD_NAME", "TRANSACTION_DATE", "REFERENCE1", "REFERENCE4", "NS_SEGMENT1") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index XXINT_GL_I001_JOURNALS_STG_N3
--------------------------------------------------------

  CREATE INDEX "XXINT"."XXINT_GL_I001_JOURNALS_STG_N3" ON "XXINT"."XXINT_GL_I001_JOURNALS_STG" ("CURRENT_INSTANCE_ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index XXINT_GL_I001_JOURNALS_STG_N4
--------------------------------------------------------

  CREATE INDEX "XXINT"."XXINT_GL_I001_JOURNALS_STG_N4" ON "XXINT"."XXINT_GL_I001_JOURNALS_STG" ("NS_SEGMENT1", "NS_SEGMENT2", "NS_SEGMENT3", "NS_SEGMENT4", "NS_SEGMENT5", "NS_SEGMENT6", "NS_SEGMENT7", "NS_SEGMENT8", "NS_SEGMENT9", "NS_SEGMENT10") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index XXINT_GL_I001_JOURNALS_STG_N5
--------------------------------------------------------

  CREATE INDEX "XXINT"."XXINT_GL_I001_JOURNALS_STG_N5" ON "XXINT"."XXINT_GL_I001_JOURNALS_STG" ("LOAD_REQUEST_ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index XXINT_GL_I001_JOURNALS_STG_N6
--------------------------------------------------------

  CREATE INDEX "XXINT"."XXINT_GL_I001_JOURNALS_STG_N6" ON "XXINT"."XXINT_GL_I001_JOURNALS_STG" ("CURRENT_INSTANCE_ID", "STATUS") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
