  CREATE TABLE "XXINT"."XXINT_HCM_116_EMPLOYEES_DATA" 
   (	"PERSON_ID" NUMBER, 
	"PERSON_NUMBER" VARCHAR2(30 BYTE) , 
	"FIRST_NAME" VARCHAR2(150 BYTE) , 
	"LAST_NAME" VARCHAR2(150 BYTE) , 
	"ASSIGNMENT_NUMBER" VARCHAR2(50 BYTE) , 
	"ASSIGNMENT_ID" NUMBER, 
	"USER_NAME" VARCHAR2(150 BYTE) 
   );


  GRANT INSERT ON "XXINT"."XXINT_HCM_116_EMPLOYEES_DATA" TO "KSY_ATP_ADMIN";
  GRANT SELECT ON "XXINT"."XXINT_HCM_116_EMPLOYEES_DATA" TO "KSY_ATP_ADMIN";
  GRANT UPDATE ON "XXINT"."XXINT_HCM_116_EMPLOYEES_DATA" TO "KSY_ATP_ADMIN";
  GRANT INSERT ON "XXINT"."XXINT_HCM_116_EMPLOYEES_DATA" TO "KSY_ATP_DEVELOPER";
  GRANT SELECT ON "XXINT"."XXINT_HCM_116_EMPLOYEES_DATA" TO "KSY_ATP_DEVELOPER";
  GRANT SELECT ON "XXINT"."XXINT_HCM_116_EMPLOYEES_DATA" TO "KSY_ATP_INQUIRER";
