
  CREATE TABLE "XXINT"."XXINT_HCM_MULE_EMP_DATA" 
   (	"PERSON_ID" NUMBER, 
	"PERSON_NUMBER" VARCHAR2(100 BYTE) , 
	"PERSON_IMAGE_ID" NUMBER, 
	"CREATION_DATE" DATE, 
	"CREATED_BY" VARCHAR2(200 BYTE) , 
	"LAST_UPDATE_DATE" DATE, 
	"LAST_UPDATED_BY" VARCHAR2(200 BYTE) , 
	 PRIMARY KEY ("PERSON_ID")
   )  ;


  GRANT INSERT ON "XXINT"."XXINT_HCM_MULE_EMP_DATA" TO "KSY_ATP_ADMIN";
  GRANT SELECT ON "XXINT"."XXINT_HCM_MULE_EMP_DATA" TO "KSY_ATP_ADMIN";
  GRANT UPDATE ON "XXINT"."XXINT_HCM_MULE_EMP_DATA" TO "KSY_ATP_ADMIN";
  GRANT INSERT ON "XXINT"."XXINT_HCM_MULE_EMP_DATA" TO "KSY_ATP_DEVELOPER";
  GRANT SELECT ON "XXINT"."XXINT_HCM_MULE_EMP_DATA" TO "KSY_ATP_DEVELOPER";
  GRANT SELECT ON "XXINT"."XXINT_HCM_MULE_EMP_DATA" TO "KSY_ATP_INQUIRER";
