/*****************************************************************
OBJECT NAME: XXINT_XX_I010_ERROR_DETAILS_LOG & XXINT_XX_I010_ERROR_DETAILS_LOG_N1
DESCRIPTION: Common Error Detail Table and index
VERSION 	NAME              	DATE           			VERSION-DESCRIPTION
----------------------------------------------------------------------------
<1.0>		Kunjesh   			18-Feb-2025    			1.0- INITIAL DRAFT
******************************************************************/ 
  CREATE TABLE "XXINT"."XXINT_XX_I010_ERROR_DETAILS_LOG" 
   (
   "INTERFACE_RICE_ID" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"INTEGRATION_NAME" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"PARENT_PROCESS_ID" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"CURRENT_PROCESS_ID" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"STATUS" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"LOCATION" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"ERROR_CODE" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"ERROR_SUMMARY" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"ERROR_DETAILS" CLOB COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE1" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE2" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE3" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE4" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE5" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE6" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE7" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE8" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE9" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE10" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE_NUMBER1" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE_NUMBER2" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE_NUMBER3" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE_NUMBER4" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE_NUMBER5" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE_CLOB1" CLOB COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE_CLOB2" CLOB COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE_CLOB3" CLOB COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE_CLOB4" CLOB COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE_CLOB5" CLOB COLLATE "USING_NLS_COMP", 
	"CREATED_BY" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'ATP', 
	"CREATION_DATE" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP" DEFAULT to_char(sysdate, 'YYYY-MM-DD HH24:MI:SS'), 
	"LAST_UPDATED_BY" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'ATP', 
	"LAST_UPDATE_DATE" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP" DEFAULT to_char(sysdate, 'YYYY-MM-DD HH24:MI:SS')
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" 
 LOB ("ERROR_DETAILS") STORE AS SECUREFILE (
  TABLESPACE "DATA" ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 262144 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("ATTRIBUTE_CLOB1") STORE AS SECUREFILE (
  TABLESPACE "DATA" ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 262144 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("ATTRIBUTE_CLOB2") STORE AS SECUREFILE (
  TABLESPACE "DATA" ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 262144 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("ATTRIBUTE_CLOB3") STORE AS SECUREFILE (
  TABLESPACE "DATA" ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 262144 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("ATTRIBUTE_CLOB4") STORE AS SECUREFILE (
  TABLESPACE "DATA" ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 262144 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("ATTRIBUTE_CLOB5") STORE AS SECUREFILE (
  TABLESPACE "DATA" ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 262144 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

  CREATE INDEX "XXINT"."XXINT_XX_I010_ERROR_DETAILS_LOG_N1" ON "XXINT"."XXINT_XX_I010_ERROR_DETAILS_LOG" ("INTERFACE_RICE_ID", "PARENT_PROCESS_ID", "CURRENT_PROCESS_ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;