CREATE TABLE xxint.xxint_po_i030_po_header_tbl (
    "XXINT_PO_SEQ_ID"        NUMBER
        GENERATED BY DEFAULT ON NULL AS IDENTITY,
    "OIC_BATCH_ID"           VARCHAR2(250 BYTE),
    "ERP_PO_NUM"             VARCHAR2(250 BYTE),
    "ERP_PO_ID"              NUMBER,
    "SUPPLIER_NAME"          VARCHAR2(250 BYTE),
    "SUPPLIER_ID"            VARCHAR2(250 BYTE),
    "BUYER_NUM"              NUMBER,
    "REQUESTOR_NUM"          NUMBER,
    "PO_CREATION_DATE"       DATE,
    "REQUISITION_BU"         VARCHAR2(250 BYTE),
    "PROCUREMENT_BU"         VARCHAR2(250 BYTE),
    "DEPARTMENT"             VARCHAR2(250 BYTE),
    "CURRENCY"               VARCHAR2(250 BYTE),
    "MEMO"                   VARCHAR2(25000 BYTE),
    "SHIP_TO_LOCATION"       VARCHAR2(250 BYTE),
    "SHIP_TO_LOCATION_ID"    NUMBER,
    "LASTRUNDATETIME_PARM"   VARCHAR2(50 BYTE),
    "NS_PO_NUM"              VARCHAR2(250 BYTE),
    "NS_PO_ID"               VARCHAR2(250 BYTE),
    "STATUS"                 VARCHAR2(250 BYTE),
    "MESSAGE"                VARCHAR2(5000 BYTE),
    "CREATION_DATE"          DATE,
    "CREATED_BY"             VARCHAR2(250 BYTE),
    "LAST_UPDATE_DATE"       DATE,
    "LAST_UPDATED_BY"        VARCHAR2(250 BYTE),
    "ACTION_TYPE"            VARCHAR2(20 BYTE),
    "BU_NAME"                VARCHAR2(250 BYTE),
    "HEADER_DOCUMENT_STATUS" VARCHAR2(20 BYTE),
    "SOLD_TO_LE_NAME"        VARCHAR2(250 BYTE)
);

CREATE INDEX xxint_po_i030_po_header_tbl_n1 ON
    xxint.xxint_po_i030_po_header_tbl (
        erp_po_num
    );