/*****************************************************************
OBJECT NAME: XXINT_XX_I010_DB_EXECUTION_LOG & XXINT_XX_I010_DB_EXECUTION_LOG_N1
DESCRIPTION: Common DB Execution details Table and index
VERSION 	NAME              	DATE           			VERSION-DESCRIPTION
----------------------------------------------------------------------------
<1.0>		Kunjesh   			18-Feb-2025    			1.0- INITIAL DRAFT
******************************************************************/ 
CREATE TABLE "XXINT"."XXINT_XX_I010_DB_EXECUTION_LOG" 
   (
   "INTERFACE_RICE_ID" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"INTEGRATION_NAME" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"PARENT_PROCESS_ID" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"CURRENT_PROCESS_ID" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"DB_OBJECT_NAME" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"MESSAGE" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE1" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE2" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE3" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE4" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE5" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"CREATED_BY" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'ATP', 
	"CREATION_DATE" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP" DEFAULT to_char(sysdate, 'YYYY-MM-DD HH24:MI:SS'), 
	"LAST_UPDATED_BY" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'ATP', 
	"LAST_UPDATE_DATE" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP" DEFAULT to_char(sysdate, 'YYYY-MM-DD HH24:MI:SS')
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "DATA" ;

  CREATE INDEX "XXINT"."XXINT_XX_I010_DB_EXECUTION_LOG_N1" ON "XXINT"."XXINT_XX_I010_DB_EXECUTION_LOG" ("INTERFACE_RICE_ID", "INTEGRATION_NAME", "CURRENT_PROCESS_ID", "DB_OBJECT_NAME") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "DATA" ;