CREATE TABLE "XXINT"."XXINT_HCM_101_ADP_US_DATA" 
   (	"OIC_INSTANCE_ID" VARCHAR2(100 BYTE) , 
	"PERSON_NUMBER" VARCHAR2(100 BYTE) , 
	"ACTION_CODE" VARCHAR2(100 BYTE) , 
	"STATUS" VARCHAR2(100 BYTE) , 
	"MESSAGE" VARCHAR2(2000 BYTE) , 
	"CREATION_DATE" DATE DEFAULT SYSDATE, 
	"CREATED_BY" VARCHAR2(100 BYTE) , 
	"LAST_UPDATE_DATE" DATE, 
	"LAST_UPDATED_BY" VARCHAR2(100 BYTE) , 
	 PRIMARY KEY ("PERSON_NUMBER")
   ) ;


  GRANT INSERT ON "XXINT"."XXINT_HCM_101_ADP_US_DATA" TO "KSY_ATP_ADMIN";
  GRANT SELECT ON "XXINT"."XXINT_HCM_101_ADP_US_DATA" TO "KSY_ATP_ADMIN";
  GRANT UPDATE ON "XXINT"."XXINT_HCM_101_ADP_US_DATA" TO "KSY_ATP_ADMIN";
  GRANT INSERT ON "XXINT"."XXINT_HCM_101_ADP_US_DATA" TO "KSY_ATP_DEVELOPER";
  GRANT SELECT ON "XXINT"."XXINT_HCM_101_ADP_US_DATA" TO "KSY_ATP_DEVELOPER";
  GRANT SELECT ON "XXINT"."XXINT_HCM_101_ADP_US_DATA" TO "KSY_ATP_INQUIRER";