 CREATE TABLE "XXINT"."XXINT_HCM_110_MOOREPAY_DATA_STATUS" 
   (	"OIC_INSTANCE_ID" VARCHAR2(100 BYTE) , 
	"PERSON_NUMBER" VARCHAR2(100 BYTE) , 
	"EVENT" VARCHAR2(50 BYTE) , 
	"STATUS" VARCHAR2(50 BYTE) , 
	"ERROR_MESSAGE" VARCHAR2(2000 BYTE) , 
	"CREATION_DATE" DATE, 
	"CREATED_BY" VARCHAR2(200 BYTE) , 
	"LAST_UPDATE_DATE" DATE, 
	"LAST_UPDATED_BY" VARCHAR2(200 BYTE) 
   ) ;


  GRANT INSERT ON "XXINT"."XXINT_HCM_110_MOOREPAY_DATA_STATUS" TO "KSY_ATP_ADMIN";
  GRANT SELECT ON "XXINT"."XXINT_HCM_110_MOOREPAY_DATA_STATUS" TO "KSY_ATP_ADMIN";
  GRANT UPDATE ON "XXINT"."XXINT_HCM_110_MOOREPAY_DATA_STATUS" TO "KSY_ATP_ADMIN";
  GRANT INSERT ON "XXINT"."XXINT_HCM_110_MOOREPAY_DATA_STATUS" TO "KSY_ATP_DEVELOPER";
  GRANT SELECT ON "XXINT"."XXINT_HCM_110_MOOREPAY_DATA_STATUS" TO "KSY_ATP_DEVELOPER";
  GRANT SELECT ON "XXINT"."XXINT_HCM_110_MOOREPAY_DATA_STATUS" TO "KSY_ATP_INQUIRER";
