--------------------------------------------------------
--  File created - Thursday-July-24-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table XXINT_AP_I017_KYRIBA_PAYMENTS_ACK_STG
--------------------------------------------------------

  CREATE TABLE "XXINT"."XXINT_AP_I017_KYRIBA_PAYMENTS_ACK_STG" 
   (	"INTERFACE_RICE_ID" VARCHAR2(250 BYTE) COLLATE "USING_NLS_COMP", 
	"INTERFACE_RICE_NAME" VARCHAR2(250 BYTE) COLLATE "USING_NLS_COMP", 
	"PARENT_INSTANCE_ID" VARCHAR2(250 BYTE) COLLATE "USING_NLS_COMP", 
	"CURRENT_INSTANCE_ID" VARCHAR2(250 BYTE) COLLATE "USING_NLS_COMP", 
	"BATCH_ID" VARCHAR2(250 BYTE) COLLATE "USING_NLS_COMP", 
	"TASK_ID" VARCHAR2(250 BYTE) COLLATE "USING_NLS_COMP", 
	"TASK_STATUS" VARCHAR2(250 BYTE) COLLATE "USING_NLS_COMP", 
	"REFERENCE" VARCHAR2(250 BYTE) COLLATE "USING_NLS_COMP", 
	"REMITTANCE_IDENTIFIER_1" VARCHAR2(250 BYTE) COLLATE "USING_NLS_COMP", 
	"TRANSACTION_NUMBER" VARCHAR2(250 BYTE) COLLATE "USING_NLS_COMP", 
	"REMITTANCE_NUMBER" VARCHAR2(250 BYTE) COLLATE "USING_NLS_COMP", 
	"TRANSACTION_STATUS" VARCHAR2(250 BYTE) COLLATE "USING_NLS_COMP", 
	"LAST_ACK_BANK_STATUS" VARCHAR2(250 BYTE) COLLATE "USING_NLS_COMP", 
	"LAST_ACK_DATE" VARCHAR2(250 BYTE) COLLATE "USING_NLS_COMP", 
	"LAST_ACK_TIME" VARCHAR2(250 BYTE) COLLATE "USING_NLS_COMP", 
	"LINK_ID_OUTSOURCE" VARCHAR2(250 BYTE) COLLATE "USING_NLS_COMP", 
	"REJECTION_REASON" VARCHAR2(250 BYTE) COLLATE "USING_NLS_COMP", 
	"PAYMENT_NUMBER" VARCHAR2(250 BYTE) COLLATE "USING_NLS_COMP", 
	"CHECK_ID" VARCHAR2(250 BYTE) COLLATE "USING_NLS_COMP", 
	"STATUS" VARCHAR2(250 BYTE) COLLATE "USING_NLS_COMP", 
	"MESSAGE" VARCHAR2(2000 BYTE) COLLATE "USING_NLS_COMP", 
	"CREATED_BY" VARCHAR2(250 BYTE) COLLATE "USING_NLS_COMP", 
	"CREATION_DATE" VARCHAR2(250 BYTE) COLLATE "USING_NLS_COMP", 
	"LAST_UPDATED_BY" VARCHAR2(250 BYTE) COLLATE "USING_NLS_COMP", 
	"LAST_UPDATE_DATE" VARCHAR2(250 BYTE) COLLATE "USING_NLS_COMP", 
	"CHUNK_ID" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
  GRANT SELECT ON "XXINT"."XXINT_AP_I017_KYRIBA_PAYMENTS_ACK_STG" TO "XXINT_RO";
--------------------------------------------------------
--  DDL for Index XXINT_AP_I017_KYRIBA_PAYMENTS_ACK_STG_N1
--------------------------------------------------------

  CREATE INDEX "XXINT"."XXINT_AP_I017_KYRIBA_PAYMENTS_ACK_STG_N1" ON "XXINT"."XXINT_AP_I017_KYRIBA_PAYMENTS_ACK_STG" ("CURRENT_INSTANCE_ID", "PARENT_INSTANCE_ID", "INTERFACE_RICE_ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index XXINT_AP_I017_KYRIBA_PAYMENTS_ACK_STG_N2
--------------------------------------------------------

  CREATE INDEX "XXINT"."XXINT_AP_I017_KYRIBA_PAYMENTS_ACK_STG_N2" ON "XXINT"."XXINT_AP_I017_KYRIBA_PAYMENTS_ACK_STG" ("BATCH_ID", "STATUS") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index XXINT_AP_I017_KYRIBA_PAYMENTS_ACK_STG_N3
--------------------------------------------------------

  CREATE INDEX "XXINT"."XXINT_AP_I017_KYRIBA_PAYMENTS_ACK_STG_N3" ON "XXINT"."XXINT_AP_I017_KYRIBA_PAYMENTS_ACK_STG" ("REFERENCE", "REMITTANCE_IDENTIFIER_1") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
