/*****************************************************************
OBJECT NAME: XXINT_XX_I010_UCM_UPLOAD_LOG & XXINT_XX_I010_UCM_UPLOAD_LOG_N1
DESCRIPTION: Common UCM Log Details Table and index
VERSION 	NAME              	DATE           			VERSION-DESCRIPTION
----------------------------------------------------------------------------
<1.0>		Kunjesh   			18-Feb-2025    			1.0- INITIAL DRAFT
******************************************************************/ 

  CREATE TABLE "XXINT"."XXINT_XX_I010_UCM_UPLOAD_LOG"
   ("INTERFACE_RICE_ID" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"INTEGRATION_NAME" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"RECORD_INDENTIFIER" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"PARENT_PROCESS_ID" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"CURRENT_PROCESS_ID" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"UCM_DOC_ID" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"UCM_FILE_NAME" VARCHAR2(400 BYTE) COLLATE "USING_NLS_COMP", 
	"TOTAL_ERROR_COUNT" NUMBER, 
	"PURGE_STATUS" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"PURGE_STATUS_MESSAGE" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE1" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE2" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE3" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE4" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE5" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE6" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE7" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE8" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE9" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE10" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE_NUMBER1" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE_NUMBER2" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE_NUMBER3" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE_NUMBER4" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE_NUMBER5" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE_CLOB1" CLOB COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE_CLOB2" CLOB COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE_CLOB3" CLOB COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE_CLOB4" CLOB COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE_CLOB5" CLOB COLLATE "USING_NLS_COMP", 
	"CREATION_DATE" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'ATP', 
	"CREATED_BY" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP" DEFAULT to_char(sysdate, 'YYYY-MM-DD HH24:MI:SS'), 
	"LAST_UPDATE_DATE" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'ATP', 
	"LAST_UPDATED_BY" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP" DEFAULT to_char(sysdate, 'YYYY-MM-DD HH24:MI:SS')
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "DATA" 
 LOB ("ATTRIBUTE_CLOB1") STORE AS SECUREFILE (
  TABLESPACE "DATA" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) 
 LOB ("ATTRIBUTE_CLOB2") STORE AS SECUREFILE (
  TABLESPACE "DATA" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) 
 LOB ("ATTRIBUTE_CLOB3") STORE AS SECUREFILE (
  TABLESPACE "DATA" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) 
 LOB ("ATTRIBUTE_CLOB4") STORE AS SECUREFILE (
  TABLESPACE "DATA" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) 
 LOB ("ATTRIBUTE_CLOB5") STORE AS SECUREFILE (
  TABLESPACE "DATA" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;

  CREATE INDEX "XXINT"."XXINT_XX_I010_UCM_UPLOAD_LOG_N1" ON "XXINT"."XXINT_XX_I010_UCM_UPLOAD_LOG"("UCM_DOC_ID", "CREATION_DATE") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "DATA" ;

