/*****************************************************************
OBJECT NAME: XXINT_XX_I010_AUDIT_LOG & XXINT_XX_I010_AUDIT_LOG_N1
DESCRIPTION: Common Audit Table and index
VERSION 	NAME              	DATE           			VERSION-DESCRIPTION
----------------------------------------------------------------------------
<1.0>		Kunjesh   			18-Feb-2025    			1.0- INITIAL DRAFT
******************************************************************/ 

  CREATE TABLE "XXINT"."XXINT_XX_I010_AUDIT_LOG" 
   (
   "INTERFACE_RICE_ID" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"INTERFACE_RICE_NAME" VARCHAR2(1000 BYTE) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"LOG_FLAG" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"NOTIFY_FLAG" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"PARENT_PROCESS_ID" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"CURRENT_PROCESS_ID" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"STATUS" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"IS_FINAL_PROCESS" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"INTEGRATION_NAME" VARCHAR2(1000 BYTE) COLLATE "USING_NLS_COMP", 
	"INTEGRATION_VERSION" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"INVOKED_BY" VARCHAR2(1000 BYTE) COLLATE "USING_NLS_COMP", 
	"INSTANCE" VARCHAR2(400 BYTE) COLLATE "USING_NLS_COMP", 
	"PROCESS_START_TIME" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"PROCESS_END_TIME" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"BUSINESS_INDETIFIER_KEY" VARCHAR2(1000 BYTE) COLLATE "USING_NLS_COMP", 
	"BUSINESS_INDETIFIER_VALUE" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"STAGE" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"SOURCE" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"TARGET" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"SOURCE_FILE_NAME" VARCHAR2(400 BYTE) COLLATE "USING_NLS_COMP", 
	"SOURCE_FILE_PATH" VARCHAR2(1000 BYTE) COLLATE "USING_NLS_COMP", 
	"SOURCE_FILE_CHECKSUM" VARCHAR2(400 BYTE) COLLATE "USING_NLS_COMP", 
	"INTEGRATION_REQUEST_PAYLOAD" CLOB COLLATE "USING_NLS_COMP", 
	"INTEGRATION_RESPONSE_PAYLOAD" CLOB COLLATE "USING_NLS_COMP", 
	"ACTIVITY_STREAM_FLAG" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"ACTIVITY_STREAM" CLOB COLLATE "USING_NLS_COMP", 
	"ORACLE_PROCESS_NAME" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"ORACLE_PROCESS_ID" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"IS_FBDI_PROCESS" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"ENABLED_CALLBACK" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"UCM_UPLOAD_REQUEST_ID" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"UCM_UPLOAD_STATUS" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"LOAD_REQUEST_ID" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"LOAD_REQUEST_STATUS" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"IMPORT_REQUEST_ID" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"IMPORT_REQUEST_STATUS" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"CALLBACK_RECEIVED" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"FILE_COUNT" NUMBER, 
	"TOTAL_BATCH_COUNT" NUMBER, 
	"TOTAL_ROW_COUNT" NUMBER, 
	"TOTAL_SUCCESS_COUNT" NUMBER, 
	"TOTAL_ERROR_COUNT" NUMBER, 
	"HEADER_ERROR_CODE" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"HEADER_ERROR_SUMMARY" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"HEADER_ERROR_DETAILS" CLOB COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE1" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE2" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE3" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE4" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE5" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE6" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE7" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE8" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE9" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE10" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE_NUMBER1" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE_NUMBER2" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE_NUMBER3" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE_NUMBER4" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE_NUMBER5" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE_CLOB1" CLOB COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE_CLOB2" CLOB COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE_CLOB3" CLOB COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE_CLOB4" CLOB COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE_CLOB5" CLOB COLLATE "USING_NLS_COMP", 
	"MANUALLY_CLOSED" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"MANUAL_CLOSURE_REASON" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"CREATION_DATE" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'ATP', 
	"CREATED_BY" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP" DEFAULT to_char(sysdate, 'YYYY-MM-DD HH24:MI:SS'), 
	"LAST_UPDATED_BY" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'ATP', 
	"LAST_UPDATE_DATE" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP" DEFAULT to_char(sysdate, 'YYYY-MM-DD HH24:MI:SS')
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" 
 LOB ("INTEGRATION_REQUEST_PAYLOAD") STORE AS SECUREFILE (
  TABLESPACE "DATA" ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 262144 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("INTEGRATION_RESPONSE_PAYLOAD") STORE AS SECUREFILE (
  TABLESPACE "DATA" ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 262144 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("ACTIVITY_STREAM") STORE AS SECUREFILE (
  TABLESPACE "DATA" ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 262144 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("HEADER_ERROR_DETAILS") STORE AS SECUREFILE (
  TABLESPACE "DATA" ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 262144 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("ATTRIBUTE_CLOB1") STORE AS SECUREFILE (
  TABLESPACE "DATA" ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 262144 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("ATTRIBUTE_CLOB2") STORE AS SECUREFILE (
  TABLESPACE "DATA" ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 262144 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("ATTRIBUTE_CLOB3") STORE AS SECUREFILE (
  TABLESPACE "DATA" ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 262144 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("ATTRIBUTE_CLOB4") STORE AS SECUREFILE (
  TABLESPACE "DATA" ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 262144 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("ATTRIBUTE_CLOB5") STORE AS SECUREFILE (
  TABLESPACE "DATA" ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 262144 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

  CREATE INDEX "XXINT"."XXINT_XX_I010_AUDIT_LOG_N1" ON "XXINT"."XXINT_XX_I010_AUDIT_LOG" ("INTERFACE_RICE_ID", "PARENT_PROCESS_ID", "CURRENT_PROCESS_ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
