--------------------------------------------------------
--  File created on Tuesday-September-23-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table XXINT_XX_I010_COMMON_RICE_OBJECTS_REF
--------------------------------------------------------

  CREATE TABLE "XXINT"."XXINT_XX_I010_COMMON_RICE_OBJECTS_REF" 
   (	"SR_NUMBER" NUMBER DEFAULT XXINT.XXINT_XX_I010_common_rice_objects_seq.NEXTVAL, 
	"INTERFACE_RICE_ID" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"TABLE_OWNER" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"ATP_DB_PURGE_FLAG" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP", 
	"ATP_DB_PURGE_FREQ_DAYS" NUMBER, 
	"TABLE_NAME" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"ARC_TABLE_OWNER" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"ARC_TABLE_NAME" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"ARC_FLAG" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE1" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE2" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE3" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE4" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE5" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE6" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE7" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE8" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE9" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE10" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"LAST_ATP_DB_PURGE_DATE" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"CREATED_BY" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'ATP', 
	"CREATION_DATE" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP" DEFAULT to_char(sysdate, 'YYYY-MM-DD HH24:MI:SS'), 
	"LAST_UPDATED_BY" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'ATP', 
	"LAST_UPDATE_DATE" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP" DEFAULT to_char(sysdate, 'YYYY-MM-DD HH24:MI:SS'), 
	"TBL_CREATION_DATE_FORMAT" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
  GRANT SELECT ON "XXINT"."XXINT_XX_I010_COMMON_RICE_OBJECTS_REF" TO "XX_RO";
  GRANT SELECT ON "XXINT"."XXINT_XX_I010_COMMON_RICE_OBJECTS_REF" TO "XXRO";
REM INSERTING into XXINT.XXINT_XX_I010_COMMON_RICE_OBJECTS_REF
SET DEFINE OFF;
Insert into XXINT.XXINT_XX_I010_COMMON_RICE_OBJECTS_REF (SR_NUMBER,INTERFACE_RICE_ID,TABLE_OWNER,ATP_DB_PURGE_FLAG,ATP_DB_PURGE_FREQ_DAYS,TABLE_NAME,ARC_TABLE_OWNER,ARC_TABLE_NAME,ARC_FLAG,ATTRIBUTE1,ATTRIBUTE2,ATTRIBUTE3,ATTRIBUTE4,ATTRIBUTE5,ATTRIBUTE6,ATTRIBUTE7,ATTRIBUTE8,ATTRIBUTE9,ATTRIBUTE10,LAST_ATP_DB_PURGE_DATE,CREATED_BY,CREATION_DATE,LAST_UPDATED_BY,LAST_UPDATE_DATE,TBL_CREATION_DATE_FORMAT) values (5,'GL_I008','XXINT','Y',60,'XXINT_GL_I008_CONCUR_ACC_JOURNALS_STG','XXINT','XXINT_GL_I008_CONCUR_ACC_JOURNALS_STG_ARC','Y','10000',null,null,null,null,null,null,null,null,null,null,'ATP','2025-09-08 10:49:23','ATP','2025-09-08 10:49:23','YYYY-MM-DD');
Insert into XXINT.XXINT_XX_I010_COMMON_RICE_OBJECTS_REF (SR_NUMBER,INTERFACE_RICE_ID,TABLE_OWNER,ATP_DB_PURGE_FLAG,ATP_DB_PURGE_FREQ_DAYS,TABLE_NAME,ARC_TABLE_OWNER,ARC_TABLE_NAME,ARC_FLAG,ATTRIBUTE1,ATTRIBUTE2,ATTRIBUTE3,ATTRIBUTE4,ATTRIBUTE5,ATTRIBUTE6,ATTRIBUTE7,ATTRIBUTE8,ATTRIBUTE9,ATTRIBUTE10,LAST_ATP_DB_PURGE_DATE,CREATED_BY,CREATION_DATE,LAST_UPDATED_BY,LAST_UPDATE_DATE,TBL_CREATION_DATE_FORMAT) values (6,'GL_I008','XXINT','Y',360,'XXINT_GL_I008_CONCUR_ACC_JOURNALS_STG_ARC','XXINT',null,'N','10000',null,null,null,null,null,null,null,null,null,null,'ATP','2025-09-08 10:49:23','ATP','2025-09-08 10:49:23','YYYY-MM-DD');
Insert into XXINT.XXINT_XX_I010_COMMON_RICE_OBJECTS_REF (SR_NUMBER,INTERFACE_RICE_ID,TABLE_OWNER,ATP_DB_PURGE_FLAG,ATP_DB_PURGE_FREQ_DAYS,TABLE_NAME,ARC_TABLE_OWNER,ARC_TABLE_NAME,ARC_FLAG,ATTRIBUTE1,ATTRIBUTE2,ATTRIBUTE3,ATTRIBUTE4,ATTRIBUTE5,ATTRIBUTE6,ATTRIBUTE7,ATTRIBUTE8,ATTRIBUTE9,ATTRIBUTE10,LAST_ATP_DB_PURGE_DATE,CREATED_BY,CREATION_DATE,LAST_UPDATED_BY,LAST_UPDATE_DATE,TBL_CREATION_DATE_FORMAT) values (7,'AP_I017','XXINT','Y',60,'XXINT_AP_I017_KYRIBA_PAYMENTS_ACK_STG','XXINT','XXINT_AP_I017_KYRIBA_PAYMENTS_ACK_STG_ARC','Y','10000',null,null,null,null,null,null,null,null,null,null,'ATP','2025-09-08 10:49:23','ATP','2025-09-08 10:49:23','YYYY-MM-DD');
Insert into XXINT.XXINT_XX_I010_COMMON_RICE_OBJECTS_REF (SR_NUMBER,INTERFACE_RICE_ID,TABLE_OWNER,ATP_DB_PURGE_FLAG,ATP_DB_PURGE_FREQ_DAYS,TABLE_NAME,ARC_TABLE_OWNER,ARC_TABLE_NAME,ARC_FLAG,ATTRIBUTE1,ATTRIBUTE2,ATTRIBUTE3,ATTRIBUTE4,ATTRIBUTE5,ATTRIBUTE6,ATTRIBUTE7,ATTRIBUTE8,ATTRIBUTE9,ATTRIBUTE10,LAST_ATP_DB_PURGE_DATE,CREATED_BY,CREATION_DATE,LAST_UPDATED_BY,LAST_UPDATE_DATE,TBL_CREATION_DATE_FORMAT) values (8,'AP_I017','XXINT','Y',360,'XXINT_AP_I017_KYRIBA_PAYMENTS_ACK_STG_ARC','XXINT',null,'N','10000',null,null,null,null,null,null,null,null,null,null,'ATP','2025-09-08 10:49:23','ATP','2025-09-08 10:49:23','YYYY-MM-DD');
Insert into XXINT.XXINT_XX_I010_COMMON_RICE_OBJECTS_REF (SR_NUMBER,INTERFACE_RICE_ID,TABLE_OWNER,ATP_DB_PURGE_FLAG,ATP_DB_PURGE_FREQ_DAYS,TABLE_NAME,ARC_TABLE_OWNER,ARC_TABLE_NAME,ARC_FLAG,ATTRIBUTE1,ATTRIBUTE2,ATTRIBUTE3,ATTRIBUTE4,ATTRIBUTE5,ATTRIBUTE6,ATTRIBUTE7,ATTRIBUTE8,ATTRIBUTE9,ATTRIBUTE10,LAST_ATP_DB_PURGE_DATE,CREATED_BY,CREATION_DATE,LAST_UPDATED_BY,LAST_UPDATE_DATE,TBL_CREATION_DATE_FORMAT) values (9,'GL_I018','XXINT','Y',60,'XXINT_GL_I018_CONCUR_JOURNALS_STG','XXINT','XXINT_GL_I018_CONCUR_JOURNALS_STG_ARC','Y','10000',null,null,null,null,null,null,null,null,null,null,'ATP','2025-09-08 10:49:23','ATP','2025-09-08 10:49:23','YYYY-MM-DD');
Insert into XXINT.XXINT_XX_I010_COMMON_RICE_OBJECTS_REF (SR_NUMBER,INTERFACE_RICE_ID,TABLE_OWNER,ATP_DB_PURGE_FLAG,ATP_DB_PURGE_FREQ_DAYS,TABLE_NAME,ARC_TABLE_OWNER,ARC_TABLE_NAME,ARC_FLAG,ATTRIBUTE1,ATTRIBUTE2,ATTRIBUTE3,ATTRIBUTE4,ATTRIBUTE5,ATTRIBUTE6,ATTRIBUTE7,ATTRIBUTE8,ATTRIBUTE9,ATTRIBUTE10,LAST_ATP_DB_PURGE_DATE,CREATED_BY,CREATION_DATE,LAST_UPDATED_BY,LAST_UPDATE_DATE,TBL_CREATION_DATE_FORMAT) values (10,'GL_I018','XXINT','Y',360,'XXINT_GL_I018_CONCUR_JOURNALS_STG_ARC','XXINT',null,'N','10000',null,null,null,null,null,null,null,null,null,null,'ATP','2025-09-08 10:49:23','ATP','2025-09-08 10:49:23','YYYY-MM-DD');
Insert into XXINT.XXINT_XX_I010_COMMON_RICE_OBJECTS_REF (SR_NUMBER,INTERFACE_RICE_ID,TABLE_OWNER,ATP_DB_PURGE_FLAG,ATP_DB_PURGE_FREQ_DAYS,TABLE_NAME,ARC_TABLE_OWNER,ARC_TABLE_NAME,ARC_FLAG,ATTRIBUTE1,ATTRIBUTE2,ATTRIBUTE3,ATTRIBUTE4,ATTRIBUTE5,ATTRIBUTE6,ATTRIBUTE7,ATTRIBUTE8,ATTRIBUTE9,ATTRIBUTE10,LAST_ATP_DB_PURGE_DATE,CREATED_BY,CREATION_DATE,LAST_UPDATED_BY,LAST_UPDATE_DATE,TBL_CREATION_DATE_FORMAT) values (11,'GL_I020','XXINT','Y',60,'XXINT_GL_I020_KYRIBA_JOURNALS_STG','XXINT','XXINT_GL_I020_KYRIBA_JOURNALS_STG_ARC','Y','10000',null,null,null,null,null,null,null,null,null,'2025-08-25 12:35:35','ATP','2025-08-12 10:51:05','ATP','2025-08-12 10:51:05','DD-MON-YY');
Insert into XXINT.XXINT_XX_I010_COMMON_RICE_OBJECTS_REF (SR_NUMBER,INTERFACE_RICE_ID,TABLE_OWNER,ATP_DB_PURGE_FLAG,ATP_DB_PURGE_FREQ_DAYS,TABLE_NAME,ARC_TABLE_OWNER,ARC_TABLE_NAME,ARC_FLAG,ATTRIBUTE1,ATTRIBUTE2,ATTRIBUTE3,ATTRIBUTE4,ATTRIBUTE5,ATTRIBUTE6,ATTRIBUTE7,ATTRIBUTE8,ATTRIBUTE9,ATTRIBUTE10,LAST_ATP_DB_PURGE_DATE,CREATED_BY,CREATION_DATE,LAST_UPDATED_BY,LAST_UPDATE_DATE,TBL_CREATION_DATE_FORMAT) values (12,'GL_I020','XXINT','Y',360,'XXINT_GL_I020_KYRIBA_JOURNALS_STG_ARC','XXINT',null,'N','10000',null,null,null,null,null,null,null,null,null,'2025-08-25 12:35:35','ATP','2025-08-12 10:52:33','ATP','2025-08-12 10:52:33','DD-MON-YY');
Insert into XXINT.XXINT_XX_I010_COMMON_RICE_OBJECTS_REF (SR_NUMBER,INTERFACE_RICE_ID,TABLE_OWNER,ATP_DB_PURGE_FLAG,ATP_DB_PURGE_FREQ_DAYS,TABLE_NAME,ARC_TABLE_OWNER,ARC_TABLE_NAME,ARC_FLAG,ATTRIBUTE1,ATTRIBUTE2,ATTRIBUTE3,ATTRIBUTE4,ATTRIBUTE5,ATTRIBUTE6,ATTRIBUTE7,ATTRIBUTE8,ATTRIBUTE9,ATTRIBUTE10,LAST_ATP_DB_PURGE_DATE,CREATED_BY,CREATION_DATE,LAST_UPDATED_BY,LAST_UPDATE_DATE,TBL_CREATION_DATE_FORMAT) values (3,'GL_I003','XXINT','Y',60,'XXINT_GL_I003_ADP_JOURNALS_STG','XXINT','XXINT_GL_I003_ADP_JOURNALS_STG_ARC','Y','10000',null,null,null,null,null,null,null,null,null,null,'ATP','2025-09-08 10:49:23','ATP','2025-09-08 10:49:23','YYYY-MM-DD');
Insert into XXINT.XXINT_XX_I010_COMMON_RICE_OBJECTS_REF (SR_NUMBER,INTERFACE_RICE_ID,TABLE_OWNER,ATP_DB_PURGE_FLAG,ATP_DB_PURGE_FREQ_DAYS,TABLE_NAME,ARC_TABLE_OWNER,ARC_TABLE_NAME,ARC_FLAG,ATTRIBUTE1,ATTRIBUTE2,ATTRIBUTE3,ATTRIBUTE4,ATTRIBUTE5,ATTRIBUTE6,ATTRIBUTE7,ATTRIBUTE8,ATTRIBUTE9,ATTRIBUTE10,LAST_ATP_DB_PURGE_DATE,CREATED_BY,CREATION_DATE,LAST_UPDATED_BY,LAST_UPDATE_DATE,TBL_CREATION_DATE_FORMAT) values (4,'GL_I003','XXINT','Y',360,'XXINT_GL_I003_ADP_JOURNALS_STG_ARC','XXINT',null,'N','10000',null,null,null,null,null,null,null,null,null,null,'ATP','2025-09-08 10:49:23','ATP','2025-09-08 10:49:23','YYYY-MM-DD');
Insert into XXINT.XXINT_XX_I010_COMMON_RICE_OBJECTS_REF (SR_NUMBER,INTERFACE_RICE_ID,TABLE_OWNER,ATP_DB_PURGE_FLAG,ATP_DB_PURGE_FREQ_DAYS,TABLE_NAME,ARC_TABLE_OWNER,ARC_TABLE_NAME,ARC_FLAG,ATTRIBUTE1,ATTRIBUTE2,ATTRIBUTE3,ATTRIBUTE4,ATTRIBUTE5,ATTRIBUTE6,ATTRIBUTE7,ATTRIBUTE8,ATTRIBUTE9,ATTRIBUTE10,LAST_ATP_DB_PURGE_DATE,CREATED_BY,CREATION_DATE,LAST_UPDATED_BY,LAST_UPDATE_DATE,TBL_CREATION_DATE_FORMAT) values (1,'GL_I001','XXINT','Y',60,'XXINT_GL_I001_JOURNALS_STG','XXINT','XXINT_GL_I001_JOURNALS_STG_ARC','Y','10000',null,null,null,null,null,null,null,null,null,'2025-08-25 12:35:35','ATP','2025-09-08 10:49:23','ATP','2025-09-08 10:49:23','YYYY-MM-DD');
Insert into XXINT.XXINT_XX_I010_COMMON_RICE_OBJECTS_REF (SR_NUMBER,INTERFACE_RICE_ID,TABLE_OWNER,ATP_DB_PURGE_FLAG,ATP_DB_PURGE_FREQ_DAYS,TABLE_NAME,ARC_TABLE_OWNER,ARC_TABLE_NAME,ARC_FLAG,ATTRIBUTE1,ATTRIBUTE2,ATTRIBUTE3,ATTRIBUTE4,ATTRIBUTE5,ATTRIBUTE6,ATTRIBUTE7,ATTRIBUTE8,ATTRIBUTE9,ATTRIBUTE10,LAST_ATP_DB_PURGE_DATE,CREATED_BY,CREATION_DATE,LAST_UPDATED_BY,LAST_UPDATE_DATE,TBL_CREATION_DATE_FORMAT) values (2,'GL_I001','XXINT','Y',360,'XXINT_GL_I001_JOURNALS_STG_ARC','XXINT',null,'N','10000',null,null,null,null,null,null,null,null,null,'2025-08-25 12:35:35','ATP','2025-09-08 10:49:23','ATP','2025-09-08 10:49:23','YYYY-MM-DD');
commit;
--------------------------------------------------------
--  DDL for Index XXINT_XX_I010_COMMON_RICE_OBJECTS_REF_IDX1
--------------------------------------------------------

  CREATE UNIQUE INDEX "XXINT"."XXINT_XX_I010_COMMON_RICE_OBJECTS_REF_IDX1" ON "XXINT"."XXINT_XX_I010_COMMON_RICE_OBJECTS_REF" ("SR_NUMBER") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  Constraints for Table XXINT_XX_I010_COMMON_RICE_OBJECTS_REF
--------------------------------------------------------

  ALTER TABLE "XXINT"."XXINT_XX_I010_COMMON_RICE_OBJECTS_REF" MODIFY ("SR_NUMBER" NOT NULL ENABLE);
