
  CREATE TABLE "XXINT"."XXINT_HCM_116_GREENHOUSE_INBOUND" 
   (	"OFFERID" NUMBER, 
	"ORACLEPERSONNUMBER" NUMBER, 
	"ACTIONCODE" VARCHAR2(30 BYTE), 
	"FIRSTNAME" VARCHAR2(150 BYTE), 
	"LASTNAME" VARCHAR2(150 BYTE), 
	"CREATEPENDINGWORKERSTATUS" VARCHAR2(10 BYTE), 
	"CREATEPENDINGWORKERERROR" VARCHAR2(4000 BYTE), 
	"ADDSALARYSTATUS" VARCHAR2(10 BYTE), 
	"ADDSALARYERROR" VARCHAR2(4000 BYTE), 
	"ADDELEMENTENTRIESSTATUS" VARCHAR2(10 BYTE), 
	"ADDELEMENTENTRIESERROR" VARCHAR2(4000 BYTE), 
	"CREATEDORSTATUS" VARCHAR2(10 BYTE), 
	"CREATEDORERROR" VARCHAR2(4000 BYTE), 
	"ADDATTACHMENTSTATUS" VARCHAR2(10 BYTE), 
	"ADDATTACHMENTERROR" VARCHAR2(4000 BYTE), 
	"FINALSTATUS" VARCHAR2(10 BYTE), 
	"CREATED_DATE" DATE DEFAULT SYSDATE, 
	"CREATED_BY" VARCHAR2(150 BYTE), 
	"LAST_UPDATED_DATE" DATE, 
	"LAST_UPDATED_BY" VARCHAR2(150 BYTE), 
	"CANDIDATEID" NUMBER, 
	"EMPLOYMENTTYPE" VARCHAR2(150 BYTE), 
	 CONSTRAINT "OFFIER_ID" PRIMARY KEY ("OFFERID")
   )  ;



  GRANT INSERT ON "XXINT"."XXINT_HCM_116_GREENHOUSE_INBOUND" TO "KSY_ATP_ADMIN";
  GRANT SELECT ON "XXINT"."XXINT_HCM_116_GREENHOUSE_INBOUND" TO "KSY_ATP_ADMIN";
  GRANT UPDATE ON "XXINT"."XXINT_HCM_116_GREENHOUSE_INBOUND" TO "KSY_ATP_ADMIN";
  GRANT INSERT ON "XXINT"."XXINT_HCM_116_GREENHOUSE_INBOUND" TO "KSY_ATP_DEVELOPER";
  GRANT SELECT ON "XXINT"."XXINT_HCM_116_GREENHOUSE_INBOUND" TO "KSY_ATP_DEVELOPER";
  GRANT SELECT ON "XXINT"."XXINT_HCM_116_GREENHOUSE_INBOUND" TO "KSY_ATP_INQUIRER";
