
  CREATE TABLE "XXINT"."XXINT_HCM_116_GREENHOUSE_LOCATION_MAPPING_UDT" 
   (	"STG_ID" NUMBER DEFAULT "XXINT"."XXINT_HCM_116_GREENHOUSE_UDT_SEQ"."NEXTVAL", 
	"OIC_RUN_ID" VARCHAR2(200 BYTE) , 
	"USER_TABLE" VARCHAR2(150 BYTE) , 
	"COLUMN_NAME" VARCHAR2(150 BYTE) , 
	"WORK_LOCATION" VARCHAR2(150 BYTE) , 
	"EFFECTIVE_START_DATE" DATE, 
	"EFFECTIVE_END_DATE" DATE, 
	"VALUE" VARCHAR2(150 BYTE) , 
	"LAST_UPDATED_BY" VARCHAR2(150 BYTE) , 
	"CREATION_DATE" DATE, 
	"CREATED_BY" VARCHAR2(150 BYTE) , 
	"LAST_UPDATE_DATE" DATE
   ) ;


  GRANT INSERT ON "XXINT"."XXINT_HCM_116_GREENHOUSE_LOCATION_MAPPING_UDT" TO "KSY_ATP_ADMIN";
  GRANT SELECT ON "XXINT"."XXINT_HCM_116_GREENHOUSE_LOCATION_MAPPING_UDT" TO "KSY_ATP_ADMIN";
  GRANT UPDATE ON "XXINT"."XXINT_HCM_116_GREENHOUSE_LOCATION_MAPPING_UDT" TO "KSY_ATP_ADMIN";
  GRANT INSERT ON "XXINT"."XXINT_HCM_116_GREENHOUSE_LOCATION_MAPPING_UDT" TO "KSY_ATP_DEVELOPER";
  GRANT SELECT ON "XXINT"."XXINT_HCM_116_GREENHOUSE_LOCATION_MAPPING_UDT" TO "KSY_ATP_DEVELOPER";
  GRANT SELECT ON "XXINT"."XXINT_HCM_116_GREENHOUSE_LOCATION_MAPPING_UDT" TO "KSY_ATP_INQUIRER";
