  CREATE TABLE XXMAP.XXMAP_GL_E001_KASEYA_NS_FUTURE1

  (
    "MAPPING_SET_VALUE_ID" NUMBER PRIMARY KEY,
    "MAPPING_SET_CODE"         VARCHAR2(50),
    "ERP_COA_VALUE"                NUMBER,
    "NS_FUTURE1_ATTRIBUTE_1"  VARCHAR2(500),
    "NS_FUTURE1_ATTRIBUTE_2"  VARCHAR2(500),
	"ENABLED_FLAG"             CHAR(1),
	"EFFECTIVE_START_DATE" DATE,
	"EFFECTIVE_END_DATE" DATE,
	"COA_OC_DESC" VARCHAR2(500),
    "CREATION_DATE" DATE,
	"CREATED_BY" VARCHAR2(50),
	"LAST_UPDATE_DATE" DATE,
	"LAST_UPDATED_BY" VARCHAR2(50)
  ); 