DROP TABLE IF EXISTS "XXMAP"."XXMAP_XX_I004_COA_SEGMENT_VALUES";
CREATE TABLE "XXMAP"."XXMAP_XX_I004_COA_SEGMENT_VALUES" (
    "VALUE_CATEGORY"      VARCHAR2(250 BYTE),
    "DESCRIPTION"         VARCHAR2(250 BYTE),
    "VALUE_CODE"          VARCHAR2(250 BYTE),
    "START_DATE_ACTIVE"   DATE,
    "END_DATE_ACTIVE"     DATE,
    "ENABLED_FLAG"        VARCHAR2(10 BYTE),
    "SUMMARY_FLAG"        VARCHAR2(10 BYTE),
    "CODE_COMBINATION_ID" VARCHAR2(250 BYTE),
    "CREATED_BY"          VARCHAR2(250 BYTE),
    "LAST_UPDATED_BY"     VARCHAR2(250 BYTE),
    "CREATED_DATE"        DATE DEFAULT SYSDATE,
    "LAST_UPDATE_DATE"    DATE,
    PRIMARY KEY ( "VALUE_CATEGORY",
                  "DESCRIPTION" )
);

CREATE INDEX "XXMAP"."XXMAP_XX_I004_COA_SEGMENT_VALUES_N1" ON
    "XXMAP"."XXMAP_XX_I004_COA_SEGMENT_VALUES" (
        "VALUE_CATEGORY",
        "VALUE_CODE",
        "DESCRIPTION"
    );
	
GRANT select, insert, update,  delete ON XXMAP.XXMAP_XX_I004_COA_SEGMENT_VALUES TO XXINT;