DROP TABLE XXMAP.XXMAP_GL_E001_EXCLUDE_ACCOUNTS;


CREATE TABLE XXMAP.XXMAP_GL_E001_EXCLUDE_ACCOUNTS

  (
    "ACCOUNT_NO" VARCHAR2(100),
    "CREATED_BY" VARCHAR2(150),
	"CREATION_DATE" DATE,
	"LAST_UPDATED_BY" VARCHAR2(150),
	"LAST_UPDATE_DATE" DATE
  ); 