DROP TABLE IF EXISTS "XXOOD"."XXOOD_XXI021_ESS_BICC_REPORT_LAST_RUN_DETAILS_TABLE";
CREATE TABLE "XXOOD"."XXOOD_XXI021_ESS_BICC_REPORT_LAST_RUN_DETAILS_TABLE" (
    "TYPE_OF_REPORT"       VARCHAR2(250 BYTE) COLLATE "USING_NLS_COMP",
    "SUCCESSFULL_RUN_TIME" DATE,
     PRIMARY KEY ( "TYPE_OF_REPORT" )
            USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS
                STORAGE ( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL
                DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT )
            TABLESPACE "DATA" ENABLE
) ;

GRANT INSERT ON "XXOOD"."XXOOD_XXI021_ESS_BICC_REPORT_LAST_RUN_DETAILS_TABLE" TO "XXINT";

GRANT SELECT ON "XXOOD"."XXOOD_XXI021_ESS_BICC_REPORT_LAST_RUN_DETAILS_TABLE" TO "XXINT";

GRANT UPDATE ON "XXOOD"."XXOOD_XXI021_ESS_BICC_REPORT_LAST_RUN_DETAILS_TABLE" TO "XXINT";