DROP TABLE IF EXISTS "XXOOD"."XXOOD_XXI021_ESS_BICC_DETAIL_TABLE";
CREATE TABLE "XXOOD"."XXOOD_XXI021_ESS_BICC_DETAIL_TABLE" (
    "REQUEST_ID"       VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP",
    "STATUS"           VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP",
    "NAME"             VARCHAR2(1000 BYTE) COLLATE "USING_NLS_COMP",
    "PROCESS_START"    DATE,
    "PROCESS_END"      DATE,
    "JOB_TYPE"         VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP",
    "JOB_CREATED_BY"   VARCHAR2(250 BYTE) COLLATE "USING_NLS_COMP",
    "CREATED_BY"       VARCHAR2(250 BYTE) COLLATE "USING_NLS_COMP",
    "LAST_UPDATED_BY"  VARCHAR2(250 BYTE) COLLATE "USING_NLS_COMP",
    "CREATION_DATE"    DATE DEFAULT sysdate,
    "LAST_UPDATE_DATE" DATE DEFAULT sysdate,
    "UCM_DOCUMENT_ID"  NUMBER,
    "PARENTJOBID"      NUMBER,
     PRIMARY KEY ( "REQUEST_ID" )
            USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS
                STORAGE ( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL
                DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT )
            TABLESPACE "DATA" ENABLE
) ;

CREATE INDEX "XXOOD"."XXOOD_XXI021_ESS_BICC_DETAIL_TABLE_N1" ON
    "XXOOD"."XXOOD_XXI021_ESS_BICC_DETAIL_TABLE" (
        "STATUS",
        "PROCESS_START",
        "PROCESS_END",
        "REQUEST_ID"
    );

GRANT INSERT ON "XXOOD"."XXOOD_XXI021_ESS_BICC_DETAIL_TABLE" TO "XXINT";

GRANT SELECT ON "XXOOD"."XXOOD_XXI021_ESS_BICC_DETAIL_TABLE" TO "XXINT";

GRANT UPDATE ON "XXOOD"."XXOOD_XXI021_ESS_BICC_DETAIL_TABLE" TO "XXINT";

GRANT DELETE ON "XXOOD"."XXOOD_XXI021_ESS_BICC_DETAIL_TABLE" TO "XXINT";