--------------------------------------------------------
--  File created - Monday-September-15-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Materialized View MV_HZ_GEOGRAPHIES_MAPPED
--------------------------------------------------------

  CREATE MATERIALIZED VIEW "XXSUPCNV"."MV_HZ_GEOGRAPHIES_MAPPED" ("COUNTRY_CODE", "STATE", "PROVINCE", "COUNTY", "CITY", "POSTAL_CODE")
  DEFAULT COLLATION "USING_NLS_COMP"  SEGMENT CREATION IMMEDIATE
  ORGANIZATION HEAP PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" 
  BUILD IMMEDIATE
  USING INDEX 
  REFRESH FORCE ON DEMAND
  USING DEFAULT LOCAL ROLLBACK SEGMENT
  USING ENFORCED CONSTRAINTS DISABLE ON QUERY COMPUTATION DISABLE QUERY REWRITE DISABLE CONCURRENT REFRESH
  AS SELECT 'AU' AS COUNTRY_CODE, GEOGRAPHY_ELEMENT2 AS STATE, NULL AS PROVINCE, NULL AS COUNTY, GEOGRAPHY_ELEMENT3 AS CITY, GEOGRAPHY_ELEMENT4 AS POSTAL_CODE FROM HZ_GEOGRAPHIES WHERE GEOGRAPHY_ELEMENT1_CODE = 'AU'
UNION ALL
SELECT 'CA' AS COUNTRY_CODE, NULL AS STATE, GEOGRAPHY_ELEMENT2 AS PROVINCE, NULL AS COUNTY, GEOGRAPHY_ELEMENT3 AS CITY, GEOGRAPHY_ELEMENT4 AS POSTAL_CODE FROM HZ_GEOGRAPHIES WHERE GEOGRAPHY_ELEMENT1_CODE = 'CA'
UNION ALL
SELECT 'CH' AS COUNTRY_CODE, GEOGRAPHY_ELEMENT2 AS STATE, NULL AS PROVINCE, GEOGRAPHY_ELEMENT3 AS COUNTY, GEOGRAPHY_ELEMENT4 AS CITY, GEOGRAPHY_ELEMENT5 AS POSTAL_CODE FROM HZ_GEOGRAPHIES WHERE GEOGRAPHY_ELEMENT1_CODE = 'CH'
UNION ALL
SELECT 'DE' AS COUNTRY_CODE, GEOGRAPHY_ELEMENT2 AS STATE, NULL AS PROVINCE, NULL AS COUNTY, GEOGRAPHY_ELEMENT3 AS CITY, GEOGRAPHY_ELEMENT4 AS POSTAL_CODE FROM HZ_GEOGRAPHIES WHERE GEOGRAPHY_ELEMENT1_CODE = 'DE'
UNION ALL
SELECT 'DK' AS COUNTRY_CODE, GEOGRAPHY_ELEMENT2 AS STATE, NULL AS PROVINCE, NULL AS COUNTY, GEOGRAPHY_ELEMENT3 AS CITY, GEOGRAPHY_ELEMENT4 AS POSTAL_CODE FROM HZ_GEOGRAPHIES WHERE GEOGRAPHY_ELEMENT1_CODE = 'DK'
UNION ALL
SELECT 'GB' AS COUNTRY_CODE, NULL AS STATE, NULL AS PROVINCE, GEOGRAPHY_ELEMENT2 AS COUNTY, GEOGRAPHY_ELEMENT3 AS CITY, GEOGRAPHY_ELEMENT4 AS POSTAL_CODE FROM HZ_GEOGRAPHIES WHERE GEOGRAPHY_ELEMENT1_CODE = 'GB'
UNION ALL
SELECT 'IE' AS COUNTRY_CODE, GEOGRAPHY_ELEMENT2 AS STATE, NULL AS PROVINCE, NULL AS COUNTY, GEOGRAPHY_ELEMENT3 AS CITY, GEOGRAPHY_ELEMENT4 AS POSTAL_CODE FROM HZ_GEOGRAPHIES WHERE GEOGRAPHY_ELEMENT1_CODE = 'IE'
UNION ALL
SELECT 'IL' AS COUNTRY_CODE, GEOGRAPHY_ELEMENT2 AS STATE, NULL AS PROVINCE, GEOGRAPHY_ELEMENT3 AS COUNTY, GEOGRAPHY_ELEMENT4 AS CITY, GEOGRAPHY_ELEMENT5 AS POSTAL_CODE FROM HZ_GEOGRAPHIES WHERE GEOGRAPHY_ELEMENT1_CODE = 'IL'
UNION ALL
SELECT 'IN' AS COUNTRY_CODE, GEOGRAPHY_ELEMENT2 AS STATE, NULL AS PROVINCE, NULL AS COUNTY, GEOGRAPHY_ELEMENT3 AS CITY, GEOGRAPHY_ELEMENT4 AS POSTAL_CODE FROM HZ_GEOGRAPHIES WHERE GEOGRAPHY_ELEMENT1_CODE = 'IN'
UNION ALL
SELECT 'NL' AS COUNTRY_CODE, NULL AS STATE, GEOGRAPHY_ELEMENT2 AS PROVINCE, GEOGRAPHY_ELEMENT3 AS COUNTY, GEOGRAPHY_ELEMENT4 AS CITY, GEOGRAPHY_ELEMENT5 AS POSTAL_CODE FROM HZ_GEOGRAPHIES WHERE GEOGRAPHY_ELEMENT1_CODE = 'NL'
UNION ALL
SELECT 'NZ' AS COUNTRY_CODE, GEOGRAPHY_ELEMENT2 AS STATE, NULL AS PROVINCE, NULL AS COUNTY, GEOGRAPHY_ELEMENT3 AS CITY, GEOGRAPHY_ELEMENT4 AS POSTAL_CODE FROM HZ_GEOGRAPHIES WHERE GEOGRAPHY_ELEMENT1_CODE = 'NZ'
UNION ALL
SELECT 'PL' AS COUNTRY_CODE, GEOGRAPHY_ELEMENT2 AS STATE, NULL AS PROVINCE, NULL AS COUNTY, GEOGRAPHY_ELEMENT4 AS CITY, GEOGRAPHY_ELEMENT5 AS POSTAL_CODE FROM HZ_GEOGRAPHIES WHERE GEOGRAPHY_ELEMENT1_CODE = 'PL'
UNION ALL
SELECT 'SE' AS COUNTRY_CODE, GEOGRAPHY_ELEMENT2 AS STATE, NULL AS PROVINCE, NULL AS COUNTY, GEOGRAPHY_ELEMENT3 AS CITY, GEOGRAPHY_ELEMENT4 AS POSTAL_CODE FROM HZ_GEOGRAPHIES WHERE GEOGRAPHY_ELEMENT1_CODE = 'SE'
UNION ALL
SELECT 'SG' AS COUNTRY_CODE, GEOGRAPHY_ELEMENT2 AS STATE, NULL AS PROVINCE, NULL AS COUNTY, GEOGRAPHY_ELEMENT3 AS CITY, GEOGRAPHY_ELEMENT4 AS POSTAL_CODE FROM HZ_GEOGRAPHIES WHERE GEOGRAPHY_ELEMENT1_CODE = 'SG'
UNION ALL
SELECT 'US' AS COUNTRY_CODE, GEOGRAPHY_ELEMENT2 AS STATE, NULL AS PROVINCE, GEOGRAPHY_ELEMENT3 AS COUNTY, GEOGRAPHY_ELEMENT4 AS CITY, GEOGRAPHY_ELEMENT5 AS POSTAL_CODE FROM HZ_GEOGRAPHIES WHERE GEOGRAPHY_ELEMENT1_CODE = 'US';

   COMMENT ON MATERIALIZED VIEW "XXSUPCNV"."MV_HZ_GEOGRAPHIES_MAPPED"  IS 'snapshot table for snapshot XXSUPCNV.MV_HZ_GEOGRAPHIES_MAPPED';
