--------------------------------------------------------
--  DDL for View POZ_SUPPLIER_ADDRESSES_FBDI
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "XXSUPCNV"."POZ_SUPPLIER_ADDRESSES_FBDI" ("BATCH_ID", "IMPORT_ACTION", "SUPPLIER_NAME", "ADDRESS_NAME", "ADDRESS_NAME_NEW", "COUNTRY_CODE", "ADDRESS_1", "ADDRESS_2", "ADDRESS_3", "ADDRESS_LINE4", "ADDRESS_LINES_PHONETIC", "ADDR_ELEMENT_ATTRIBUTE1", "ADDR_ELEMENT_ATTRIBUTE2", "ADDR_ELEMENT_ATTRIBUTE3", "ADDR_ELEMENT_ATTRIBUTE4", "ADDR_ELEMENT_ATTRIBUTE5", "BUILDING", "FLOOR_NUMBER", "CITY", "STATE", "PROVINCE", "COUNTY", "POSTAL_CODE", "POSTAL_PLUS_4_CODE", "ADDRESSEE", "GLOBAL_LOCATION_NUMBER", "LANGUAGE", "INACTIVE_DATE", "PHONE_COUNTRY_CODE", "PHONE_AREA_CODE", "PHONE", "PHONE_EXTENSION", "FAX_COUNTRY_CODE", "FAX_AREA_CODE", "FAX", "RFQ_OR_BIDDING", "ORDERING", "PAY", "ATTRIBUTE_CATEGORY", "ATTRIBUTE1", "ATTRIBUTE2", "ATTRIBUTE3", "ATTRIBUTE4", "ATTRIBUTE5", "ATTRIBUTE6", "ATTRIBUTE7", "ATTRIBUTE8", "ATTRIBUTE9", "ATTRIBUTE10", "ATTRIBUTE11", "ATTRIBUTE12", "ATTRIBUTE13", "ATTRIBUTE14", "ATTRIBUTE15", "ATTRIBUTE16", "ATTRIBUTE17", "ATTRIBUTE18", "ATTRIBUTE19", "ATTRIBUTE20", "ATTRIBUTE21", "ATTRIBUTE22", "ATTRIBUTE23", "ATTRIBUTE24", "ATTRIBUTE25", "ATTRIBUTE26", "ATTRIBUTE27", "ATTRIBUTE28", "ATTRIBUTE29", "ATTRIBUTE30", "ATTRIBUTE_NUMBER1", "ATTRIBUTE_NUMBER2", "ATTRIBUTE_NUMBER3", "ATTRIBUTE_NUMBER4", "ATTRIBUTE_NUMBER5", "ATTRIBUTE_NUMBER6", "ATTRIBUTE_NUMBER7", "ATTRIBUTE_NUMBER8", "ATTRIBUTE_NUMBER9", "ATTRIBUTE_NUMBER10", "ATTRIBUTE_NUMBER11", "ATTRIBUTE_NUMBER12", "ATTRIBUTE_DATE1", "ATTRIBUTE_DATE2", "ATTRIBUTE_DATE3", "ATTRIBUTE_DATE4", "ATTRIBUTE_DATE5", "ATTRIBUTE_DATE6", "ATTRIBUTE_DATE7", "ATTRIBUTE_DATE8", "ATTRIBUTE_DATE9", "ATTRIBUTE_DATE10", "ATTRIBUTE_DATE11", "ATTRIBUTE_DATE12", "EMAIL", "DELIVERY_CHANNEL", "BANK_INSTRUCTION_1", "BANK_INSTRUCTION_2", "BANK_INSTRUCTION", "SETTLEMENT_PRIORITY", "PAYMENT_TEXT_MESSAGE_1", "PAYMENT_TEXT_MESSAGE_2", "PAYMENT_TEXT_MESSAGE_3", "PAYEE_SERVICE_LEVEL", "PAY_EACH_DOCUMENT_ALONE", "BANK_CHARGE_BEARER", "PAYMENT_REASON", "PAYMENT_REASON_COMMENTS", "DELIVERY_METHOD", "REMITTANCE_EMAIL", "REMIT_ADVICE_FAX") DEFAULT COLLATION "USING_NLS_COMP"  AS 
  select distinct
        batch_id,
        import_action,
        supplier_name,
        address_name,
        address_name_new,
        country_code,
        address_1,
        address_2,
        address_3,
        ''                                  address_line4,
        ''                                  address_lines_phonetic,
        ''                                  addr_element_attribute1,
        ''                                  addr_element_attribute2,
        ''                                  addr_element_attribute3,
        ''                                  addr_element_attribute4,
        ''                                  addr_element_attribute5,
        ''                                  building,
        ''                                  floor_number,
        city,
        state,
        province,
        county,
        postal_code,
        postal_plus_4_code,
        addressee,
        global_location_number,
        language,
        inactive_date,
        phone_country_code,
        phone_area_code,
        phone,
        phone_extension,
        fax_country_code,
        fax_area_code,
        fax,
        rfq_or_bidding,
        ordering,
        pay,
        ''                                  attribute_category,
        ''                                  attribute1,
        ''                                  attribute2,
        ''                                  attribute3,
        ''                                  attribute4,
        ''                                  attribute5,
        ''                                  attribute6,
        ''                                  attribute7,
        ''                                  attribute8,
        ''                                  attribute9,
        ''                                  attribute10,
        ''                                  attribute11,
        ''                                  attribute12,
        ''                                  attribute13,
        ''                                  attribute14,
        ''                                  attribute15,
        ''                                  attribute16,
        ''                                  attribute17,
        ''                                  attribute18,
        ''                                  attribute19,
        ''                                  attribute20,
        ''                                  attribute21,
        ''                                  attribute22,
        ''                                  attribute23,
        ''                                  attribute24,
        ''                                  attribute25,
        ''                                  attribute26,
        ''                                  attribute27,
        ''                                  attribute28,
        ''                                  attribute29,
        ''                                  attribute30,
        ''                                  attribute_number1,
        ''                                  attribute_number2,
        ''                                  attribute_number3,
        ''                                  attribute_number4,
        ''                                  attribute_number5,
        ''                                  attribute_number6,
        ''                                  attribute_number7,
        ''                                  attribute_number8,
        ''                                  attribute_number9,
        ''                                  attribute_number10,
        ''                                  attribute_number11,
        ''                                  attribute_number12,
        ''                                  attribute_date1,
        ''                                  attribute_date2,
        ''                                  attribute_date3,
        ''                                  attribute_date4,
        ''                                  attribute_date5,
        ''                                  attribute_date6,
        ''                                  attribute_date7,
        ''                                  attribute_date8,
        ''                                  attribute_date9,
        ''                                  attribute_date10,
        ''                                  attribute_date11,
        ''                                  attribute_date12,
        email,
        delivery_channel,
        ''                                  bank_instruction_1,
        ''                                  bank_instruction_2,
        ''                                  bank_instruction,
        ''                                  settlement_priority,
        ''                                  payment_text_message_1,
        ''                                  payment_text_message_2,
        ''                                  payment_text_message_3,
        ''                                  payee_service_level,
        ''                                  pay_each_document_alone,
        ''                                  bank_charge_bearer,
        ''                                  payment_reason,
        ''                                  payment_reason_comments,
        nvl2(remittance_email, 'EMAIL', '') delivery_method,
        remittance_email,
        ''                                  remit_advice_fax
    from
        xxsupcnv.poz_supplier_addresses_ns psa
    where
        nvl(error_flag, 'N') = 'N'
;
/