--------------------------------------------------------
--  DDL for View POZ_SUPPLIERS_FBDI
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "XXSUPCNV"."POZ_SUPPLIERS_FBDI" ("BATCH_ID", "IMPORT_ACTION", "SUPPLIER_NAME", "SUPPLIER_NAME_NEW", "SUPPLIER_NUMBER", "ALTERNATE_NAME", "TAX_ORGANIZATION_TYPE", "SUPPLIER_TYPE", "INACTIVE_DATE", "BUSINESS_RELATIONSHIP", "PARENT_SUPPLIER", "ALIAS", "DUNS_NUMBER", "ONE_TIME_FLAG", "CUSTOMER_NUM", "STANDARD_INDUSTRY_CLASS", "NI_NUMBER", "CORPORATE_WEB_SITE", "CHIEF_EXECUTIVE_TITLE", "CHIEF_EXECUTIVE_NAME", "BC_NOT_APPLICABLE_FLAG", "TAXPAYER_COUNTRY", "TAXPAYER_ID", "FEDERAL_REPORTABLE", "FEDERAL_INCOME_TAX_TYPE", "STATE_REPORTABLE_FLAG", "TAX_REPORTING_NAME", "NAME_CONTROL", "TAX_VERIFICATION_DATE", "ALLOW_AWT_FLAG", "AWT_GROUP_NAME", "VAT_CODE", "TAX_REGISTRATION_NUMBER", "AUTO_TAX_CALC_OVERRIDE", "PAYMENT_METHOD", "DELIVERY_CHANNEL_CODE", "BANK_INSTRUCTION1_CODE", "BANK_INSTRUCTION2_CODE", "BANK_INSTRUCTION_DETAILS", "SETTLEMENT_PRIORITY", "PAYMENT_TEXT_MESSAGE1", "PAYMENT_TEXT_MESSAGE2", "PAYMENT_TEXT_MESSAGE3", "IBY_BANK_VARCHAR2GE_BEARER", "PAYMENT_REASON_CODE", "PAYMENT_REASON_COMMENTS", "PAYMENT_FORMAT_CODE", "ATTRIBUTE_CATEGORY", "ATTRIBUTE1", "ATTRIBUTE2", "ATTRIBUTE3", "ATTRIBUTE4", "ATTRIBUTE5", "ATTRIBUTE6", "ATTRIBUTE7", "ATTRIBUTE8", "ATTRIBUTE9", "ATTRIBUTE10", "ATTRIBUTE11", "ATTRIBUTE12", "ATTRIBUTE13", "ATTRIBUTE14", "ATTRIBUTE15", "ATTRIBUTE16", "ATTRIBUTE17", "ATTRIBUTE18", "ATTRIBUTE19", "ATTRIBUTE20", "ATTRIBUTE_DATE1", "ATTRIBUTE_DATE2", "ATTRIBUTE_DATE3", "ATTRIBUTE_DATE4", "ATTRIBUTE_DATE5", "ATTRIBUTE_DATE6", "ATTRIBUTE_DATE7", "ATTRIBUTE_DATE8", "ATTRIBUTE_DATE9", "ATTRIBUTE_DATE10", "ATTRIBUTE_TIMESTAMP1", "ATTRIBUTE_TIMESTAMP2", "ATTRIBUTE_TIMESTAMP3", "ATTRIBUTE_TIMESTAMP4", "ATTRIBUTE_TIMESTAMP5", "ATTRIBUTE_TIMESTAMP6", "ATTRIBUTE_TIMESTAMP7", "ATTRIBUTE_TIMESTAMP8", "ATTRIBUTE_TIMESTAMP9", "ATTRIBUTE_TIMESTAMP10", "ATTRIBUTE_NUMBER1", "ATTRIBUTE_NUMBER2", "ATTRIBUTE_NUMBER3", "ATTRIBUTE_NUMBER4", "ATTRIBUTE_NUMBER5", "ATTRIBUTE_NUMBER6", "ATTRIBUTE_NUMBER7", "ATTRIBUTE_NUMBER8", "ATTRIBUTE_NUMBER9", "ATTRIBUTE_NUMBER10", "GLOBAL_ATTRIBUTE_CATEGORY", "GLOBAL_ATTRIBUTE1", "GLOBAL_ATTRIBUTE2", "GLOBAL_ATTRIBUTE3", "GLOBAL_ATTRIBUTE4", "GLOBAL_ATTRIBUTE5", "GLOBAL_ATTRIBUTE6", "GLOBAL_ATTRIBUTE7", "GLOBAL_ATTRIBUTE8", "GLOBAL_ATTRIBUTE9", "GLOBAL_ATTRIBUTE10", "GLOBAL_ATTRIBUTE11", "GLOBAL_ATTRIBUTE12", "GLOBAL_ATTRIBUTE13", "GLOBAL_ATTRIBUTE14", "GLOBAL_ATTRIBUTE15", "GLOBAL_ATTRIBUTE16", "GLOBAL_ATTRIBUTE17", "GLOBAL_ATTRIBUTE18", "GLOBAL_ATTRIBUTE19", "GLOBAL_ATTRIBUTE20", "GLOBAL_ATTRIBUTE_DATE1", "GLOBAL_ATTRIBUTE_DATE2", "GLOBAL_ATTRIBUTE_DATE3", "GLOBAL_ATTRIBUTE_DATE4", "GLOBAL_ATTRIBUTE_DATE5", "GLOBAL_ATTRIBUTE_DATE6", "GLOBAL_ATTRIBUTE_DATE7", "GLOBAL_ATTRIBUTE_DATE8", "GLOBAL_ATTRIBUTE_DATE9", "GLOBAL_ATTRIBUTE_DATE10", "GLOBAL_ATTRIBUTE_TIMESTAMP1", "GLOBAL_ATTRIBUTE_TIMESTAMP2", "GLOBAL_ATTRIBUTE_TIMESTAMP3", "GLOBAL_ATTRIBUTE_TIMESTAMP4", "GLOBAL_ATTRIBUTE_TIMESTAMP5", "GLOBAL_ATTRIBUTE_TIMESTAMP6", "GLOBAL_ATTRIBUTE_TIMESTAMP7", "GLOBAL_ATTRIBUTE_TIMESTAMP8", "GLOBAL_ATTRIBUTE_TIMESTAMP9", "GLOBAL_ATTRIBUTE_TIMESTAMP10", "GLOBAL_ATTRIBUTE_NUMBER1", "GLOBAL_ATTRIBUTE_NUMBER2", "GLOBAL_ATTRIBUTE_NUMBER3", "GLOBAL_ATTRIBUTE_NUMBER4", "GLOBAL_ATTRIBUTE_NUMBER5", "GLOBAL_ATTRIBUTE_NUMBER6", "GLOBAL_ATTRIBUTE_NUMBER7", "GLOBAL_ATTRIBUTE_NUMBER8", "GLOBAL_ATTRIBUTE_NUMBER9", "GLOBAL_ATTRIBUTE_NUMBER10", "PARTY_NUMBER", "SERVICE_LEVEL_CODE", "EXCLUSIVE_PAYMENT_FLAG", "REMIT_ADVICE_DELIVERY_METHOD", "REMITTANCE_E_MAIL", "REMIT_ADVICE_FAX") DEFAULT COLLATION "USING_NLS_COMP"  AS 
  select
        batch_id,
        import_action,
        supplier_name,
        supplier_name_new,
        supplier_number,
        alternate_name,
        tax_organization_type,
        'Supplier'                           supplier_type,
        inactive_date,
        business_relationship,
        parent_supplier,
        alias,
        duns_number,
        'N'                                  one_time_flag,
        ''                                   customer_num,
        ''                                   standard_industry_class,
        ''                                   ni_number,
        corporate_web_site,
        ''                                   chief_executive_title,
        ''                                   chief_executive_name,
        ''                                   bc_not_applicable_flag,
        taxpayer_country,
        taxpayer_id,
        federal_reportable,
        federal_income_tax_type,
        ''                                   state_reportable_flag,
        ''                                   tax_reporting_name,
        ''                                   name_control,
        ''                                   tax_verification_date,
        ''                                   allow_awt_flag,
        ''                                   awt_group_name,
        ''                                   vat_code,
        tax_registration_number,
        ''                                   auto_tax_calc_override,
        payment_method,
        ''                                   delivery_channel_code,
        ''                                   bank_instruction1_code,
        ''                                   bank_instruction2_code,
        ''                                   bank_instruction_details,
        ''                                   settlement_priority,
        ''                                   payment_text_message1,
        ''                                   payment_text_message2,
        ''                                   payment_text_message3,
        ''                                   iby_bank_varchar2ge_bearer,
        ''                                   payment_reason_code,
        ''                                   payment_reason_comments,
        ''                                   payment_format_code,
        ''                                   attribute_category,
        critical_pay                         attribute1,
        ''                                   attribute2,
        ''                                   attribute3,
        ''                                   attribute4,
        ''                                   attribute5,
        ''                                   attribute6,
        ''                                   attribute7,
        ''                                   attribute8,
        ''                                   attribute9,
        ''                                   attribute10,
        ''                                   attribute11,
        ''                                   attribute12,
        ''                                   attribute13,
        ''                                   attribute14,
        ''                                   attribute15,
        ''                                   attribute16,
        ''                                   attribute17,
        ''                                   attribute18,
        ''                                   attribute19,
        ''                                   attribute20,
        ''                                   attribute_date1,
        ''                                   attribute_date2,
        ''                                   attribute_date3,
        ''                                   attribute_date4,
        ''                                   attribute_date5,
        ''                                   attribute_date6,
        ''                                   attribute_date7,
        ''                                   attribute_date8,
        ''                                   attribute_date9,
        ''                                   attribute_date10,
        ''                                   attribute_timestamp1,
        ''                                   attribute_timestamp2,
        ''                                   attribute_timestamp3,
        ''                                   attribute_timestamp4,
        ''                                   attribute_timestamp5,
        ''                                   attribute_timestamp6,
        ''                                   attribute_timestamp7,
        ''                                   attribute_timestamp8,
        ''                                   attribute_timestamp9,
        ''                                   attribute_timestamp10,
        ''                                   attribute_number1,
        ''                                   attribute_number2,
        ''                                   attribute_number3,
        ''                                   attribute_number4,
        ''                                   attribute_number5,
        ''                                   attribute_number6,
        ''                                   attribute_number7,
        ''                                   attribute_number8,
        ''                                   attribute_number9,
        ''                                   attribute_number10,
        ''                                   global_attribute_category,
        ''                                   global_attribute1,
        ''                                   global_attribute2,
        ''                                   global_attribute3,
        ''                                   global_attribute4,
        ''                                   global_attribute5,
        ''                                   global_attribute6,
        ''                                   global_attribute7,
        ''                                   global_attribute8,
        ''                                   global_attribute9,
        ''                                   global_attribute10,
        ''                                   global_attribute11,
        ''                                   global_attribute12,
        ''                                   global_attribute13,
        ''                                   global_attribute14,
        ''                                   global_attribute15,
        ''                                   global_attribute16,
        ''                                   global_attribute17,
        ''                                   global_attribute18,
        ''                                   global_attribute19,
        ''                                   global_attribute20,
        ''                                   global_attribute_date1,
        ''                                   global_attribute_date2,
        ''                                   global_attribute_date3,
        ''                                   global_attribute_date4,
        ''                                   global_attribute_date5,
        ''                                   global_attribute_date6,
        ''                                   global_attribute_date7,
        ''                                   global_attribute_date8,
        ''                                   global_attribute_date9,
        ''                                   global_attribute_date10,
        ''                                   global_attribute_timestamp1,
        ''                                   global_attribute_timestamp2,
        ''                                   global_attribute_timestamp3,
        ''                                   global_attribute_timestamp4,
        ''                                   global_attribute_timestamp5,
        ''                                   global_attribute_timestamp6,
        ''                                   global_attribute_timestamp7,
        ''                                   global_attribute_timestamp8,
        ''                                   global_attribute_timestamp9,
        ''                                   global_attribute_timestamp10,
        ''                                   global_attribute_number1,
        ''                                   global_attribute_number2,
        ''                                   global_attribute_number3,
        ''                                   global_attribute_number4,
        ''                                   global_attribute_number5,
        ''                                   global_attribute_number6,
        ''                                   global_attribute_number7,
        ''                                   global_attribute_number8,
        ''                                   global_attribute_number9,
        ''                                   global_attribute_number10,
        ''                                   party_number,
        ''                                   service_level_code,
        ''                                   exclusive_payment_flag,
        nvl2(remittance_e_mail, 'EMAIL', '') remit_advice_delivery_method,
        remittance_e_mail,
        ''                                   remit_advice_fax
    from
        xxsupcnv.poz_suppliers_ns ps
    where
        nvl(error_flag, 'N') = 'N'
;
/