--------------------------------------------------------
--  DDL for View POZ_SUPPLIER_SITES_FBDI
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "XXSUPCNV"."POZ_SUPPLIER_SITES_FBDI" ("BATCH_ID", "IMPORT_ACTION", "SUPPLIER_NAME", "PROCUREMENT_BU", "ADDRESS_NAME", "SUPPLIER_SITE", "SUPPLIER_SITE_NEW", "INACTIVE_DATE", "SOURCING_ONLY", "PURCHASING", "PROCUREMENT_CARD", "PAY", "PRIMARY_PAY", "INCOME_TAX_REPORTING_SITE", "ALTERNATE_SITE_NAME", "CUSTOMER_NUMBER", "B2B_COMMUNICATION_METHOD", "B2B_SITE_CODE", "COMMUNICATION_METHOD", "EMAIL", "FAX_COUNTRY_CODE", "FAX_AREA_CODE", "FAX", "HOLD_ALL_NEW_PURCHASING_DOCUMENTS", "PURCHASING_HOLD_REASON", "CARRIER", "MODE_OF_TRANSPORT", "SERVICE_LEVEL", "FREIGHT_TERMS", "PAY_ON_RECEIPT", "FOB", "COUNTRY_OF_ORIGIN", "BUYER_MANAGED_TRANSPORTATION", "PAY_ON_USE", "AGING_ONSET_POINT", "AGING_PERIOD_DAYS", "CONSUMPTION_ADVICE_FREQUENCY", "CONSUMPTION_ADVICE_SUMMARY", "ALTERNATE_PAY_SITE", "INVOICE_SUMMARY_LEVEL", "GAPLESS_INVOICE_NUMBERING", "SELLING_COMPANY_IDENTIFIER", "CREATE_DEBIT_MEMO_FROM_RETURN", "SHIP_TO_EXCEPTION_ACTION", "RECEIPT_ROUTING", "OVER_RECEIPT_TOLERANCE", "OVER_RECEIPT_ACTION", "DAYS_EARLY_RECEIPT_ALLOWED", "DAYS_LATE_RECEIPT_ALLOWED", "ALLOW_SUBSTITUTE_RECEIPTS_FLAG", "ALLOW_UNORDERED_RECEIPTS_FLAG", "RECEIPT_DAYS_EXCEPTION_CODE", "INVOICE_CURRENCY_CODE", "INVOICE_AMOUNT_LIMIT", "MATCH_OPTION", "MATCH_APPROVAL_LEVEL", "PAYMENT_CURRENCY", "PAYMENT_PRIORITY", "PAY_GROUP", "QUANTITY_TOLERANCES", "AMOUNT_TOLERANCE", "HOLD_ALL_INVOICES", "HOLD_UNMATCHED_INVOICES", "HOLD_UNVALIDATED_INVOICES", "PAYMENT_HOLD_BY", "PAYMENT_HOLD_DATE", "PAYMENT_HOLD_REASON", "PAYMENT_TERMS", "TERMS_DATE_BASIS", "PAY_DATE_BASIS", "BANK_CHARGE_DEDUCTION_TYPE", "ALWAYS_TAKE_DISCOUNT", "EXCLUDE_FREIGHT_FROM_DISCOUNT", "EXCLUDE_TAX_FROM_DISCOUNT", "CREATE_INTEREST_INVOICES", "VAT_CODE_OBSOLETED", "TAX_REGISTRATION_NUMBER_OBSOLETED", "PAYMENT_METHOD", "DELIVERY_CHANNEL", "BANK_INSTRUCTION_1", "BANK_INSTRUCTION_2", "BANK_INSTRUCTION", "SETTLEMENT_PRIORITY", "PAYMENT_TEXT_MESSAGE_1", "PAYMENT_TEXT_MESSAGE_2", "PAYMENT_TEXT_MESSAGE_3", "BANK_CHARGE_BEARER", "PAYMENT_REASON", "PAYMENT_REASON_COMMENTS", "DELIVERY_METHOD", "REMITTANCE_EMAIL", "REMIT_ADVICE_FAX", "ATTRIBUTE_CATEGORY", "ATTRIBUTE1", "ATTRIBUTE2", "ATTRIBUTE3", "ATTRIBUTE4", "ATTRIBUTE5", "ATTRIBUTE6", "ATTRIBUTE7", "ATTRIBUTE8", "ATTRIBUTE9", "ATTRIBUTE10", "ATTRIBUTE11", "ATTRIBUTE12", "ATTRIBUTE13", "ATTRIBUTE14", "ATTRIBUTE15", "ATTRIBUTE16", "ATTRIBUTE17", "ATTRIBUTE18", "ATTRIBUTE19", "ATTRIBUTE20", "ATTRIBUTE_DATE1", "ATTRIBUTE_DATE2", "ATTRIBUTE_DATE3", "ATTRIBUTE_DATE4", "ATTRIBUTE_DATE5", "ATTRIBUTE_DATE6", "ATTRIBUTE_DATE7", "ATTRIBUTE_DATE8", "ATTRIBUTE_DATE9", "ATTRIBUTE_DATE10", "ATTRIBUTE_TIMESTAMP1", "ATTRIBUTE_TIMESTAMP2", "ATTRIBUTE_TIMESTAMP3", "ATTRIBUTE_TIMESTAMP4", "ATTRIBUTE_TIMESTAMP5", "ATTRIBUTE_TIMESTAMP6", "ATTRIBUTE_TIMESTAMP7", "ATTRIBUTE_TIMESTAMP8", "ATTRIBUTE_TIMESTAMP9", "ATTRIBUTE_TIMESTAMP10", "ATTRIBUTE_NUMBER1", "ATTRIBUTE_NUMBER2", "ATTRIBUTE_NUMBER3", "ATTRIBUTE_NUMBER4", "ATTRIBUTE_NUMBER5", "ATTRIBUTE_NUMBER6", "ATTRIBUTE_NUMBER7", "ATTRIBUTE_NUMBER8", "ATTRIBUTE_NUMBER9", "ATTRIBUTE_NUMBER10", "GLOBAL_ATTRIBUTE_CATEGORY", "GLOBAL_ATTRIBUTE1", "GLOBAL_ATTRIBUTE2", "GLOBAL_ATTRIBUTE3", "GLOBAL_ATTRIBUTE4", "GLOBAL_ATTRIBUTE5", "GLOBAL_ATTRIBUTE6", "GLOBAL_ATTRIBUTE7", "GLOBAL_ATTRIBUTE8", "GLOBAL_ATTRIBUTE9", "GLOBAL_ATTRIBUTE10", "GLOBAL_ATTRIBUTE11", "GLOBAL_ATTRIBUTE12", "GLOBAL_ATTRIBUTE13", "GLOBAL_ATTRIBUTE14", "GLOBAL_ATTRIBUTE15", "GLOBAL_ATTRIBUTE16", "GLOBAL_ATTRIBUTE17", "GLOBAL_ATTRIBUTE18", "GLOBAL_ATTRIBUTE19", "GLOBAL_ATTRIBUTE20", "GLOBAL_ATTRIBUTE_DATE1", "GLOBAL_ATTRIBUTE_DATE2", "GLOBAL_ATTRIBUTE_DATE3", "GLOBAL_ATTRIBUTE_DATE4", "GLOBAL_ATTRIBUTE_DATE5", "GLOBAL_ATTRIBUTE_DATE6", "GLOBAL_ATTRIBUTE_DATE7", "GLOBAL_ATTRIBUTE_DATE8", "GLOBAL_ATTRIBUTE_DATE9", "GLOBAL_ATTRIBUTE_DATE10", "GLOBAL_ATTRIBUTE_TIMESTAMP1", "GLOBAL_ATTRIBUTE_TIMESTAMP2", "GLOBAL_ATTRIBUTE_TIMESTAMP3", "GLOBAL_ATTRIBUTE_TIMESTAMP4", "GLOBAL_ATTRIBUTE_TIMESTAMP5", "GLOBAL_ATTRIBUTE_TIMESTAMP6", "GLOBAL_ATTRIBUTE_TIMESTAMP7", "GLOBAL_ATTRIBUTE_TIMESTAMP8", "GLOBAL_ATTRIBUTE_TIMESTAMP9", "GLOBAL_ATTRIBUTE_TIMESTAMP10", "GLOBAL_ATTRIBUTE_NUMBER1", "GLOBAL_ATTRIBUTE_NUMBER2", "GLOBAL_ATTRIBUTE_NUMBER3", "GLOBAL_ATTRIBUTE_NUMBER4", "GLOBAL_ATTRIBUTE_NUMBER5", "GLOBAL_ATTRIBUTE_NUMBER6", "GLOBAL_ATTRIBUTE_NUMBER7", "GLOBAL_ATTRIBUTE_NUMBER8", "GLOBAL_ATTRIBUTE_NUMBER9", "GLOBAL_ATTRIBUTE_NUMBER10", "PO_ACK_REQD_CODE", "PO_ACK_REQD_DAYS", "INVOICE_CHANNEL", "PAYEE_SERVICE_LEVEL_CODE", "EXCLUSIVE_PARENT_FLAG") DEFAULT COLLATION "USING_NLS_COMP"  AS 
  SELECT DISTINCT
        batch_id,
        import_action,
        supplier_name,
        procurement_bu,
        address_name,
        supplier_site,
        supplier_site_new,
        inactive_date,
        sourcing_only,
        purchasing,
        procurement_card,
        pay,
        primary_pay,
        income_tax_reporting_site,
        alternate_site_name,
        customer_number,
        b2b_communication_method,
        ''                                  b2b_site_code,
        communication_method,
        email,
        fax_country_code,
        fax_area_code,
        fax,
        hold_all_new_purchasing_documents,
        purchasing_hold_reason,
        carrier,
        mode_of_transport,
        service_level,
        freight_terms,
        pay_on_receipt,
        fob,
        country_of_origin,
        buyer_managed_transportation,
        pay_on_use,
        aging_onset_point,
        aging_period_days,
        consumption_advice_frequency,
        consumption_advice_summary,
        alternate_pay_site,
        invoice_summary_level,
        gapless_invoice_numbering,
        selling_company_identifier,
        create_debit_memo_from_return,
        ship_to_exception_action,
        receipt_routing,
        over_receipt_tolerance,
        over_receipt_action,
        ''                                  days_early_receipt_allowed,
        ''                                  days_late_receipt_allowed,
        ''                                  allow_substitute_receipts_flag,
        ''                                  allow_unordered_receipts_flag,
        ''                                  receipt_days_exception_code,
        ''                                  invoice_currency_code,
        ''                                  invoice_amount_limit,
        ''                                  match_option,
        ''                                  match_approval_level,
        payment_currency,
        payment_priority,
        ''                                  pay_group,
        ''                                  quantity_tolerances,
        ''                                  amount_tolerance,
        ''                                  hold_all_invoices,
        ''                                  hold_unmatched_invoices,
        ''                                  hold_unvalidated_invoices,
        ''                                  payment_hold_by,
        ''                                  payment_hold_date,
        ''                                  payment_hold_reason,
        payment_terms,
        ''                                  terms_date_basis,
        ''                                  pay_date_basis,
        ''                                  bank_charge_deduction_type,
        ''                                  always_take_discount,
        ''                                  exclude_freight_from_discount,
        ''                                  exclude_tax_from_discount,
        ''                                  create_interest_invoices,
        ''                                  vat_code_obsoleted,
        ''                                  tax_registration_number_obsoleted,
        payment_method,
        ''                                  delivery_channel,
        ''                                  bank_instruction_1,
        ''                                  bank_instruction_2,
        ''                                  bank_instruction,
        ''                                  settlement_priority,
        ''                                  payment_text_message_1,
        ''                                  payment_text_message_2,
        ''                                  payment_text_message_3,
        ''                                  bank_charge_bearer,
        ''                                  payment_reason,
        (
            SELECT
                payment_reason_comments
            FROM
                ibytempextpayees_cleaned
            WHERE
                supplier_number = pss.id
        )                                   payment_reason_comments,
        nvl2(remittance_email, 'EMAIL', '') delivery_method,
        remittance_email,
        ''                                  remit_advice_fax,
        ''                                  attribute_category,
        attribute1,
        ''                                  attribute2,
        ''                                  attribute3,
        ''                                  attribute4,
        ''                                  attribute5,
        ''                                  attribute6,
        ''                                  attribute7,
        ''                                  attribute8,
        ''                                  attribute9,
        ''                                  attribute10,
        ''                                  attribute11,
        ''                                  attribute12,
        ''                                  attribute13,
        ''                                  attribute14,
        ''                                  attribute15,
        ''                                  attribute16,
        ''                                  attribute17,
        ''                                  attribute18,
        ''                                  attribute19,
        ''                                  attribute20,
        ''                                  attribute_date1,
        ''                                  attribute_date2,
        ''                                  attribute_date3,
        ''                                  attribute_date4,
        ''                                  attribute_date5,
        ''                                  attribute_date6,
        ''                                  attribute_date7,
        ''                                  attribute_date8,
        ''                                  attribute_date9,
        ''                                  attribute_date10,
        ''                                  attribute_timestamp1,
        ''                                  attribute_timestamp2,
        ''                                  attribute_timestamp3,
        ''                                  attribute_timestamp4,
        ''                                  attribute_timestamp5,
        ''                                  attribute_timestamp6,
        ''                                  attribute_timestamp7,
        ''                                  attribute_timestamp8,
        ''                                  attribute_timestamp9,
        ''                                  attribute_timestamp10,
        ''                                  attribute_number1,
        ''                                  attribute_number2,
        ''                                  attribute_number3,
        ''                                  attribute_number4,
        ''                                  attribute_number5,
        ''                                  attribute_number6,
        ''                                  attribute_number7,
        ''                                  attribute_number8,
        ''                                  attribute_number9,
        ''                                  attribute_number10,
        ''                                  global_attribute_category,
        ''                                  global_attribute1,
        ''                                  global_attribute2,
        ''                                  global_attribute3,
        ''                                  global_attribute4,
        ''                                  global_attribute5,
        ''                                  global_attribute6,
        ''                                  global_attribute7,
        ''                                  global_attribute8,
        ''                                  global_attribute9,
        ''                                  global_attribute10,
        ''                                  global_attribute11,
        ''                                  global_attribute12,
        ''                                  global_attribute13,
        ''                                  global_attribute14,
        ''                                  global_attribute15,
        ''                                  global_attribute16,
        ''                                  global_attribute17,
        ''                                  global_attribute18,
        ''                                  global_attribute19,
        ''                                  global_attribute20,
        ''                                  global_attribute_date1,
        ''                                  global_attribute_date2,
        ''                                  global_attribute_date3,
        ''                                  global_attribute_date4,
        ''                                  global_attribute_date5,
        ''                                  global_attribute_date6,
        ''                                  global_attribute_date7,
        ''                                  global_attribute_date8,
        ''                                  global_attribute_date9,
        ''                                  global_attribute_date10,
        ''                                  global_attribute_timestamp1,
        ''                                  global_attribute_timestamp2,
        ''                                  global_attribute_timestamp3,
        ''                                  global_attribute_timestamp4,
        ''                                  global_attribute_timestamp5,
        ''                                  global_attribute_timestamp6,
        ''                                  global_attribute_timestamp7,
        ''                                  global_attribute_timestamp8,
        ''                                  global_attribute_timestamp9,
        ''                                  global_attribute_timestamp10,
        ''                                  global_attribute_number1,
        ''                                  global_attribute_number2,
        ''                                  global_attribute_number3,
        ''                                  global_attribute_number4,
        ''                                  global_attribute_number5,
        ''                                  global_attribute_number6,
        ''                                  global_attribute_number7,
        ''                                  global_attribute_number8,
        ''                                  global_attribute_number9,
        ''                                  global_attribute_number10,
        ''                                  po_ack_reqd_code,
        ''                                  po_ack_reqd_days,
        ''                                  invoice_channel,
        ''                                  payee_service_level_code,
        ''                                  exclusive_parent_flag
    FROM
        xxsupcnv.poz_supplier_sites_ns pss
    WHERE
        nvl(error_flag, 'N') = 'N'
;