--------------------------------------------------------
--  DDL for View POZ_SUP_CONTACTS_FBDI
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "XXSUPCNV"."POZ_SUP_CONTACTS_FBDI" ("BATCH_ID", "IMPORT_ACTION", "SUPPLIER_NAME", "PREFIX", "FIRST_NAME", "FIRST_NAME_NEW", "MIDDLE_NAME", "LAST_NAME", "LAST_NAME_NEW", "JOB_TITLE", "ADMINISTRATIVE_CONTACT", "EMAIL", "E_MAIL_NEW", "PHONE_COUNTRY_CODE", "PHONE_AREA_CODE", "PHONE", "PHONE_EXTENSION", "FAX_COUNTRY_CODE", "FAX_AREA_CODE", "FAX", "MOBILE_COUNTRY_CODE", "MOBILE_AREA_CODE", "MOBILE", "INACTIVE_DATE", "ATTRIBUTE_CATEGORY", "ATTRIBUTE1", "ATTRIBUTE2", "ATTRIBUTE3", "ATTRIBUTE4", "ATTRIBUTE5", "ATTRIBUTE6", "ATTRIBUTE7", "ATTRIBUTE8", "ATTRIBUTE9", "ATTRIBUTE10", "ATTRIBUTE11", "ATTRIBUTE12", "ATTRIBUTE13", "ATTRIBUTE14", "ATTRIBUTE15", "ATTRIBUTE16", "ATTRIBUTE17", "ATTRIBUTE18", "ATTRIBUTE19", "ATTRIBUTE20", "ATTRIBUTE21", "ATTRIBUTE22", "ATTRIBUTE23", "ATTRIBUTE24", "ATTRIBUTE25", "ATTRIBUTE26", "ATTRIBUTE27", "ATTRIBUTE28", "ATTRIBUTE29", "ATTRIBUTE30", "ATTRIBUTE_NUMBER1", "ATTRIBUTE_NUMBER2", "ATTRIBUTE_NUMBER3", "ATTRIBUTE_NUMBER4", "ATTRIBUTE_NUMBER5", "ATTRIBUTE_NUMBER6", "ATTRIBUTE_NUMBER7", "ATTRIBUTE_NUMBER8", "ATTRIBUTE_NUMBER9", "ATTRIBUTE_NUMBER10", "ATTRIBUTE_NUMBER11", "ATTRIBUTE_NUMBER12", "ATTRIBUTE_DATE1", "ATTRIBUTE_DATE2", "ATTRIBUTE_DATE3", "ATTRIBUTE_DATE4", "ATTRIBUTE_DATE5", "ATTRIBUTE_DATE6", "ATTRIBUTE_DATE7", "ATTRIBUTE_DATE8", "ATTRIBUTE_DATE9", "ATTRIBUTE_DATE10", "ATTRIBUTE_DATE11", "ATTRIBUTE_DATE12", "USER_ACCOUNT_ACTION", "ROLE1", "ROLE2", "ROLE3", "ROLE4", "ROLE5", "ROLE6", "ROLE7", "ROLE8", "ROLE9", "ROLE10") DEFAULT COLLATION "USING_NLS_COMP"  AS 
  select distinct
        batch_id,
        import_action,
        supplier_name,
        prefix,
        first_name,
        first_name_new,
        middle_name,
        last_name,
        last_name_new,
        job_title,
        administrative_contact,
        email,
        e_mail_new,
        phone_country_code,
        phone_area_code,
        phone,
        phone_extension,
        fax_country_code,
        fax_area_code,
        fax,
        mobile_country_code,
        mobile_area_code,
        mobile,
        inactive_date,
        '' attribute_category,
        '' attribute1,
        '' attribute2,
        '' attribute3,
        '' attribute4,
        '' attribute5,
        '' attribute6,
        '' attribute7,
        '' attribute8,
        '' attribute9,
        '' attribute10,
        '' attribute11,
        '' attribute12,
        '' attribute13,
        '' attribute14,
        '' attribute15,
        '' attribute16,
        '' attribute17,
        '' attribute18,
        '' attribute19,
        '' attribute20,
        '' attribute21,
        '' attribute22,
        '' attribute23,
        '' attribute24,
        '' attribute25,
        '' attribute26,
        '' attribute27,
        '' attribute28,
        '' attribute29,
        '' attribute30,
        '' attribute_number1,
        '' attribute_number2,
        '' attribute_number3,
        '' attribute_number4,
        '' attribute_number5,
        '' attribute_number6,
        '' attribute_number7,
        '' attribute_number8,
        '' attribute_number9,
        '' attribute_number10,
        '' attribute_number11,
        '' attribute_number12,
        '' attribute_date1,
        '' attribute_date2,
        '' attribute_date3,
        '' attribute_date4,
        '' attribute_date5,
        '' attribute_date6,
        '' attribute_date7,
        '' attribute_date8,
        '' attribute_date9,
        '' attribute_date10,
        '' attribute_date11,
        '' attribute_date12,
        '' user_account_action,
        '' role1,
        '' role2,
        '' role3,
        '' role4,
        '' role5,
        '' role6,
        '' role7,
        '' role8,
        '' role9,
        '' role10
    from
        xxsupcnv.poz_sup_contacts_ns a
    where
        nvl(error_flag, 'N') = 'N'
;
/