-- Generated by Oracle SQL Developer REST Data Services 24.3.1.347.1826
-- Exported REST Definitions from ORDS Schema Version 25.3.1.r2891312
-- Schema: XXOOD   Date: Mon Dec 08 17:33:28 UTC 2025
--
BEGIN
  ORDS.ENABLE_SCHEMA(
      p_enabled             => TRUE,
      p_schema              => 'XXOOD',
      p_url_mapping_type    => 'BASE_PATH',
      p_url_mapping_pattern => 'xxood',
      p_auto_rest_auth      => TRUE);    

  ORDS.DEFINE_MODULE(
      p_module_name    => 'XXOOD_APP',
      p_base_path      => '/db/',
      p_items_per_page =>  25,
      p_status         => 'PUBLISHED',
      p_comments       => NULL);      
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'XXOOD_APP',
      p_pattern        => 'getSummary',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'XXOOD_APP',
      p_pattern        => 'getSummary',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_items_per_page =>  25,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'select xxood_xxi021_job_summary_pkg.ess_summary_fnc(:p_days_cnt,:p_job_type,:p_current_time) from dual'
      );
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'XXOOD_APP',
      p_pattern            => 'getSummary',
      p_method             => 'GET',
      p_name               => 'p_current_time',
      p_bind_variable_name => 'p_current_time',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'XXOOD_APP',
      p_pattern            => 'getSummary',
      p_method             => 'GET',
      p_name               => 'p_days_cnt',
      p_bind_variable_name => 'p_days_cnt',
      p_source_type        => 'HEADER',
      p_param_type         => 'INT',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'XXOOD_APP',
      p_pattern            => 'getSummary',
      p_method             => 'GET',
      p_name               => 'p_job_type',
      p_bind_variable_name => 'p_job_type',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      


  COMMIT; 
END;