ALTER TABLE "XXREQ"."XXREQ_JOB_REQ_REQUESTS" ADD 
   (	
	"SALARY_BASE_LOCAL" NUMBER, 
	"VARIABLE_SALARY_LOCAL" NUMBER, 
	"CURRENCY" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"CONVERSION_RATE" NUMBER
   );