ALTER TABLE XXINT.XXINT_HCM_116_GREENHOUSE_INBOUND ADD(CANDIDATEID NUMBER);
ALTER TABLE XXINT.XXINT_HCM_116_GREENHOUSE_INBOUND MODIFY CREATED_DATE DEFAULT SYSDATE;
ALTER TABLE XXINT.XXINT_HCM_116_GREENHOUSE_INBOUND ADD(EmploymentType VARCHAR2(150));