--------------------------------------------------------
--  File created - Wednesday-August-13-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence XXREQ_JOB_REQ_DELEGATIONSS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "XXREQ"."XXREQ_JOB_REQ_DELEGATIONSS_SEQ"  MINVALUE 1 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence XXREQ_JOB_REQ_ENGINEERING_DEPARTMENTS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "XXREQ"."XXREQ_JOB_REQ_ENGINEERING_DEPARTMENTS_SEQ"  MINVALUE 1 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 17 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence XXREQ_JOB_REQ_REQUESTS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "XXREQ"."XXREQ_JOB_REQ_REQUESTS_SEQ"  MINVALUE 1 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence XXREQ_JOB_REQ_STATUSES_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "XXREQ"."XXREQ_JOB_REQ_STATUSES_SEQ"  MINVALUE 1 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 5 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence XXREQ_JOB_REQ_TYPES_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "XXREQ"."XXREQ_JOB_REQ_TYPES_SEQ"  MINVALUE 1 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 5 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Table XXREQ_JOB_REQ_DELEGATIONS
--------------------------------------------------------

  CREATE TABLE "XXREQ"."XXREQ_JOB_REQ_DELEGATIONS" 
   (	"DELEGATION_ID" NUMBER(18,0), 
	"DELEGATE_PERSON_ID" NUMBER(18,0), 
	"PROXY_PERSON_ID" NUMBER(18,0), 
	"START_DATE" TIMESTAMP (6), 
	"END_DATE" TIMESTAMP (6), 
	"CREATION_DATE" TIMESTAMP (6) DEFAULT CURRENT_DATE, 
	"CREATED_BY" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"LAST_UPDATE_DATE" TIMESTAMP (6), 
	"LAST_UPDATED_BY" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"IS_ACTIVE" NUMBER(1,0)
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Table XXREQ_JOB_REQ_ENG_DEPARTMENTS
--------------------------------------------------------

  CREATE TABLE "XXREQ"."XXREQ_JOB_REQ_ENG_DEPARTMENTS" 
   (	"ENGINEERING_DEPARTMENT_ID" NUMBER, 
	"ENGINEERING_DEPARTMENT_NAME" VARCHAR2(250 CHAR) COLLATE "USING_NLS_COMP", 
	"ORA_DEPARTMENT_ID" NUMBER(18,0), 
	"ACTIVE_FLAG" NUMBER(1,0), 
	"CREATED_BY" VARCHAR2(64 CHAR) COLLATE "USING_NLS_COMP", 
	"CREATED_DATE" TIMESTAMP (6), 
	"LAST_UPDATED_BY" VARCHAR2(64 CHAR) COLLATE "USING_NLS_COMP", 
	"LAST_UPDATED_DATE" TIMESTAMP (6)
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Table XXREQ_JOB_REQ_REQUESTS
--------------------------------------------------------

  CREATE TABLE "XXREQ"."XXREQ_JOB_REQ_REQUESTS" 
   (	"REQUEST_ID" NUMBER(18,0), 
	"GH_REQUISITION_ID" VARCHAR2(30 CHAR) COLLATE "USING_NLS_COMP", 
	"REQ_TYPE_ID" NUMBER(10,0), 
	"MANAGE_OTHERS_FLAG" NUMBER(1,0) DEFAULT 0, 
	"EMP_ID" NUMBER(18,0), 
	"EXIT_DATE" DATE, 
	"REPORT_TO_MAN_ID" NUMBER(18,0), 
	"JOB_TITLE_ID" NUMBER, 
	"JOB_LEVEL_ID" VARCHAR2(20 CHAR) COLLATE "USING_NLS_COMP", 
	"DEPARTMENT_ID" NUMBER(18,0), 
	"BUDGET_HOLDER_ID" NUMBER(18,0), 
	"LOCATION_ID" NUMBER(18,0), 
	"RD_OR_SUPPORT_FLAG" NUMBER(1,0), 
	"SUITE_ID" NUMBER(10,0), 
	"MODULE_ID" NUMBER(10,0), 
	"DIVISION_ID" NUMBER(10,0), 
	"SALARY_BASE" NUMBER, 
	"VARIABLE_SALARY" NUMBER, 
	"EQUITY_APPROVED_FLAG" NUMBER(1,0), 
	"JOB_DESC" VARCHAR2(8000 BYTE) COLLATE "USING_NLS_COMP", 
	"STATUS_ID" NUMBER(18,0), 
	"CREATION_DATE" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
	"CREATED_BY" VARCHAR2(64 CHAR) COLLATE "USING_NLS_COMP", 
	"LAST_UPDATE_DATE" TIMESTAMP (6), 
	"LAST_UPDATED_BY" VARCHAR2(64 CHAR) COLLATE "USING_NLS_COMP", 
	"SUBMIT_DATE" TIMESTAMP (6), 
	"SUBMITTED_BY" VARCHAR2(64 CHAR) COLLATE "USING_NLS_COMP", 
	"LAST_SYNC_DATE_GH" TIMESTAMP (6), 
	"GH_REQUISITION_NAME" VARCHAR2(20 CHAR) COLLATE "USING_NLS_COMP", 
	"ACTIVE_FLAG" NUMBER(1,0) DEFAULT 1, 
	"SUBMIT_MESSAGE" VARCHAR2(600 CHAR) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Table XXREQ_JOB_REQ_TYPES
--------------------------------------------------------

  CREATE TABLE "XXREQ"."XXREQ_JOB_REQ_TYPES" 
   (	"REQUEST_TYPE_ID" NUMBER, 
	"REQUEST_TYPE_NAME" VARCHAR2(150 CHAR) COLLATE "USING_NLS_COMP", 
	"GH_REQUEST_TYPE_ID" NUMBER(12,0)
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Table XXREQ_JOB_REQ_STATUSES
--------------------------------------------------------

  CREATE TABLE "XXREQ"."XXREQ_JOB_REQ_STATUSES" 
   (	"STATUS_ID" NUMBER, 
	"STATUS_NAME" VARCHAR2(64 CHAR) COLLATE "USING_NLS_COMP", 
	"GH_STATUS_NAME" VARCHAR2(64 CHAR) COLLATE "USING_NLS_COMP", 
	"CREATED_BY" VARCHAR2(64 CHAR) COLLATE "USING_NLS_COMP", 
	"CREATED_DATE" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
	"LAST_UPDATED_BY" VARCHAR2(64 CHAR) COLLATE "USING_NLS_COMP", 
	"LAST_UPDATE_DATE" TIMESTAMP (6)
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
REM INSERTING into XXREQ.XXREQ_JOB_REQ_DELEGATIONS
SET DEFINE OFF;
REM INSERTING into XXREQ.XXREQ_JOB_REQ_ENG_DEPARTMENTS
SET DEFINE OFF;
Insert into XXREQ.XXREQ_JOB_REQ_ENG_DEPARTMENTS (ENGINEERING_DEPARTMENT_ID,ENGINEERING_DEPARTMENT_NAME,ORA_DEPARTMENT_ID,ACTIVE_FLAG,CREATED_BY,CREATED_DATE,LAST_UPDATED_BY,LAST_UPDATED_DATE) values (1,'Audit & Compliance',300000005433465,1,null,null,null,null);
Insert into XXREQ.XXREQ_JOB_REQ_ENG_DEPARTMENTS (ENGINEERING_DEPARTMENT_ID,ENGINEERING_DEPARTMENT_NAME,ORA_DEPARTMENT_ID,ACTIVE_FLAG,CREATED_BY,CREATED_DATE,LAST_UPDATED_BY,LAST_UPDATED_DATE) values (2,'Backup',300000005107862,1,null,null,null,null);
Insert into XXREQ.XXREQ_JOB_REQ_ENG_DEPARTMENTS (ENGINEERING_DEPARTMENT_ID,ENGINEERING_DEPARTMENT_NAME,ORA_DEPARTMENT_ID,ACTIVE_FLAG,CREATED_BY,CREATED_DATE,LAST_UPDATED_BY,LAST_UPDATED_DATE) values (3,'Big K',300000005433140,1,null,null,null,null);
Insert into XXREQ.XXREQ_JOB_REQ_ENG_DEPARTMENTS (ENGINEERING_DEPARTMENT_ID,ENGINEERING_DEPARTMENT_NAME,ORA_DEPARTMENT_ID,ACTIVE_FLAG,CREATED_BY,CREATED_DATE,LAST_UPDATED_BY,LAST_UPDATED_DATE) values (4,'Bravo',300000005433289,1,null,null,null,null);
Insert into XXREQ.XXREQ_JOB_REQ_ENG_DEPARTMENTS (ENGINEERING_DEPARTMENT_ID,ENGINEERING_DEPARTMENT_NAME,ORA_DEPARTMENT_ID,ACTIVE_FLAG,CREATED_BY,CREATED_DATE,LAST_UPDATED_BY,LAST_UPDATED_DATE) values (5,'CISO',300000005107207,1,null,null,null,null);
Insert into XXREQ.XXREQ_JOB_REQ_ENG_DEPARTMENTS (ENGINEERING_DEPARTMENT_ID,ENGINEERING_DEPARTMENT_NAME,ORA_DEPARTMENT_ID,ACTIVE_FLAG,CREATED_BY,CREATED_DATE,LAST_UPDATED_BY,LAST_UPDATED_DATE) values (6,'CISO - COGS',300000005433355,1,null,null,null,null);
Insert into XXREQ.XXREQ_JOB_REQ_ENG_DEPARTMENTS (ENGINEERING_DEPARTMENT_ID,ENGINEERING_DEPARTMENT_NAME,ORA_DEPARTMENT_ID,ACTIVE_FLAG,CREATED_BY,CREATED_DATE,LAST_UPDATED_BY,LAST_UPDATED_DATE) values (7,'Cloud to Cloud BDR',300000005433553,1,null,null,null,null);
Insert into XXREQ.XXREQ_JOB_REQ_ENG_DEPARTMENTS (ENGINEERING_DEPARTMENT_ID,ENGINEERING_DEPARTMENT_NAME,ORA_DEPARTMENT_ID,ACTIVE_FLAG,CREATED_BY,CREATED_DATE,LAST_UPDATED_BY,LAST_UPDATED_DATE) values (8,'Datto',300000005107795,1,null,null,null,null);
Insert into XXREQ.XXREQ_JOB_REQ_ENG_DEPARTMENTS (ENGINEERING_DEPARTMENT_ID,ENGINEERING_DEPARTMENT_NAME,ORA_DEPARTMENT_ID,ACTIVE_FLAG,CREATED_BY,CREATED_DATE,LAST_UPDATED_BY,LAST_UPDATED_DATE) values (9,'Executive',300000005107920,1,null,null,null,null);
Insert into XXREQ.XXREQ_JOB_REQ_ENG_DEPARTMENTS (ENGINEERING_DEPARTMENT_ID,ENGINEERING_DEPARTMENT_NAME,ORA_DEPARTMENT_ID,ACTIVE_FLAG,CREATED_BY,CREATED_DATE,LAST_UPDATED_BY,LAST_UPDATED_DATE) values (10,'Internal Systems',300000005107303,1,null,null,null,null);
Insert into XXREQ.XXREQ_JOB_REQ_ENG_DEPARTMENTS (ENGINEERING_DEPARTMENT_ID,ENGINEERING_DEPARTMENT_NAME,ORA_DEPARTMENT_ID,ACTIVE_FLAG,CREATED_BY,CREATED_DATE,LAST_UPDATED_BY,LAST_UPDATED_DATE) values (11,'IT Complete',300000005433223,1,null,null,null,null);
Insert into XXREQ.XXREQ_JOB_REQ_ENG_DEPARTMENTS (ENGINEERING_DEPARTMENT_ID,ENGINEERING_DEPARTMENT_NAME,ORA_DEPARTMENT_ID,ACTIVE_FLAG,CREATED_BY,CREATED_DATE,LAST_UPDATED_BY,LAST_UPDATED_DATE) values (12,'IT Operations',300000005107810,1,null,null,null,null);
Insert into XXREQ.XXREQ_JOB_REQ_ENG_DEPARTMENTS (ENGINEERING_DEPARTMENT_ID,ENGINEERING_DEPARTMENT_NAME,ORA_DEPARTMENT_ID,ACTIVE_FLAG,CREATED_BY,CREATED_DATE,LAST_UPDATED_BY,LAST_UPDATED_DATE) values (13,'Kaseya Security Labs',300000005107325,1,null,null,null,null);
Insert into XXREQ.XXREQ_JOB_REQ_ENG_DEPARTMENTS (ENGINEERING_DEPARTMENT_ID,ENGINEERING_DEPARTMENT_NAME,ORA_DEPARTMENT_ID,ACTIVE_FLAG,CREATED_BY,CREATED_DATE,LAST_UPDATED_BY,LAST_UPDATED_DATE) values (14,'MSP Enablement',300000005433432,1,null,null,null,null);
Insert into XXREQ.XXREQ_JOB_REQ_ENG_DEPARTMENTS (ENGINEERING_DEPARTMENT_ID,ENGINEERING_DEPARTMENT_NAME,ORA_DEPARTMENT_ID,ACTIVE_FLAG,CREATED_BY,CREATED_DATE,LAST_UPDATED_BY,LAST_UPDATED_DATE) values (15,'Networking',300000005433410,1,null,null,null,null);
Insert into XXREQ.XXREQ_JOB_REQ_ENG_DEPARTMENTS (ENGINEERING_DEPARTMENT_ID,ENGINEERING_DEPARTMENT_NAME,ORA_DEPARTMENT_ID,ACTIVE_FLAG,CREATED_BY,CREATED_DATE,LAST_UPDATED_BY,LAST_UPDATED_DATE) values (16,'Project S',300000005433096,1,null,null,null,null);
Insert into XXREQ.XXREQ_JOB_REQ_ENG_DEPARTMENTS (ENGINEERING_DEPARTMENT_ID,ENGINEERING_DEPARTMENT_NAME,ORA_DEPARTMENT_ID,ACTIVE_FLAG,CREATED_BY,CREATED_DATE,LAST_UPDATED_BY,LAST_UPDATED_DATE) values (17,'RMM',300000005107634,1,null,null,null,null);
Insert into XXREQ.XXREQ_JOB_REQ_ENG_DEPARTMENTS (ENGINEERING_DEPARTMENT_ID,ENGINEERING_DEPARTMENT_NAME,ORA_DEPARTMENT_ID,ACTIVE_FLAG,CREATED_BY,CREATED_DATE,LAST_UPDATED_BY,LAST_UPDATED_DATE) values (18,'Sales Lab',300000005433454,1,null,null,null,null);
Insert into XXREQ.XXREQ_JOB_REQ_ENG_DEPARTMENTS (ENGINEERING_DEPARTMENT_ID,ENGINEERING_DEPARTMENT_NAME,ORA_DEPARTMENT_ID,ACTIVE_FLAG,CREATED_BY,CREATED_DATE,LAST_UPDATED_BY,LAST_UPDATED_DATE) values (19,'Security',300000005107772,1,null,null,null,null);
Insert into XXREQ.XXREQ_JOB_REQ_ENG_DEPARTMENTS (ENGINEERING_DEPARTMENT_ID,ENGINEERING_DEPARTMENT_NAME,ORA_DEPARTMENT_ID,ACTIVE_FLAG,CREATED_BY,CREATED_DATE,LAST_UPDATED_BY,LAST_UPDATED_DATE) values (20,'Special Projects - R&D',300000005107317,1,null,null,null,null);
Insert into XXREQ.XXREQ_JOB_REQ_ENG_DEPARTMENTS (ENGINEERING_DEPARTMENT_ID,ENGINEERING_DEPARTMENT_NAME,ORA_DEPARTMENT_ID,ACTIVE_FLAG,CREATED_BY,CREATED_DATE,LAST_UPDATED_BY,LAST_UPDATED_DATE) values (21,'Technical Writers',300000005433267,1,null,null,null,null);

REM INSERTING into XXREQ.XXREQ_JOB_REQ_REQUESTS
SET DEFINE OFF;
REM INSERTING into XXREQ.XXREQ_JOB_REQ_TYPES
SET DEFINE OFF;
Insert into XXREQ.XXREQ_JOB_REQ_TYPES (REQUEST_TYPE_ID,REQUEST_TYPE_NAME,GH_REQUEST_TYPE_ID) values (1,'New',14010490004);
Insert into XXREQ.XXREQ_JOB_REQ_TYPES (REQUEST_TYPE_ID,REQUEST_TYPE_NAME,GH_REQUEST_TYPE_ID) values (2,'Backfill',14010491004);
Insert into XXREQ.XXREQ_JOB_REQ_TYPES (REQUEST_TYPE_ID,REQUEST_TYPE_NAME,GH_REQUEST_TYPE_ID) values (3,'Backfill - Shadow',14010492004);
Insert into XXREQ.XXREQ_JOB_REQ_TYPES (REQUEST_TYPE_ID,REQUEST_TYPE_NAME,GH_REQUEST_TYPE_ID) values (4,'Contractor',19749980004);
REM INSERTING into XXREQ.XXREQ_JOB_REQ_STATUSES
SET DEFINE OFF;
Insert into XXREQ.XXREQ_JOB_REQ_STATUSES (STATUS_ID,STATUS_NAME,GH_STATUS_NAME,CREATED_BY,CREATED_DATE,LAST_UPDATED_BY,LAST_UPDATE_DATE) values (1,'Not Submitted','NA',null,null,null,null);
Insert into XXREQ.XXREQ_JOB_REQ_STATUSES (STATUS_ID,STATUS_NAME,GH_STATUS_NAME,CREATED_BY,CREATED_DATE,LAST_UPDATED_BY,LAST_UPDATE_DATE) values (2,'Submitted','Draft',null,null,null,null);
Insert into XXREQ.XXREQ_JOB_REQ_STATUSES (STATUS_ID,STATUS_NAME,GH_STATUS_NAME,CREATED_BY,CREATED_DATE,LAST_UPDATED_BY,LAST_UPDATE_DATE) values (3,'Open','Approved',null,null,null,null);
Insert into XXREQ.XXREQ_JOB_REQ_STATUSES (STATUS_ID,STATUS_NAME,GH_STATUS_NAME,CREATED_BY,CREATED_DATE,LAST_UPDATED_BY,LAST_UPDATE_DATE) values (4,'Closed','Closed',null,null,null,null);

--------------------------------------------------------
--  DDL for Index XXREQ_JOB_REQ_DELEGATIONS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "XXREQ"."XXREQ_JOB_REQ_DELEGATIONS_PK" ON "XXREQ"."XXREQ_JOB_REQ_DELEGATIONS" ("DELEGATION_ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index XXREQ_JOB_REQ_ENGINEERING_DEPARTMENTS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "XXREQ"."XXREQ_JOB_REQ_ENGINEERING_DEPARTMENTS_PK" ON "XXREQ"."XXREQ_JOB_REQ_ENG_DEPARTMENTS" ("ENGINEERING_DEPARTMENT_ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index XXREQ_JOB_REQ_REQUESTS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "XXREQ"."XXREQ_JOB_REQ_REQUESTS_PK" ON "XXREQ"."XXREQ_JOB_REQ_REQUESTS" ("REQUEST_ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index XXREQ_JOB_REQ_REQUEST_TYPES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "XXREQ"."XXREQ_JOB_REQ_REQUEST_TYPES_PK" ON "XXREQ"."XXREQ_JOB_REQ_TYPES" ("REQUEST_TYPE_ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index XXREQ_JOB_REQ_REQUEST_STATUSES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "XXREQ"."XXREQ_JOB_REQ_REQUEST_STATUSES_PK" ON "XXREQ"."XXREQ_JOB_REQ_STATUSES" ("STATUS_ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Trigger XXREQ_JOB_REQ_DELEGATIONS_SEQ_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "XXREQ"."XXREQ_JOB_REQ_DELEGATIONS_SEQ_TRG" 
   before insert on "XXREQ"."XXREQ_JOB_REQ_DELEGATIONS" 
   for each row 
begin  
   if inserting then 
      if :NEW."DELEGATION_ID" is null then 
         select XXREQ_JOB_REQ_DELEGATIONSS_SEQ.nextval into :NEW."DELEGATION_ID" from dual; 
      end if; 
   end if; 
end;

/
ALTER TRIGGER "XXREQ"."XXREQ_JOB_REQ_DELEGATIONS_SEQ_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger XXREQ_JOB_REQ_ENGINEERING_DEPARTMENTS_SEQ_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "XXREQ"."XXREQ_JOB_REQ_ENGINEERING_DEPARTMENTS_SEQ_TRG" 
   before insert on "XXREQ"."XXREQ_JOB_REQ_ENG_DEPARTMENTS" 
   for each row 
begin  
   if inserting then 
      if :NEW."ENGINEERING_DEPARTMENT_ID" is null then 
         select XXREQ_JOB_REQ_ENGINEERING_DEPARTMENTS_SEQ.nextval into :NEW."ENGINEERING_DEPARTMENT_ID" from dual; 
      end if; 
   end if; 
end;

/
ALTER TRIGGER "XXREQ"."XXREQ_JOB_REQ_ENGINEERING_DEPARTMENTS_SEQ_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger XXREQ_JOB_REQ_REQUESTS_AUTO_NAME_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "XXREQ"."XXREQ_JOB_REQ_REQUESTS_AUTO_NAME_TRG" BEFORE INSERT ON "XXREQ"."XXREQ_JOB_REQ_REQUESTS" 
FOR EACH ROW
DECLARE  V_TODAY_DATE_STR VARCHAR(6);
V_LAST_SEQ_DATE_STR VARCHAR(6);
V_LAST_SEQ_DIGIT_NUM NUMBER;
V_NEW_FULL_SEQ VARCHAR(20);

BEGIN
IF INSERTING THEN
    IF :NEW."GH_REQUISITION_NAME" IS NULL THEN
        
        SELECT TO_CHAR(CURRENT_DATE, 'YYMMDD') INTO V_TODAY_DATE_STR FROM DUAL;
        SELECT NVL(MAX(REGEXP_SUBSTR(GH_REQUISITION_NAME,'(^|-)([^-]*)')), TO_CHAR(CURRENT_DATE, 'YYMMDD')) INTO V_LAST_SEQ_DATE_STR FROM XXREQ_JOB_REQ_REQUESTS;
        SELECT NVL(MAX(TO_NUMBER(REGEXP_SUBSTR(GH_REQUISITION_NAME,'(^|-)([^-]*)',1,2,NULL,2))),0) INTO V_LAST_SEQ_DIGIT_NUM FROM XXREQ_JOB_REQ_REQUESTS WHERE GH_REQUISITION_NAME LIKE V_LAST_SEQ_DATE_STR||'%';
        SELECT CASE WHEN (V_TODAY_DATE_STR > V_LAST_SEQ_DATE_STR) THEN V_TODAY_DATE_STR ||'-' || '1' ELSE V_LAST_SEQ_DATE_STR || '-' || TO_CHAR(V_LAST_SEQ_DIGIT_NUM + 1) END INTO V_NEW_FULL_SEQ;
      
        SELECT V_NEW_FULL_SEQ INTO :NEW."GH_REQUISITION_NAME";
        
    END IF;
END IF;
END;
/
ALTER TRIGGER "XXREQ"."XXREQ_JOB_REQ_REQUESTS_AUTO_NAME_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger XXREQ_JOB_REQ_REQUESTS_SEQ_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "XXREQ"."XXREQ_JOB_REQ_REQUESTS_SEQ_TRG" 
   before insert on "XXREQ"."XXREQ_JOB_REQ_REQUESTS" 
   for each row 
begin  
   if inserting then 
      if :NEW."REQUEST_ID" is null then 
         select XXREQ_JOB_REQ_REQUESTS_SEQ.nextval into :NEW."REQUEST_ID" from dual; 
      end if; 
   end if; 
end;

/
ALTER TRIGGER "XXREQ"."XXREQ_JOB_REQ_REQUESTS_SEQ_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger XXREQ_JOB_REQ_STATUSES_SEQ_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "XXREQ"."XXREQ_JOB_REQ_STATUSES_SEQ_TRG" 
   before insert on "XXREQ"."XXREQ_JOB_REQ_STATUSES" 
   for each row 
begin  
   if inserting then 
      if :NEW."STATUS_ID" is null then 
         select XXREQ_JOB_REQ_STATUSES_SEQ.nextval into :NEW."STATUS_ID" from dual; 
      end if; 
   end if; 
end;

/
ALTER TRIGGER "XXREQ"."XXREQ_JOB_REQ_STATUSES_SEQ_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger XXREQ_JOB_REQ_TYPES_SEQ_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "XXREQ"."XXREQ_JOB_REQ_TYPES_SEQ_TRG" 
   before insert on "XXREQ"."XXREQ_JOB_REQ_TYPES" 
   for each row 
begin  
   if inserting then 
      if :NEW."REQUEST_TYPE_ID" is null then 
         select XXREQ_JOB_REQ_TYPES_SEQ.nextval into :NEW."REQUEST_TYPE_ID" from dual; 
      end if; 
   end if; 
end;

/
ALTER TRIGGER "XXREQ"."XXREQ_JOB_REQ_TYPES_SEQ_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger XXREQ_JOB_REQ_DELEGATIONS_SEQ_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "XXREQ"."XXREQ_JOB_REQ_DELEGATIONS_SEQ_TRG" 
   before insert on "XXREQ"."XXREQ_JOB_REQ_DELEGATIONS" 
   for each row 
begin  
   if inserting then 
      if :NEW."DELEGATION_ID" is null then 
         select XXREQ_JOB_REQ_DELEGATIONSS_SEQ.nextval into :NEW."DELEGATION_ID" from dual; 
      end if; 
   end if; 
end;

/
ALTER TRIGGER "XXREQ"."XXREQ_JOB_REQ_DELEGATIONS_SEQ_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger XXREQ_JOB_REQ_ENGINEERING_DEPARTMENTS_SEQ_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "XXREQ"."XXREQ_JOB_REQ_ENGINEERING_DEPARTMENTS_SEQ_TRG" 
   before insert on "XXREQ"."XXREQ_JOB_REQ_ENG_DEPARTMENTS" 
   for each row 
begin  
   if inserting then 
      if :NEW."ENGINEERING_DEPARTMENT_ID" is null then 
         select XXREQ_JOB_REQ_ENGINEERING_DEPARTMENTS_SEQ.nextval into :NEW."ENGINEERING_DEPARTMENT_ID" from dual; 
      end if; 
   end if; 
end;

/
ALTER TRIGGER "XXREQ"."XXREQ_JOB_REQ_ENGINEERING_DEPARTMENTS_SEQ_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger XXREQ_JOB_REQ_REQUESTS_SEQ_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "XXREQ"."XXREQ_JOB_REQ_REQUESTS_SEQ_TRG" 
   before insert on "XXREQ"."XXREQ_JOB_REQ_REQUESTS" 
   for each row 
begin  
   if inserting then 
      if :NEW."REQUEST_ID" is null then 
         select XXREQ_JOB_REQ_REQUESTS_SEQ.nextval into :NEW."REQUEST_ID" from dual; 
      end if; 
   end if; 
end;

/
ALTER TRIGGER "XXREQ"."XXREQ_JOB_REQ_REQUESTS_SEQ_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger XXREQ_JOB_REQ_REQUESTS_AUTO_NAME_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "XXREQ"."XXREQ_JOB_REQ_REQUESTS_AUTO_NAME_TRG" BEFORE INSERT ON "XXREQ"."XXREQ_JOB_REQ_REQUESTS" 
FOR EACH ROW
DECLARE  V_TODAY_DATE_STR VARCHAR(6);
V_LAST_SEQ_DATE_STR VARCHAR(6);
V_LAST_SEQ_DIGIT_NUM NUMBER;
V_NEW_FULL_SEQ VARCHAR(20);

BEGIN
IF INSERTING THEN
    IF :NEW."GH_REQUISITION_NAME" IS NULL THEN
        
        SELECT TO_CHAR(CURRENT_DATE, 'YYMMDD') INTO V_TODAY_DATE_STR FROM DUAL;
        SELECT NVL(MAX(REGEXP_SUBSTR(GH_REQUISITION_NAME,'(^|-)([^-]*)')), TO_CHAR(CURRENT_DATE, 'YYMMDD')) INTO V_LAST_SEQ_DATE_STR FROM XXREQ_JOB_REQ_REQUESTS;
        SELECT NVL(MAX(TO_NUMBER(REGEXP_SUBSTR(GH_REQUISITION_NAME,'(^|-)([^-]*)',1,2,NULL,2))),0) INTO V_LAST_SEQ_DIGIT_NUM FROM XXREQ_JOB_REQ_REQUESTS WHERE GH_REQUISITION_NAME LIKE V_LAST_SEQ_DATE_STR||'%';
        SELECT CASE WHEN (V_TODAY_DATE_STR > V_LAST_SEQ_DATE_STR) THEN V_TODAY_DATE_STR ||'-' || '1' ELSE V_LAST_SEQ_DATE_STR || '-' || TO_CHAR(V_LAST_SEQ_DIGIT_NUM + 1) END INTO V_NEW_FULL_SEQ;
      
        SELECT V_NEW_FULL_SEQ INTO :NEW."GH_REQUISITION_NAME";
        
    END IF;
END IF;
END;
/
ALTER TRIGGER "XXREQ"."XXREQ_JOB_REQ_REQUESTS_AUTO_NAME_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger XXREQ_JOB_REQ_TYPES_SEQ_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "XXREQ"."XXREQ_JOB_REQ_TYPES_SEQ_TRG" 
   before insert on "XXREQ"."XXREQ_JOB_REQ_TYPES" 
   for each row 
begin  
   if inserting then 
      if :NEW."REQUEST_TYPE_ID" is null then 
         select XXREQ_JOB_REQ_TYPES_SEQ.nextval into :NEW."REQUEST_TYPE_ID" from dual; 
      end if; 
   end if; 
end;

/
ALTER TRIGGER "XXREQ"."XXREQ_JOB_REQ_TYPES_SEQ_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger XXREQ_JOB_REQ_STATUSES_SEQ_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "XXREQ"."XXREQ_JOB_REQ_STATUSES_SEQ_TRG" 
   before insert on "XXREQ"."XXREQ_JOB_REQ_STATUSES" 
   for each row 
begin  
   if inserting then 
      if :NEW."STATUS_ID" is null then 
         select XXREQ_JOB_REQ_STATUSES_SEQ.nextval into :NEW."STATUS_ID" from dual; 
      end if; 
   end if; 
end;

/
ALTER TRIGGER "XXREQ"."XXREQ_JOB_REQ_STATUSES_SEQ_TRG" ENABLE;

--------------------------------------------------------
--  Constraints for Table XXREQ_JOB_REQ_DELEGATIONS
--------------------------------------------------------

  ALTER TABLE "XXREQ"."XXREQ_JOB_REQ_DELEGATIONS" MODIFY ("DELEGATION_ID" NOT NULL ENABLE);
  ALTER TABLE "XXREQ"."XXREQ_JOB_REQ_DELEGATIONS" ADD CONSTRAINT "XXREQ_JOB_REQ_DELEGATIONS_PK" PRIMARY KEY ("DELEGATION_ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 
  TABLESPACE "DATA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table XXREQ_JOB_REQ_ENG_DEPARTMENTS
--------------------------------------------------------

  ALTER TABLE "XXREQ"."XXREQ_JOB_REQ_ENG_DEPARTMENTS" MODIFY ("ENGINEERING_DEPARTMENT_ID" NOT NULL ENABLE);
  ALTER TABLE "XXREQ"."XXREQ_JOB_REQ_ENG_DEPARTMENTS" ADD CONSTRAINT "XXREQ_JOB_REQ_ENGINEERING_DEPARTMENTS_PK" PRIMARY KEY ("ENGINEERING_DEPARTMENT_ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table XXREQ_JOB_REQ_REQUESTS
--------------------------------------------------------

  ALTER TABLE "XXREQ"."XXREQ_JOB_REQ_REQUESTS" ADD CONSTRAINT "XXREQ_JOB_REQ_REQUESTS_CHK_BOOL_EQ" CHECK (EQUITY_APPROVED_FLAG IN (1,0)) ENABLE;
  ALTER TABLE "XXREQ"."XXREQ_JOB_REQ_REQUESTS" ADD CONSTRAINT "XXREQ_JOB_REQ_REQUESTS_CHK_BOOL_RD" CHECK (RD_OR_SUPPORT_FLAG IN (1,0)) ENABLE;
  ALTER TABLE "XXREQ"."XXREQ_JOB_REQ_REQUESTS" ADD CONSTRAINT "XXREQ_JOB_REQ_REQUESTS_CHK_BOOL_MAN" CHECK (manage_others_flag in (1,0)) ENABLE;
  ALTER TABLE "XXREQ"."XXREQ_JOB_REQ_REQUESTS" ADD CONSTRAINT "XXREQ_JOB_REQ_REQUESTS_PK" PRIMARY KEY ("REQUEST_ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
  ALTER TABLE "XXREQ"."XXREQ_JOB_REQ_REQUESTS" MODIFY ("REQUEST_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table XXREQ_JOB_REQ_TYPES
--------------------------------------------------------

  ALTER TABLE "XXREQ"."XXREQ_JOB_REQ_TYPES" ADD CONSTRAINT "XXREQ_JOB_REQ_REQUEST_TYPES_PK" PRIMARY KEY ("REQUEST_TYPE_ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
  ALTER TABLE "XXREQ"."XXREQ_JOB_REQ_TYPES" MODIFY ("REQUEST_TYPE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table XXREQ_JOB_REQ_STATUSES
--------------------------------------------------------

  ALTER TABLE "XXREQ"."XXREQ_JOB_REQ_STATUSES" MODIFY ("STATUS_ID" NOT NULL ENABLE);
  ALTER TABLE "XXREQ"."XXREQ_JOB_REQ_STATUSES" ADD CONSTRAINT "XXREQ_JOB_REQ_REQUEST_STATUSES_PK" PRIMARY KEY ("STATUS_ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table XXREQ_JOB_REQ_REQUESTS
--------------------------------------------------------

  ALTER TABLE "XXREQ"."XXREQ_JOB_REQ_REQUESTS" ADD CONSTRAINT "XXREQ_JOB_REQ_STATUSES_FK" FOREIGN KEY ("STATUS_ID")
	  REFERENCES "XXREQ"."XXREQ_JOB_REQ_STATUSES" ("STATUS_ID") ENABLE;
  ALTER TABLE "XXREQ"."XXREQ_JOB_REQ_REQUESTS" ADD CONSTRAINT "XXREQ_JOB_REQ_REQ_TYPES_FK" FOREIGN KEY ("REQ_TYPE_ID")
	  REFERENCES "XXREQ"."XXREQ_JOB_REQ_TYPES" ("REQUEST_TYPE_ID") ENABLE;
