INSERT INTO xxint.xxint_xx_i010_common_rice_objects_ref (
    interface_rice_id,
    table_owner,
    atp_db_purge_flag,
    atp_db_purge_freq_days,
    table_name,
    arc_table_name,
    arc_table_owner,
    arc_flag,
    attribute1,
    tbl_creation_date_format
) VALUES ( 'XX_I024',
           'XXAUD',
           'Y',
           '40',
           'XXAUD_XX_I024_OCI_EVENT_AUDIT_LOGS',
           'XXAUD_XX_I024_OCI_EVENT_AUDIT_LOGS_ARC',
           'XXAUD',
           'Y',
           10000,
           'YYYY-MM-DD' ), ( 'XX_I024',
                             'XXAUD',
                             'Y',
                             '100',
                             'XXAUD_XX_I024_OCI_EVENT_AUDIT_LOGS_ARC',
                             NULL,
                             'XXAUD',
                             'N',
                             10000,
                             'YYYY-MM-DD' );