GRANT SELECT ON "XXINT"."XXINT_HCM_116_GREENHOUSE_INBOUND" TO "XXRO";
GRANT SELECT ON "XXINT"."XXINT_HCM_116_EMPLOYEES_DATA" TO "XXRO";
GRANT SELECT ON "XXINT"."XXINT_HCM_116_GREENHOUSE_LOCATION_MAPPING_UDT" TO "XXRO";